"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, TextNode

"""Markdown node parser."""
class MarkdownNodeParser(NodeParser):
    """
    Markdown node parser.

    Splits a document into Nodes using Markdown header-based splitting logic.
    Each node contains its text content and the path of headers leading to it.

    Args:
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships
        header_path_separator (str): separator char used for section header path metadata

    """
    header_path_separator: str = ...
    @classmethod
    def from_defaults(cls, include_metadata: bool = ..., include_prev_next_rel: bool = ..., header_path_separator: str = ..., callback_manager: Optional[CallbackManager] = ...) -> MarkdownNodeParser:
        ...
    
    def get_nodes_from_node(self, node: BaseNode) -> List[TextNode]:
        """Get nodes from document by splitting on headers."""
        ...
    


