"""
This type stub file was generated by pyright.
"""

from typing import List
from llama_index.core.indices.query.schema import QueryType
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.schema import NodeWithScore

class BaseImageRetriever(PromptMixin, DispatcherSpanMixin):
    """Base Image Retriever Abstraction."""
    def text_to_image_retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        """
        Retrieve image nodes given query or single image input.

        Args:
            str_or_query_bundle (QueryType): a query text
            string or a QueryBundle object.

        """
        ...
    
    def image_to_image_retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        """
        Retrieve image nodes given single image input.

        Args:
            str_or_query_bundle (QueryType): a image path
            string or a QueryBundle object.

        """
        ...
    
    async def atext_to_image_retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        ...
    
    async def aimage_to_image_retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        ...
    


