"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from dataclasses import dataclass
from enum import Enum
from io import BytesIO
from pathlib import Path
from typing import Annotated, Any, Dict, List, Literal, Optional, Sequence, TYPE_CHECKING, Union
from dataclasses_json import DataClassJsonMixin
from deprecated import deprecated
from typing_extensions import Self
from llama_index.core.bridge.pydantic import AnyUrl, BaseModel, GetJsonSchemaHandler, JsonSchemaValue, SerializationInfo, SerializeAsAny, SerializerFunctionWrapHandler, ValidationInfo, field_serializer, field_validator, model_serializer
from llama_index.core.bridge.pydantic_core import CoreSchema
from llama_index.core.instrumentation import DispatcherSpanMixin
from haystack.schema import Document as HaystackDocument
from llama_cloud.types.cloud_document import CloudDocument
from semantic_kernel.memory.memory_record import MemoryRecord
from llama_index.core.bridge.langchain import Document as LCDocument

"""Base schema for data structures."""
if TYPE_CHECKING:
    ...
DEFAULT_TEXT_NODE_TMPL = ...
DEFAULT_METADATA_TMPL = ...
TRUNCATE_LENGTH = ...
WRAP_WIDTH = ...
ImageType = Union[str, BytesIO]
logger = ...
EnumNameSerializer = ...
class BaseComponent(BaseModel):
    """Base component object to capture class names."""
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: CoreSchema, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        """
        Get the class name, used as a unique ID in serialization.

        This provides a key that makes serialization robust against actual class
        name changes.
        """
        ...
    
    def json(self, **kwargs: Any) -> str:
        ...
    
    @model_serializer(mode="wrap")
    def custom_model_dump(self, handler: SerializerFunctionWrapHandler, info: SerializationInfo) -> Dict[str, Any]:
        ...
    
    def dict(self, **kwargs: Any) -> Dict[str, Any]:
        ...
    
    def __getstate__(self) -> Dict[str, Any]:
        ...
    
    def __setstate__(self, state: Dict[str, Any]) -> None:
        ...
    
    def to_dict(self, **kwargs: Any) -> Dict[str, Any]:
        ...
    
    def to_json(self, **kwargs: Any) -> str:
        ...
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> Self:
        ...
    
    @classmethod
    def from_json(cls, data_str: str, **kwargs: Any) -> Self:
        ...
    


class TransformComponent(BaseComponent, DispatcherSpanMixin):
    """Base class for transform components."""
    model_config = ...
    @abstractmethod
    def __call__(self, nodes: Sequence[BaseNode], **kwargs: Any) -> Sequence[BaseNode]:
        """Transform nodes."""
        ...
    
    async def acall(self, nodes: Sequence[BaseNode], **kwargs: Any) -> Sequence[BaseNode]:
        """Async transform nodes."""
        ...
    


class NodeRelationship(str, Enum):
    """
    Node relationships used in `BaseNode` class.

    Attributes:
        SOURCE: The node is the source document.
        PREVIOUS: The node is the previous node in the document.
        NEXT: The node is the next node in the document.
        PARENT: The node is the parent node in the document.
        CHILD: The node is a child node in the document.

    """
    SOURCE = ...
    PREVIOUS = ...
    NEXT = ...
    PARENT = ...
    CHILD = ...


class ObjectType(str, Enum):
    TEXT = ...
    IMAGE = ...
    INDEX = ...
    DOCUMENT = ...
    MULTIMODAL = ...


class Modality(str, Enum):
    TEXT = ...
    IMAGE = ...
    AUDIO = ...
    VIDEO = ...


class MetadataMode(str, Enum):
    ALL = ...
    EMBED = ...
    LLM = ...
    NONE = ...


class RelatedNodeInfo(BaseComponent):
    node_id: str
    node_type: Annotated[ObjectType, EnumNameSerializer] | str | None = ...
    metadata: Dict[str, Any] = ...
    hash: Optional[str] = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


RelatedNodeType = Union[RelatedNodeInfo, List[RelatedNodeInfo]]
class BaseNode(BaseComponent):
    """
    Base node Object.

    Generic abstract interface for retrievable nodes

    """
    model_config = ...
    id_: str = ...
    embedding: Optional[List[float]] = ...
    metadata: Dict[str, Any] = ...
    excluded_embed_metadata_keys: List[str] = ...
    excluded_llm_metadata_keys: List[str] = ...
    relationships: Dict[Annotated[NodeRelationship, EnumNameSerializer], RelatedNodeType,] = ...
    metadata_template: str = ...
    metadata_separator: str = ...
    @classmethod
    @abstractmethod
    def get_type(cls) -> str:
        """Get Object type."""
        ...
    
    @abstractmethod
    def get_content(self, metadata_mode: MetadataMode = ...) -> str:
        """Get object content."""
        ...
    
    def get_metadata_str(self, mode: MetadataMode = ...) -> str:
        """Metadata info string."""
        ...
    
    @abstractmethod
    def set_content(self, value: Any) -> None:
        """Set the content of the node."""
        ...
    
    @property
    @abstractmethod
    def hash(self) -> str:
        """Get hash of node."""
        ...
    
    @property
    def node_id(self) -> str:
        ...
    
    @node_id.setter
    def node_id(self, value: str) -> None:
        ...
    
    @property
    def source_node(self) -> Optional[RelatedNodeInfo]:
        """
        Source object node.

        Extracted from the relationships field.

        """
        ...
    
    @property
    def prev_node(self) -> Optional[RelatedNodeInfo]:
        """Prev node."""
        ...
    
    @property
    def next_node(self) -> Optional[RelatedNodeInfo]:
        """Next node."""
        ...
    
    @property
    def parent_node(self) -> Optional[RelatedNodeInfo]:
        """Parent node."""
        ...
    
    @property
    def child_nodes(self) -> Optional[List[RelatedNodeInfo]]:
        """Child nodes."""
        ...
    
    @property
    def ref_doc_id(self) -> Optional[str]:
        """Deprecated: Get ref doc id."""
        ...
    
    @property
    @deprecated(version="0.12.2", reason="'extra_info' is deprecated, use 'metadata' instead.")
    def extra_info(self) -> dict[str, Any]:
        ...
    
    @extra_info.setter
    @deprecated(version="0.12.2", reason="'extra_info' is deprecated, use 'metadata' instead.")
    def extra_info(self, extra_info: dict[str, Any]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def get_embedding(self) -> List[float]:
        """
        Get embedding.

        Errors if embedding is None.

        """
        ...
    
    def as_related_node_info(self) -> RelatedNodeInfo:
        """Get node as RelatedNodeInfo."""
        ...
    


EmbeddingKind = Literal["sparse", "dense"]
class MediaResource(BaseModel):
    """
    A container class for media content.

    This class represents a generic media resource that can be stored and accessed
    in multiple ways - as raw bytes, on the filesystem, or via URL. It also supports
    storing vector embeddings for the media content.

    Attributes:
        embeddings: Multi-vector dict representation of this resource for embedding-based search/retrieval
        text: Plain text representation of this resource
        data: Raw binary data of the media content
        mimetype: The MIME type indicating the format/type of the media content
        path: Local filesystem path where the media content can be accessed
        url: URL where the media content can be accessed remotely

    """
    embeddings: dict[EmbeddingKind, list[float]] | None = ...
    data: bytes | None = ...
    text: str | None = ...
    path: Path | None = ...
    url: AnyUrl | None = ...
    mimetype: str | None = ...
    model_config = ...
    @field_validator("data", mode="after")
    @classmethod
    def validate_data(cls, v: bytes | None, info: ValidationInfo) -> bytes | None:
        """
        If binary data was passed, store the resource as base64 and guess the mimetype when possible.

        In case the model was built passing binary data but without a mimetype,
        we try to guess it using the filetype library. To avoid resource-intense
        operations, we won't load the path or the URL to guess the mimetype.
        """
        ...
    
    @field_validator("mimetype", mode="after")
    @classmethod
    def validate_mimetype(cls, v: str | None, info: ValidationInfo) -> str | None:
        ...
    
    @field_serializer("path")
    def serialize_path(self, path: Optional[Path], _info: ValidationInfo) -> Optional[str]:
        ...
    
    @property
    def hash(self) -> str:
        """
        Generate a hash to uniquely identify the media resource.

        The hash is generated based on the available content (data, path, text or url).
        Returns an empty string if no content is available.
        """
        ...
    


class Node(BaseNode):
    text_resource: MediaResource | None = ...
    image_resource: MediaResource | None = ...
    audio_resource: MediaResource | None = ...
    video_resource: MediaResource | None = ...
    text_template: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @classmethod
    def get_type(cls) -> str:
        """Get Object type."""
        ...
    
    def get_content(self, metadata_mode: MetadataMode = ...) -> str:
        """
        Get the text content for the node if available.

        Provided for backward compatibility, use self.text_resource directly instead.
        """
        ...
    
    def set_content(self, value: str) -> None:
        """
        Set the text content of the node.

        Provided for backward compatibility, set self.text_resource instead.
        """
        ...
    
    @property
    def hash(self) -> str:
        """
        Generate a hash representing the state of the node.

        The hash is generated based on the available resources (audio, image, text or video) and its metadata.
        """
        ...
    


class TextNode(BaseNode):
    """
    Provided for backward compatibility.

    Note: we keep the field with the typo "seperator" to maintain backward compatibility for
    serialized objects.
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Make TextNode forward-compatible with Node by supporting 'text_resource' in the constructor."""
        ...
    
    text: str = ...
    mimetype: str = ...
    start_char_idx: Optional[int] = ...
    end_char_idx: Optional[int] = ...
    metadata_seperator: str = ...
    text_template: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @property
    def hash(self) -> str:
        ...
    
    @classmethod
    def get_type(cls) -> str:
        """Get Object type."""
        ...
    
    def get_content(self, metadata_mode: MetadataMode = ...) -> str:
        """Get object content."""
        ...
    
    def get_metadata_str(self, mode: MetadataMode = ...) -> str:
        """Metadata info string."""
        ...
    
    def set_content(self, value: str) -> None:
        """Set the content of the node."""
        ...
    
    def get_node_info(self) -> Dict[str, Any]:
        """Get node info."""
        ...
    
    def get_text(self) -> str:
        ...
    
    @property
    @deprecated(version="0.12.2", reason="'node_info' is deprecated, use 'get_node_info' instead.")
    def node_info(self) -> Dict[str, Any]:
        """Deprecated: Get node info."""
        ...
    


class ImageNode(TextNode):
    """Node with image."""
    image: Optional[str] = ...
    image_path: Optional[str] = ...
    image_url: Optional[str] = ...
    image_mimetype: Optional[str] = ...
    text_embedding: Optional[List[float]] = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Make ImageNode forward-compatible with Node by supporting 'image_resource' in the constructor."""
        ...
    
    @classmethod
    def get_type(cls) -> str:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def resolve_image(self) -> ImageType:
        """Resolve an image such that PIL can read it."""
        ...
    
    @property
    def hash(self) -> str:
        """Get hash of node."""
        ...
    


class IndexNode(TextNode):
    """
    Node with reference to any object.

    This can include other indices, query engines, retrievers.

    This can also include other nodes (though this is overlapping with `relationships`
    on the Node class).

    """
    index_id: str
    obj: Any = ...
    def dict(self, **kwargs: Any) -> Dict[str, Any]:
        ...
    
    @classmethod
    def from_text_node(cls, node: TextNode, index_id: str) -> IndexNode:
        """Create index node from text node."""
        ...
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> Self:
        ...
    
    @classmethod
    def get_type(cls) -> str:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


class NodeWithScore(BaseComponent):
    node: SerializeAsAny[BaseNode]
    score: Optional[float] = ...
    def __str__(self) -> str:
        ...
    
    def get_score(self, raise_error: bool = ...) -> float:
        """Get score."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @property
    def node_id(self) -> str:
        ...
    
    @property
    def id_(self) -> str:
        ...
    
    @property
    def text(self) -> str:
        ...
    
    @property
    def metadata(self) -> Dict[str, Any]:
        ...
    
    @property
    def embedding(self) -> Optional[List[float]]:
        ...
    
    def get_text(self) -> str:
        ...
    
    def get_content(self, metadata_mode: MetadataMode = ...) -> str:
        ...
    
    def get_embedding(self) -> List[float]:
        ...
    


class Document(Node):
    """
    Generic interface for a data document.

    This document connects to data sources.
    """
    def __init__(self, **data: Any) -> None:
        """
        Keeps backward compatibility with old 'Document' versions.

        If 'text' was passed, store it in 'text_resource'.
        If 'doc_id' was passed, store it in 'id_'.
        If 'extra_info' was passed, store it in 'metadata'.
        """
        ...
    
    @model_serializer(mode="wrap")
    def custom_model_dump(self, handler: SerializerFunctionWrapHandler, info: SerializationInfo) -> Dict[str, Any]:
        """For full backward compatibility with the text field, we customize the model serializer."""
        ...
    
    @property
    def text(self) -> str:
        """Provided for backward compatibility, it returns the content of text_resource."""
        ...
    
    @classmethod
    def get_type(cls) -> str:
        """Get Document type."""
        ...
    
    @property
    def doc_id(self) -> str:
        """Get document ID."""
        ...
    
    @doc_id.setter
    def doc_id(self, id_: str) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @deprecated(version="0.12.2", reason="'get_doc_id' is deprecated, access the 'id_' property instead.")
    def get_doc_id(self) -> str:
        ...
    
    def to_langchain_format(self) -> LCDocument:
        """Convert struct to LangChain document format."""
        ...
    
    @classmethod
    def from_langchain_format(cls, doc: LCDocument) -> Document:
        """Convert struct from LangChain document format."""
        ...
    
    def to_haystack_format(self) -> HaystackDocument:
        """Convert struct to Haystack document format."""
        ...
    
    @classmethod
    def from_haystack_format(cls, doc: HaystackDocument) -> Document:
        """Convert struct from Haystack document format."""
        ...
    
    def to_embedchain_format(self) -> Dict[str, Any]:
        """Convert struct to EmbedChain document format."""
        ...
    
    @classmethod
    def from_embedchain_format(cls, doc: Dict[str, Any]) -> Document:
        """Convert struct from EmbedChain document format."""
        ...
    
    def to_semantic_kernel_format(self) -> MemoryRecord:
        """Convert struct to Semantic Kernel document format."""
        ...
    
    @classmethod
    def from_semantic_kernel_format(cls, doc: MemoryRecord) -> Document:
        """Convert struct from Semantic Kernel document format."""
        ...
    
    def to_vectorflow(self, client: Any) -> None:
        """Send a document to vectorflow, since they don't have a document object."""
        ...
    
    @classmethod
    def example(cls) -> Document:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def to_cloud_document(self) -> CloudDocument:
        """Convert to LlamaCloud document type."""
        ...
    
    @classmethod
    def from_cloud_document(cls, doc: CloudDocument) -> Document:
        """Convert from LlamaCloud document type."""
        ...
    


def is_image_pil(file_path: str) -> bool:
    ...

def is_image_url_pil(url: str) -> bool:
    ...

class ImageDocument(Document):
    """Backward compatible wrapper around Document containing an image."""
    def __init__(self, **kwargs: Any) -> None:
        ...
    
    @property
    def image(self) -> str | None:
        ...
    
    @image.setter
    def image(self, image: str) -> None:
        ...
    
    @property
    def image_path(self) -> str | None:
        ...
    
    @image_path.setter
    def image_path(self, image_path: str) -> None:
        ...
    
    @property
    def image_url(self) -> str | None:
        ...
    
    @image_url.setter
    def image_url(self, image_url: str) -> None:
        ...
    
    @property
    def image_mimetype(self) -> str | None:
        ...
    
    @image_mimetype.setter
    def image_mimetype(self, image_mimetype: str) -> None:
        ...
    
    @property
    def text_embedding(self) -> list[float] | None:
        ...
    
    @text_embedding.setter
    def text_embedding(self, embeddings: list[float]) -> None:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def resolve_image(self, as_base64: bool = ...) -> BytesIO:
        """
        Resolve an image such that PIL can read it.

        Args:
            as_base64 (bool): whether the resolved image should be returned as base64-encoded bytes

        """
        ...
    


@dataclass
class QueryBundle(DataClassJsonMixin):
    """
    Query bundle.

    This dataclass contains the original query string and associated transformations.

    Args:
        query_str (str): the original user-specified query string.
            This is currently used by all non embedding-based queries.
        custom_embedding_strs (list[str]): list of strings used for embedding the query.
            This is currently used by all embedding-based queries.
        embedding (list[float]): the stored embedding for the query.

    """
    query_str: str
    image_path: Optional[str] = ...
    custom_embedding_strs: Optional[List[str]] = ...
    embedding: Optional[List[float]] = ...
    @property
    def embedding_strs(self) -> List[str]:
        """Use custom embedding strs if specified, otherwise use query str."""
        ...
    
    @property
    def embedding_image(self) -> List[ImageType]:
        """Use image path for image retrieval."""
        ...
    
    def __str__(self) -> str:
        """Convert to string representation."""
        ...
    


QueryType = Union[str, QueryBundle]
