"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class ServiceContext:
    """
    Service Context container.

    NOTE: Deprecated, use llama_index.settings.Settings instead or pass in
    modules to local functions/methods/interfaces.

    """
    def __init__(self, **kwargs: Any) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, **kwargs: Any) -> ServiceContext:
        """
        Create a ServiceContext from defaults.

        NOTE: Deprecated, use llama_index.settings.Settings instead or pass in
        modules to local functions/methods/interfaces.

        """
        ...
    


def set_global_service_context(service_context: Optional[ServiceContext]) -> None:
    """Helper function to set the global service context."""
    ...

