"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Any, AsyncGenerator, Callable, Dict, Generator, Iterable, List, Optional, Protocol, Set, TYPE_CHECKING, Type, Union, runtime_checkable
from nltk.tokenize import PunktSentenceTokenizer

"""General utils functions."""
if TYPE_CHECKING:
    ...
class GlobalsHelper:
    """Helper to retrieve globals with asynchronous NLTK data loading."""
    _stopwords: Optional[List[str]] = ...
    _punkt_tokenizer: Optional[PunktSentenceTokenizer] = ...
    _nltk_data_dir: Optional[str] = ...
    def wait_for_nltk_check(self) -> None:
        """Initialize NLTK data download."""
        ...
    
    @property
    def stopwords(self) -> List[str]:
        """Get stopwords, ensuring data is downloaded."""
        ...
    
    @property
    def punkt_tokenizer(self) -> PunktSentenceTokenizer:
        """Get punkt tokenizer, ensuring data is downloaded."""
        ...
    


globals_helper = ...
@runtime_checkable
class Tokenizer(Protocol):
    def encode(self, text: str, *args: Any, **kwargs: Any) -> List[Any]:
        ...
    


def set_global_tokenizer(tokenizer: Union[Tokenizer, Callable[[str], list]]) -> None:
    ...

def get_tokenizer(model_name: str = ...) -> Callable[[str], List]:
    ...

def get_new_id(d: Set) -> str:
    """Get a new ID."""
    ...

def get_new_int_id(d: Set) -> int:
    """Get a new integer ID."""
    ...

@contextmanager
def temp_set_attrs(obj: Any, **kwargs: Any) -> Generator:
    """
    Temporary setter.

    Utility class for setting a temporary value for an attribute on a class.
    Taken from: https://tinyurl.com/2p89xymh

    """
    ...

@dataclass
class ErrorToRetry:
    """
    Exception types that should be retried.

    Args:
        exception_cls (Type[Exception]): Class of exception.
        check_fn (Optional[Callable[[Any]], bool]]):
            A function that takes an exception instance as input and returns
            whether to retry.

    """
    exception_cls: Type[Exception]
    check_fn: Optional[Callable[[Any], bool]] = ...


def retry_on_exceptions_with_backoff(lambda_fn: Callable, errors_to_retry: List[ErrorToRetry], max_tries: int = ..., min_backoff_secs: float = ..., max_backoff_secs: float = ...) -> Any:
    """
    Execute lambda function with retries and exponential backoff.

    Args:
        lambda_fn (Callable): Function to be called and output we want.
        errors_to_retry (List[ErrorToRetry]): List of errors to retry.
            At least one needs to be provided.
        max_tries (int): Maximum number of tries, including the first. Defaults to 10.
        min_backoff_secs (float): Minimum amount of backoff time between attempts.
            Defaults to 0.5.
        max_backoff_secs (float): Maximum amount of backoff time between attempts.
            Defaults to 60.

    """
    ...

async def aretry_on_exceptions_with_backoff(async_fn: Callable, errors_to_retry: List[ErrorToRetry], max_tries: int = ..., min_backoff_secs: float = ..., max_backoff_secs: float = ...) -> Any:
    """
    Execute lambda function with retries and exponential backoff.

    Args:
        async_fn (Callable): Async Function to be called and output we want.
        errors_to_retry (List[ErrorToRetry]): List of errors to retry.
            At least one needs to be provided.
        max_tries (int): Maximum number of tries, including the first. Defaults to 10.
        min_backoff_secs (float): Minimum amount of backoff time between attempts.
            Defaults to 0.5.
        max_backoff_secs (float): Maximum amount of backoff time between attempts.
            Defaults to 60.

    """
    ...

def get_retry_on_exceptions_with_backoff_decorator(*retry_args: Any, **retry_kwargs: Any) -> Callable:
    """Return a decorator that retries with exponential backoff on provided exceptions."""
    ...

def truncate_text(text: str, max_length: int) -> str:
    """Truncate text to a maximum length."""
    ...

def iter_batch(iterable: Union[Iterable, Generator], size: int) -> Iterable:
    """
    Iterate over an iterable in batches.

    >>> list(iter_batch([1,2,3,4,5], 3))
    [[1, 2, 3], [4, 5]]
    """
    ...

def concat_dirs(dirname: str, basename: str) -> str:
    """
    Append basename to dirname, avoiding backslashes when running on windows.

    os.path.join(dirname, basename) will add a backslash before dirname if
    basename does not end with a slash, so we make sure it does.
    """
    ...

def get_tqdm_iterable(items: Iterable, show_progress: bool, desc: str, total: Optional[int] = ...) -> Iterable:
    """
    Optionally get a tqdm iterable. Ensures tqdm.auto is used.
    """
    ...

def count_tokens(text: str) -> int:
    ...

def get_transformer_tokenizer_fn(model_name: str) -> Callable[[str], List[str]]:
    """
    Args:
        model_name(str): the model name of the tokenizer.
                        For instance, fxmarty/tiny-llama-fast-tokenizer.

    """
    ...

def get_cache_dir() -> str:
    """
    Locate a platform-appropriate cache directory for llama_index,
    and create it if it doesn't yet exist.
    """
    ...

def add_sync_version(func: Any) -> Any:
    """
    Decorator for adding sync version of an async function. The sync version
    is added as a function attribute to the original function, func.

    Args:
        func(Any): the async function for which a sync variant will be built.

    """
    ...

SAMPLE_TEXT = ...
_LLAMA_INDEX_COLORS = ...
_ANSI_COLORS = ...
def get_color_mapping(items: List[str], use_llama_index_colors: bool = ...) -> Dict[str, str]:
    """
    Get a mapping of items to colors.

    Args:
        items (List[str]): List of items to be mapped to colors.
        use_llama_index_colors (bool, optional): Flag to indicate
        whether to use LlamaIndex colors or ANSI colors.
            Defaults to True.

    Returns:
        Dict[str, str]: Mapping of items to colors.

    """
    ...

def print_text(text: str, color: Optional[str] = ..., end: str = ...) -> None:
    """
    Print the text with the specified color.

    Args:
        text (str): Text to be printed.
        color (str, optional): Color to be applied to the text. Supported colors are:
            llama_pink, llama_blue, llama_turquoise, llama_lavender,
            red, green, yellow, blue, magenta, cyan, pink.
        end (str, optional): String appended after the last character of the text.

    Returns:
        None

    """
    ...

def infer_torch_device() -> str:
    """Infer the input to torch.device."""
    ...

def unit_generator(x: Any) -> Generator[Any, None, None]:
    """
    A function that returns a generator of a single element.

    Args:
        x (Any): the element to build yield

    Yields:
        Any: the single element

    """
    ...

async def async_unit_generator(x: Any) -> AsyncGenerator[Any, None]:
    """
    A function that returns a generator of a single element.

    Args:
        x (Any): the element to build yield

    Yields:
        Any: the single element

    """
    ...

def resolve_binary(raw_bytes: Optional[bytes] = ..., path: Optional[Union[str, Path]] = ..., url: Optional[str] = ..., as_base64: bool = ...) -> BytesIO:
    """
    Resolve binary data from various sources into a BytesIO object.

    Args:
        raw_bytes: Raw bytes data
        path: File path to read bytes from
        url: URL to fetch bytes from
        as_base64: Whether to base64 encode the output bytes

    Returns:
        BytesIO object containing the binary data

    Raises:
        ValueError: If no valid source is provided

    """
    ...

