"""
This type stub file was generated by pyright.
"""

from llama_index.core.indices.knowledge_graph.base import KnowledgeGraphIndex
from llama_index.core.indices.knowledge_graph.retrievers import KGTableRetriever, KnowledgeGraphRAGRetriever

"""KG-based data structures."""
__all__ = ["KnowledgeGraphIndex", "KGTableRetriever", "KnowledgeGraphRAGRetriever"]
