"""
This type stub file was generated by pyright.
"""

import deprecated
from enum import Enum
from typing import Any, Callable, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.knowledge_graph.base import KnowledgeGraphIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.storage.storage_context import StorageContext

"""KG Retrievers."""
DQKET = ...
DEFAULT_NODE_SCORE = ...
GLOBAL_EXPLORE_NODE_LIMIT = ...
REL_TEXT_LIMIT = ...
logger = ...
class KGRetrieverMode(str, Enum):
    """
    Query mode enum for Knowledge Graphs.

    Can be passed as the enum struct, or as the underlying string.

    Attributes:
        KEYWORD ("keyword"): Default query mode, using keywords to find triplets.
        EMBEDDING ("embedding"): Embedding mode, using embeddings to find
            similar triplets.
        HYBRID ("hybrid"): Hybrid mode, combining both keywords and embeddings
            to find relevant triplets.

    """
    KEYWORD = ...
    EMBEDDING = ...
    HYBRID = ...


@deprecated.deprecated(version="0.10.53", reason="KGTableRetriever is deprecated, it is recommended to use " "PropertyGraphIndex and associated retrievers instead.")
class KGTableRetriever(BaseRetriever):
    """
    KG Table Retriever.

    Arguments are shared among subclasses.

    Args:
        query_keyword_extract_template (Optional[QueryKGExtractPrompt]): A Query
            KG Extraction
            Prompt (see :ref:`Prompt-Templates`).
        refine_template (Optional[BasePromptTemplate]): A Refinement Prompt
            (see :ref:`Prompt-Templates`).
        text_qa_template (Optional[BasePromptTemplate]): A Question Answering Prompt
            (see :ref:`Prompt-Templates`).
        max_keywords_per_query (int): Maximum number of keywords to extract from query.
        num_chunks_per_query (int): Maximum number of text chunks to query.
        include_text (bool): Use the document text source from each relevant triplet
            during queries.
        retriever_mode (KGRetrieverMode): Specifies whether to use keywords,
            embeddings, or both to find relevant triplets. Should be one of "keyword",
            "embedding", or "hybrid".
        similarity_top_k (int): The number of top embeddings to use
            (if embeddings are used).
        graph_store_query_depth (int): The depth of the graph store query.
        use_global_node_triplets (bool): Whether to get more keywords(entities) from
            text chunks matched by keywords. This helps introduce more global knowledge.
            While it's more expensive, thus to be turned off by default.
        max_knowledge_sequence (int): The maximum number of knowledge sequence to
            include in the response. By default, it's 30.

    """
    def __init__(self, index: KnowledgeGraphIndex, llm: Optional[LLM] = ..., embed_model: Optional[BaseEmbedding] = ..., query_keyword_extract_template: Optional[BasePromptTemplate] = ..., max_keywords_per_query: int = ..., num_chunks_per_query: int = ..., include_text: bool = ..., retriever_mode: Optional[KGRetrieverMode] = ..., similarity_top_k: int = ..., graph_store_query_depth: int = ..., use_global_node_triplets: bool = ..., max_knowledge_sequence: int = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


DEFAULT_SYNONYM_EXPAND_TEMPLATE = ...
DEFAULT_SYNONYM_EXPAND_PROMPT = ...
@deprecated.deprecated(version="0.10.53", reason="KnowledgeGraphRAGRetriever is deprecated, it is recommended to use " "PropertyGraphIndex and associated retrievers instead.")
class KnowledgeGraphRAGRetriever(BaseRetriever):
    """
    Knowledge Graph RAG retriever.

    Retriever that perform SubGraph RAG towards knowledge graph.

    Args:
        storage_context (Optional[StorageContext]): A storage context to use.
        entity_extract_fn (Optional[Callable]): A function to extract entities.
        entity_extract_template Optional[BasePromptTemplate]): A Query Key Entity
            Extraction Prompt (see :ref:`Prompt-Templates`).
        entity_extract_policy (Optional[str]): The entity extraction policy to use.
            default: "union"
            possible values: "union", "intersection"
        synonym_expand_fn (Optional[Callable]): A function to expand synonyms.
        synonym_expand_template (Optional[QueryKeywordExpandPrompt]): A Query Key Entity
            Expansion Prompt (see :ref:`Prompt-Templates`).
        synonym_expand_policy (Optional[str]): The synonym expansion policy to use.
            default: "union"
            possible values: "union", "intersection"
        max_entities (int): The maximum number of entities to extract.
            default: 5
        max_synonyms (int): The maximum number of synonyms to expand per entity.
            default: 5
        retriever_mode (Optional[str]): The retriever mode to use.
            default: "keyword"
            possible values: "keyword", "embedding", "keyword_embedding"
        with_nl2graphquery (bool): Whether to combine NL2GraphQuery in context.
            default: False
        graph_traversal_depth (int): The depth of graph traversal.
            default: 2
        max_knowledge_sequence (int): The maximum number of knowledge sequence to
            include in the response. By default, it's 30.
        verbose (bool): Whether to print out debug info.

    """
    def __init__(self, storage_context: Optional[StorageContext] = ..., llm: Optional[LLM] = ..., entity_extract_fn: Optional[Callable] = ..., entity_extract_template: Optional[BasePromptTemplate] = ..., entity_extract_policy: Optional[str] = ..., synonym_expand_fn: Optional[Callable] = ..., synonym_expand_template: Optional[BasePromptTemplate] = ..., synonym_expand_policy: Optional[str] = ..., max_entities: int = ..., max_synonyms: int = ..., retriever_mode: Optional[str] = ..., with_nl2graphquery: bool = ..., graph_traversal_depth: int = ..., max_knowledge_sequence: int = ..., verbose: bool = ..., callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> None:
        """Initialize the retriever."""
        ...
    


