"""
This type stub file was generated by pyright.
"""

import fsspec
from abc import ABC, abstractmethod
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Generator, Optional, Union
from llama_index.core.readers.base import BaseReader, ResourcesReaderMixin
from llama_index.core.schema import Document

"""Simple reader that reads files of different formats from a directory."""
logger = ...
class FileSystemReaderMixin(ABC):
    @abstractmethod
    def read_file_content(self, input_file: Path, **kwargs: Any) -> bytes:
        """
        Read the bytes content of a file.

        Args:
            input_file (Path): Path to the file.

        Returns:
            bytes: File content.

        """
        ...
    
    async def aread_file_content(self, input_file: Path, **kwargs: Any) -> bytes:
        """
        A thin wrapper around read_file_content.

        Args:
            input_file (Path): Path to the file.

        Returns:
            bytes: File content.

        """
        ...
    


def default_file_metadata_func(file_path: str, fs: fsspec.AbstractFileSystem | None = ...) -> dict:
    """
    Get some handy metadata from filesystem.

    Args:
        file_path: str: file path in str

    """
    ...

class _DefaultFileMetadataFunc:
    """
    Default file metadata function wrapper which stores the fs.
    Allows for pickling of the function.
    """
    def __init__(self, fs: fsspec.AbstractFileSystem | None = ...) -> None:
        ...
    
    def __call__(self, file_path: str) -> dict:
        ...
    


def get_default_fs() -> fsspec.AbstractFileSystem:
    ...

def is_default_fs(fs: fsspec.AbstractFileSystem) -> bool:
    ...

class SimpleDirectoryReader(BaseReader, ResourcesReaderMixin, FileSystemReaderMixin):
    """
    Simple directory reader.

    Load files from file directory.
    Automatically select the best file reader given file extensions.

    Args:
        input_dir (Union[Path, str]): Path to the directory.
        input_files (List): List of file paths to read
            (Optional; overrides input_dir, exclude)
        exclude (List): glob of python file paths to exclude (Optional)
        exclude_hidden (bool): Whether to exclude hidden files (dotfiles).
        exclude_empty (bool): Whether to exclude empty files (Optional).
        encoding (str): Encoding of the files.
            Default is utf-8.
        errors (str): how encoding and decoding errors are to be handled,
              see https://docs.python.org/3/library/functions.html#open
        recursive (bool): Whether to recursively search in subdirectories.
            False by default.
        filename_as_id (bool): Whether to use the filename as the document id.
            False by default.
        required_exts (Optional[List[str]]): List of required extensions.
            Default is None.
        file_extractor (Optional[Dict[str, BaseReader]]): A mapping of file
            extension to a BaseReader class that specifies how to convert that file
            to text. If not specified, use default from DEFAULT_FILE_READER_CLS.
        num_files_limit (Optional[int]): Maximum number of files to read.
            Default is None.
        file_metadata (Optional[Callable[[str], Dict]]): A function that takes
            in a filename and returns a Dict of metadata for the Document.
            Default is None.
        raise_on_error (bool): Whether to raise an error if a file cannot be read.
        fs (Optional[fsspec.AbstractFileSystem]): File system to use. Defaults
        to using the local file system. Can be changed to use any remote file system
        exposed via the fsspec interface.

    """
    supported_suffix_fn: Callable = ...
    def __init__(self, input_dir: Optional[Union[Path, str]] = ..., input_files: Optional[list] = ..., exclude: Optional[list] = ..., exclude_hidden: bool = ..., exclude_empty: bool = ..., errors: str = ..., recursive: bool = ..., encoding: str = ..., filename_as_id: bool = ..., required_exts: Optional[list[str]] = ..., file_extractor: Optional[dict[str, BaseReader]] = ..., num_files_limit: Optional[int] = ..., file_metadata: Optional[Callable[[str], dict]] = ..., raise_on_error: bool = ..., fs: fsspec.AbstractFileSystem | None = ...) -> None:
        """Initialize with parameters."""
        ...
    
    def is_hidden(self, path: Path | PurePosixPath) -> bool:
        ...
    
    def is_empty_file(self, path: Path | PurePosixPath) -> bool:
        ...
    
    def list_resources(self, *args: Any, **kwargs: Any) -> list[str]:
        """List files in the given filesystem."""
        ...
    
    def get_resource_info(self, resource_id: str, *args: Any, **kwargs: Any) -> dict:
        ...
    
    def load_resource(self, resource_id: str, *args: Any, **kwargs: Any) -> list[Document]:
        ...
    
    async def aload_resource(self, resource_id: str, *args: Any, **kwargs: Any) -> list[Document]:
        ...
    
    def read_file_content(self, input_file: Path, **kwargs: Any) -> bytes:
        """Read file content."""
        ...
    
    @staticmethod
    def load_file(input_file: Path | PurePosixPath, file_metadata: Callable[[str], dict], file_extractor: dict[str, BaseReader], filename_as_id: bool = ..., encoding: str = ..., errors: str = ..., raise_on_error: bool = ..., fs: fsspec.AbstractFileSystem | None = ...) -> list[Document]:
        """
        Static method for loading file.

        NOTE: necessarily as a static method for parallel processing.

        Args:
            input_file (Path): File path to read
            file_metadata ([Callable[[str], Dict]]): A function that takes
                in a filename and returns a Dict of metadata for the Document.
            file_extractor (Dict[str, BaseReader]): A mapping of file
                extension to a BaseReader class that specifies how to convert that file
                to text.
            filename_as_id (bool): Whether to use the filename as the document id.
            encoding (str): Encoding of the files.
                Default is utf-8.
            errors (str): how encoding and decoding errors are to be handled,
                see https://docs.python.org/3/library/functions.html#open
            raise_on_error (bool): Whether to raise an error if a file cannot be read.
            fs (Optional[fsspec.AbstractFileSystem]): File system to use. Defaults
                to using the local file system. Can be changed to use any remote file system

        Returns:
            List[Document]: loaded documents

        """
        ...
    
    @staticmethod
    async def aload_file(input_file: Path | PurePosixPath, file_metadata: Callable[[str], dict], file_extractor: dict[str, BaseReader], filename_as_id: bool = ..., encoding: str = ..., errors: str = ..., raise_on_error: bool = ..., fs: fsspec.AbstractFileSystem | None = ...) -> list[Document]:
        """Load file asynchronously."""
        ...
    
    def load_data(self, show_progress: bool = ..., num_workers: int | None = ..., fs: fsspec.AbstractFileSystem | None = ...) -> list[Document]:
        """
        Load data from the input directory.

        Args:
            show_progress (bool): Whether to show tqdm progress bars. Defaults to False.
            num_workers  (Optional[int]): Number of workers to parallelize data-loading over.
            fs (Optional[fsspec.AbstractFileSystem]): File system to use. If fs was specified
                in the constructor, it will override the fs parameter here.

        Returns:
            List[Document]: A list of documents.

        """
        ...
    
    async def aload_data(self, show_progress: bool = ..., num_workers: int | None = ..., fs: fsspec.AbstractFileSystem | None = ...) -> list[Document]:
        """
        Load data from the input directory.

        Args:
            show_progress (bool): Whether to show tqdm progress bars. Defaults to False.
            num_workers  (Optional[int]): Number of workers to parallelize data-loading over.
            fs (Optional[fsspec.AbstractFileSystem]): File system to use. If fs was specified
                in the constructor, it will override the fs parameter here.

        Returns:
            List[Document]: A list of documents.

        """
        ...
    
    def iter_data(self, show_progress: bool = ...) -> Generator[list[Document], Any, Any]:
        """
        Load data iteratively from the input directory.

        Args:
            show_progress (bool): Whether to show tqdm progress bars. Defaults to False.

        Returns:
            Generator[List[Document]]: A list of documents.

        """
        ...
    


