"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from llama_cloud.client import AsyncLlamaCloud, LlamaCloud

if TYPE_CHECKING:
    ...
def get_client(api_key: Optional[str] = ..., base_url: Optional[str] = ..., app_url: Optional[str] = ..., timeout: int = ..., httpx_client: Optional[httpx.Client] = ...) -> LlamaCloud:
    """Get the sync platform API client."""
    ...

def get_aclient(api_key: Optional[str] = ..., base_url: Optional[str] = ..., app_url: Optional[str] = ..., timeout: int = ..., httpx_client: Optional[httpx.AsyncClient] = ...) -> AsyncLlamaCloud:
    """Get the async platform API client."""
    ...

