"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, List, Optional, Sequence
from fsspec import AbstractFileSystem
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.ingestion.cache import IngestionCache
from llama_index.core.readers.base import ReaderConfig
from llama_index.core.schema import BaseNode, Document, TransformComponent
from llama_index.core.storage.docstore import BaseDocumentStore
from llama_index.core.vector_stores.types import BasePydanticVectorStore

dispatcher = ...
def remove_unstable_values(s: str) -> str:
    """
    Remove unstable key/value pairs.

    Examples include:
    - <__main__.Test object at 0x7fb9f3793f50>
    - <function test_fn at 0x7fb9f37a8900>
    """
    ...

def get_transformation_hash(nodes: Sequence[BaseNode], transformation: TransformComponent) -> str:
    """Get the hash of a transformation."""
    ...

def run_transformations(nodes: Sequence[BaseNode], transformations: Sequence[TransformComponent], in_place: bool = ..., cache: Optional[IngestionCache] = ..., cache_collection: Optional[str] = ..., **kwargs: Any) -> Sequence[BaseNode]:
    """
    Run a series of transformations on a set of nodes.

    Args:
        nodes: The nodes to transform.
        transformations: The transformations to apply to the nodes.

    Returns:
        The transformed nodes.

    """
    ...

async def arun_transformations(nodes: Sequence[BaseNode], transformations: Sequence[TransformComponent], in_place: bool = ..., cache: Optional[IngestionCache] = ..., cache_collection: Optional[str] = ..., **kwargs: Any) -> Sequence[BaseNode]:
    """
    Run a series of transformations on a set of nodes.

    Args:
        nodes: The nodes to transform.
        transformations: The transformations to apply to the nodes.

    Returns:
        The transformed nodes.

    """
    ...

def arun_transformations_wrapper(nodes: Sequence[BaseNode], transformations: Sequence[TransformComponent], in_place: bool = ..., cache: Optional[IngestionCache] = ..., cache_collection: Optional[str] = ..., **kwargs: Any) -> Sequence[BaseNode]:
    """
    Wrapper for async run_transformation. To be used in loop.run_in_executor
    within a ProcessPoolExecutor.
    """
    ...

class DocstoreStrategy(str, Enum):
    """
    Document de-duplication de-deduplication strategies work by comparing the hashes or ids stored in the document store.
       They require a document store to be set which must be persisted across pipeline runs.

    Attributes:
        UPSERTS:
            ('upserts') Use upserts to handle duplicates. Checks if the a document is already in the doc store based on its id. If it is not, or if the hash of the document is updated, it will update the document in the doc store and run the transformations.
        DUPLICATES_ONLY:
            ('duplicates_only') Only handle duplicates. Checks if the hash of a document is already in the doc store. Only then it will add the document to the doc store and run the transformations
        UPSERTS_AND_DELETE:
            ('upserts_and_delete') Use upserts and delete to handle duplicates. Like the upsert strategy but it will also delete non-existing documents from the doc store

    """
    UPSERTS = ...
    DUPLICATES_ONLY = ...
    UPSERTS_AND_DELETE = ...


class IngestionPipeline(BaseModel):
    """
    An ingestion pipeline that can be applied to data.

    Args:
        name (str, optional):
            Unique name of the ingestion pipeline. Defaults to DEFAULT_PIPELINE_NAME.
        project_name (str, optional):
            Unique name of the project. Defaults to DEFAULT_PROJECT_NAME.
        transformations (List[TransformComponent], optional):
            Transformations to apply to the data. Defaults to None.
        documents (Optional[Sequence[Document]], optional):
            Documents to ingest. Defaults to None.
        readers (Optional[List[ReaderConfig]], optional):
            Reader to use to read the data. Defaults to None.
        vector_store (Optional[BasePydanticVectorStore], optional):
            Vector store to use to store the data. Defaults to None.
        cache (Optional[IngestionCache], optional):
            Cache to use to store the data. Defaults to None.
        docstore (Optional[BaseDocumentStore], optional):
            Document store to use for de-duping with a vector store. Defaults to None.
        docstore_strategy (DocstoreStrategy, optional):
            Document de-dup strategy. Defaults to DocstoreStrategy.UPSERTS.
        disable_cache (bool, optional):
            Disable the cache. Defaults to False.
        base_url (str, optional):
            Base URL for the LlamaCloud API. Defaults to DEFAULT_BASE_URL.
        app_url (str, optional):
            Base URL for the LlamaCloud app. Defaults to DEFAULT_APP_URL.
        api_key (Optional[str], optional):
            LlamaCloud API key. Defaults to None.

    Examples:
        ```python
        from llama_index.core.ingestion import IngestionPipeline
        from llama_index.core.node_parser import SentenceSplitter
        from llama_index.embeddings.openai import OpenAIEmbedding

        pipeline = IngestionPipeline(
            transformations=[
                SentenceSplitter(chunk_size=512, chunk_overlap=20),
                OpenAIEmbedding(),
            ],
        )

        nodes = pipeline.run(documents=documents)
        ```

    """
    model_config = ...
    name: str = ...
    project_name: str = ...
    transformations: List[TransformComponent] = ...
    documents: Optional[Sequence[Document]] = ...
    readers: Optional[List[ReaderConfig]] = ...
    vector_store: Optional[BasePydanticVectorStore] = ...
    cache: IngestionCache = ...
    docstore: Optional[BaseDocumentStore] = ...
    docstore_strategy: DocstoreStrategy = ...
    disable_cache: bool = ...
    def __init__(self, name: str = ..., project_name: str = ..., transformations: Optional[List[TransformComponent]] = ..., readers: Optional[List[ReaderConfig]] = ..., documents: Optional[Sequence[Document]] = ..., vector_store: Optional[BasePydanticVectorStore] = ..., cache: Optional[IngestionCache] = ..., docstore: Optional[BaseDocumentStore] = ..., docstore_strategy: DocstoreStrategy = ..., disable_cache: bool = ...) -> None:
        ...
    
    def persist(self, persist_dir: str = ..., fs: Optional[AbstractFileSystem] = ..., cache_name: str = ..., docstore_name: str = ...) -> None:
        """Persist the pipeline to disk."""
        ...
    
    def load(self, persist_dir: str = ..., fs: Optional[AbstractFileSystem] = ..., cache_name: str = ..., docstore_name: str = ...) -> None:
        """Load the pipeline from disk."""
        ...
    
    @dispatcher.span
    def run(self, show_progress: bool = ..., documents: Optional[List[Document]] = ..., nodes: Optional[Sequence[BaseNode]] = ..., cache_collection: Optional[str] = ..., in_place: bool = ..., store_doc_text: bool = ..., num_workers: Optional[int] = ..., **kwargs: Any) -> Sequence[BaseNode]:
        """
        Run a series of transformations on a set of nodes.

        If a vector store is provided, nodes with embeddings will be added to the vector store.

        If a vector store + docstore are provided, the docstore will be used to de-duplicate documents.

        Args:
            show_progress (bool, optional): Shows execution progress bar(s). Defaults to False.
            documents (Optional[List[Document]], optional): Set of documents to be transformed. Defaults to None.
            nodes (Optional[Sequence[BaseNode]], optional): Set of nodes to be transformed. Defaults to None.
            cache_collection (Optional[str], optional): Cache for transformations. Defaults to None.
            in_place (bool, optional): Whether transformations creates a new list for transformed nodes or modifies the
                array passed to `run_transformations`. Defaults to True.
            num_workers (Optional[int], optional): The number of parallel processes to use.
                If set to None, then sequential compute is used. Defaults to None.

        Returns:
            Sequence[BaseNode]: The set of transformed Nodes/Documents

        """
        ...
    
    @dispatcher.span
    async def arun(self, show_progress: bool = ..., documents: Optional[List[Document]] = ..., nodes: Optional[Sequence[BaseNode]] = ..., cache_collection: Optional[str] = ..., in_place: bool = ..., store_doc_text: bool = ..., num_workers: Optional[int] = ..., **kwargs: Any) -> Sequence[BaseNode]:
        """
        Run a series of transformations on a set of nodes.

        If a vector store is provided, nodes with embeddings will be added to the vector store.

        If a vector store + docstore are provided, the docstore will be used to de-duplicate documents.

        Args:
            show_progress (bool, optional): Shows execution progress bar(s). Defaults to False.
            documents (Optional[List[Document]], optional): Set of documents to be transformed. Defaults to None.
            nodes (Optional[Sequence[BaseNode]], optional): Set of nodes to be transformed. Defaults to None.
            cache_collection (Optional[str], optional): Cache for transformations. Defaults to None.
            in_place (bool, optional): Whether transformations creates a new list for transformed nodes or modifies the
                array passed to `run_transformations`. Defaults to True.
            num_workers (Optional[int], optional): The number of parallel processes to use.
                If set to None, then sequential compute is used. Defaults to None.

        Returns:
            Sequence[BaseNode]: The set of transformed Nodes/Documents

        """
        ...
    


