"""
This type stub file was generated by pyright.
"""

from pathlib import Path, PurePosixPath
from typing import Any, Dict, List, Optional, Union
from tenacity import retry, stop_after_attempt
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Docs parser.

Contains parsers for docx, pdf files.

"""
logger = ...
RETRY_TIMES = ...
class PDFReader(BaseReader):
    """PDF parser."""
    def __init__(self, return_full_document: Optional[bool] = ...) -> None:
        """
        Initialize PDFReader.
        """
        ...
    
    @retry(stop=stop_after_attempt(RETRY_TIMES))
    def load_data(self, file: Union[Path, PurePosixPath], extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


class DocxReader(BaseReader):
    """Docx parser."""
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


class HWPReader(BaseReader):
    """Hwp Parser."""
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """
        Load data and extract table from Hwp file.

        Args:
            file (Path): Path for the Hwp file.

        Returns:
            List[Document]

        """
        ...
    
    def is_valid(self, dirs: List[str]) -> bool:
        ...
    
    def get_body_sections(self, dirs: List[str]) -> List[str]:
        ...
    
    def get_text(self) -> str:
        ...
    
    def is_compressed(self, load_file: Any) -> bool:
        ...
    
    def get_text_from_section(self, load_file: Any, section: str) -> str:
        ...
    


