"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Generic, Optional, Sequence, TypeVar
from llama_index.core.data_structs.table import BaseStructTable
from llama_index.core.indices.base import BaseIndex
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode
from llama_index.core.storage.docstore.types import RefDocInfo

"""Struct store."""
BST = TypeVar("BST", bound=BaseStructTable)
def default_output_parser(output: str) -> Optional[Dict[str, Any]]:
    """
    Parse output of schema extraction.

    Attempt to parse the following format from the default prompt:
    field1: <value>, field2: <value>, ...

    """
    ...

OUTPUT_PARSER_TYPE = Callable[[str], Optional[Dict[str, Any]]]
class BaseStructStoreIndex(BaseIndex[BST], Generic[BST]):
    """Base Struct Store Index."""
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., index_struct: Optional[BST] = ..., schema_extract_prompt: Optional[BasePromptTemplate] = ..., output_parser: Optional[OUTPUT_PARSER_TYPE] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


