"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Type
from llama_index.core.indices.base import BaseIndex
from llama_index.core.indices.common.struct_store.schema import SQLContextContainer
from llama_index.core.schema import BaseNode, QueryType
from llama_index.core.utilities.sql_wrapper import SQLDatabase

"""SQL Container builder."""
DEFAULT_CONTEXT_QUERY_TMPL = ...
class SQLContextContainerBuilder:
    """
    SQLContextContainerBuilder.

    Build a SQLContextContainer that can be passed to the SQL index
    during index construction or during query-time.

    NOTE: if context_str is specified, that will be used as context
    instead of context_dict

    Args:
        sql_database (SQLDatabase): SQL database
        context_dict (Optional[Dict[str, str]]): context dict

    """
    def __init__(self, sql_database: SQLDatabase, context_dict: Optional[Dict[str, str]] = ..., context_str: Optional[str] = ...) -> None:
        """Initialize params."""
        ...
    
    @classmethod
    def from_documents(cls, documents_dict: Dict[str, List[BaseNode]], sql_database: SQLDatabase, **context_builder_kwargs: Any) -> SQLContextContainerBuilder:
        """Build context from documents."""
        ...
    
    def derive_index_from_context(self, index_cls: Type[BaseIndex], ignore_db_schema: bool = ..., **index_kwargs: Any) -> BaseIndex:
        """Derive index from context."""
        ...
    
    def query_index_for_context(self, index: BaseIndex, query_str: QueryType, query_tmpl: Optional[str] = ..., store_context_str: bool = ..., **index_kwargs: Any) -> str:
        """
        Query index for context.

        A simple wrapper around the index.query call which
        injects a query template to specifically fetch table information,
        and can store a context_str.

        Args:
            index (BaseIndex): index data structure
            query_str (QueryType): query string
            query_tmpl (Optional[str]): query template
            store_context_str (bool): store context_str

        """
        ...
    
    def build_context_container(self, ignore_db_schema: bool = ...) -> SQLContextContainer:
        """Build index structure."""
        ...
    


