"""
This type stub file was generated by pyright.
"""

from typing import Any

"""
Pandas csv structured store.

DEPRECATED: Please use :class:`PandasQueryEngine` in `llama-index-experimental` instead.
"""
class PandasIndex:
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


GPTPandasIndex = PandasIndex
