"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Optional, Sequence, Union
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.data_structs.table import SQLStructTable
from llama_index.core.indices.common.struct_store.schema import SQLContextContainer
from llama_index.core.indices.struct_store.base import BaseStructStoreIndex
from llama_index.core.llms.utils import LLMType
from llama_index.core.schema import BaseNode
from llama_index.core.utilities.sql_wrapper import SQLDatabase
from sqlalchemy import Table

"""SQL Structured Store."""
class SQLQueryMode(str, Enum):
    SQL = ...
    NL = ...


class SQLStructStoreIndex(BaseStructStoreIndex[SQLStructTable]):
    """
    SQL Struct Store Index.

    The SQLStructStoreIndex is an index that uses a SQL database
    under the hood. During index construction, the data can be inferred
    from unstructured documents given a schema extract prompt,
    or it can be pre-loaded in the database.

    During query time, the user can either specify a raw SQL query
    or a natural language query to retrieve their data.

    NOTE: this is deprecated.

    Args:
        documents (Optional[Sequence[DOCUMENTS_INPUT]]): Documents to index.
            NOTE: in the SQL index, this is an optional field.
        sql_database (Optional[SQLDatabase]): SQL database to use,
            including table names to specify.
            See :ref:`Ref-Struct-Store` for more details.
        table_name (Optional[str]): Name of the table to use
            for extracting data.
            Either table_name or table must be specified.
        table (Optional[Table]): SQLAlchemy Table object to use.
            Specifying the Table object explicitly, instead of
            the table name, allows you to pass in a view.
            Either table_name or table must be specified.
        sql_context_container (Optional[SQLContextContainer]): SQL context container.
            an be generated from a SQLContextContainerBuilder.
            See :ref:`Ref-Struct-Store` for more details.

    """
    index_struct_cls = ...
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., index_struct: Optional[SQLStructTable] = ..., sql_database: Optional[SQLDatabase] = ..., table_name: Optional[str] = ..., table: Optional[Table] = ..., ref_doc_id_column: Optional[str] = ..., sql_context_container: Optional[SQLContextContainer] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def ref_doc_id_column(self) -> Optional[str]:
        ...
    
    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        ...
    
    def as_query_engine(self, llm: Optional[LLMType] = ..., query_mode: Union[str, SQLQueryMode] = ..., **kwargs: Any) -> BaseQueryEngine:
        ...
    


GPTSQLStructStoreIndex = SQLStructStoreIndex
