"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, List, Optional, Union
from llama_index.core.indices.base import BaseRetriever
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.callbacks import CallbackManager
from llama_index.core.indices.struct_store.container_builder import SQLContextContainerBuilder
from llama_index.core.indices.struct_store.sql import SQLStructStoreIndex
from llama_index.core.indices.struct_store.sql_retriever import NLSQLRetriever
from llama_index.core.llms.llm import LLM
from llama_index.core.objects.base import ObjectRetriever
from llama_index.core.objects.table_node_mapping import SQLTableSchema
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.utilities.sql_wrapper import SQLDatabase
from sqlalchemy import Table

"""Default query for SQLStructStoreIndex."""
logger = ...
DEFAULT_RESPONSE_SYNTHESIS_PROMPT_TMPL = ...
DEFAULT_RESPONSE_SYNTHESIS_PROMPT = ...
DEFAULT_RESPONSE_SYNTHESIS_PROMPT_TMPL_V2 = ...
DEFAULT_RESPONSE_SYNTHESIS_PROMPT_V2 = ...
class SQLStructStoreQueryEngine(BaseQueryEngine):
    """
    GPT SQL query engine over a structured database.

    NOTE: deprecated in favor of SQLTableRetriever, kept for backward compatibility.

    Runs raw SQL over a SQLStructStoreIndex. No LLM calls are made here.

    NOTE: this query cannot work with composed indices - if the index
    contains subindices, those subindices will not be queried.

    NOTE: Any Text-to-SQL application should be aware that executing
    arbitrary SQL queries can be a security risk. It is recommended to
    take precautions as needed, such as using restricted roles, read-only
    databases, sandboxing, etc.
    """
    def __init__(self, index: SQLStructStoreIndex, sql_context_container: Optional[SQLContextContainerBuilder] = ..., sql_only: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


class NLStructStoreQueryEngine(BaseQueryEngine):
    """
    GPT natural language query engine over a structured database.

    NOTE: deprecated in favor of SQLTableRetriever, kept for backward compatibility.

    Given a natural language query, we will extract the query to SQL.
    Runs raw SQL over a SQLStructStoreIndex. No LLM calls are made during
    the SQL execution.

    NOTE: this query cannot work with composed indices - if the index
    contains subindices, those subindices will not be queried.

    NOTE: Any Text-to-SQL application should be aware that executing
    arbitrary SQL queries can be a security risk. It is recommended to
    take precautions as needed, such as using restricted roles, read-only
    databases, sandboxing, etc.

    Args:
        index (SQLStructStoreIndex): A SQL Struct Store Index
        text_to_sql_prompt (Optional[BasePromptTemplate]): A Text to SQL
            BasePromptTemplate to use for the query.
            Defaults to DEFAULT_TEXT_TO_SQL_PROMPT.
        context_query_kwargs (Optional[dict]): Keyword arguments for the
            context query. Defaults to {}.
        synthesize_response (bool): Whether to synthesize a response from the
            query results. Defaults to True.
        sql_only (bool) : Whether to get only sql and not the sql query result.
            Default to False.
        response_synthesis_prompt (Optional[BasePromptTemplate]): A
            Response Synthesis BasePromptTemplate to use for the query. Defaults to
            DEFAULT_RESPONSE_SYNTHESIS_PROMPT.

    """
    def __init__(self, index: SQLStructStoreIndex, text_to_sql_prompt: Optional[BasePromptTemplate] = ..., context_query_kwargs: Optional[dict] = ..., synthesize_response: bool = ..., response_synthesis_prompt: Optional[BasePromptTemplate] = ..., sql_only: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


class BaseSQLTableQueryEngine(BaseQueryEngine):
    """
    Base SQL Table query engine.

    NOTE: Any Text-to-SQL application should be aware that executing
    arbitrary SQL queries can be a security risk. It is recommended to
    take precautions as needed, such as using restricted roles, read-only
    databases, sandboxing, etc.
    """
    def __init__(self, llm: Optional[LLM] = ..., synthesize_response: bool = ..., markdown_response: bool = ..., response_synthesis_prompt: Optional[BasePromptTemplate] = ..., callback_manager: Optional[CallbackManager] = ..., refine_synthesis_prompt: Optional[BasePromptTemplate] = ..., verbose: bool = ..., streaming: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    @abstractmethod
    def sql_retriever(self) -> NLSQLRetriever:
        """Get SQL retriever."""
        ...
    


class NLSQLTableQueryEngine(BaseSQLTableQueryEngine):
    """
    Natural language SQL Table query engine.

    Read NLStructStoreQueryEngine's docstring for more info on NL SQL.

    NOTE: Any Text-to-SQL application should be aware that executing
    arbitrary SQL queries can be a security risk. It is recommended to
    take precautions as needed, such as using restricted roles, read-only
    databases, sandboxing, etc.
    """
    def __init__(self, sql_database: SQLDatabase, llm: Optional[LLM] = ..., text_to_sql_prompt: Optional[BasePromptTemplate] = ..., context_query_kwargs: Optional[dict] = ..., synthesize_response: bool = ..., markdown_response: bool = ..., response_synthesis_prompt: Optional[BasePromptTemplate] = ..., refine_synthesis_prompt: Optional[BasePromptTemplate] = ..., tables: Optional[Union[List[str], List[Table]]] = ..., table_retriever: Optional[ObjectRetriever[SQLTableSchema]] = ..., rows_retrievers: Optional[dict[str, BaseRetriever]] = ..., cols_retrievers: Optional[dict[str, dict[str, BaseRetriever]]] = ..., context_str_prefix: Optional[str] = ..., embed_model: Optional[BaseEmbedding] = ..., sql_only: bool = ..., callback_manager: Optional[CallbackManager] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def sql_retriever(self) -> NLSQLRetriever:
        """Get SQL retriever."""
        ...
    


class PGVectorSQLQueryEngine(BaseSQLTableQueryEngine):
    """
    PGvector SQL query engine.

    A modified version of the normal text-to-SQL query engine because
    we can infer embedding vectors in the sql query.

    NOTE: this is a beta feature

    NOTE: Any Text-to-SQL application should be aware that executing
    arbitrary SQL queries can be a security risk. It is recommended to
    take precautions as needed, such as using restricted roles, read-only
    databases, sandboxing, etc.

    """
    def __init__(self, sql_database: SQLDatabase, llm: Optional[LLM] = ..., text_to_sql_prompt: Optional[BasePromptTemplate] = ..., context_query_kwargs: Optional[dict] = ..., synthesize_response: bool = ..., response_synthesis_prompt: Optional[BasePromptTemplate] = ..., refine_synthesis_prompt: Optional[BasePromptTemplate] = ..., tables: Optional[Union[List[str], List[Table]]] = ..., context_str_prefix: Optional[str] = ..., sql_only: bool = ..., callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def sql_retriever(self) -> NLSQLRetriever:
        """Get SQL retriever."""
        ...
    


class SQLTableRetrieverQueryEngine(BaseSQLTableQueryEngine):
    """SQL Table retriever query engine."""
    def __init__(self, sql_database: SQLDatabase, table_retriever: ObjectRetriever[SQLTableSchema], rows_retrievers: Optional[dict[str, BaseRetriever]] = ..., cols_retrievers: Optional[dict[str, dict[str, BaseRetriever]]] = ..., llm: Optional[LLM] = ..., text_to_sql_prompt: Optional[BasePromptTemplate] = ..., context_query_kwargs: Optional[dict] = ..., synthesize_response: bool = ..., response_synthesis_prompt: Optional[BasePromptTemplate] = ..., refine_synthesis_prompt: Optional[BasePromptTemplate] = ..., context_str_prefix: Optional[str] = ..., sql_only: bool = ..., callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def sql_retriever(self) -> NLSQLRetriever:
        """Get SQL retriever."""
        ...
    


GPTNLStructStoreQueryEngine = NLStructStoreQueryEngine
GPTSQLStructStoreQueryEngine = SQLStructStoreQueryEngine
