"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.indices.property_graph.sub_retrievers.base import BasePGRetriever

class PGRetriever(BaseRetriever):
    """
    A retriever that uses multiple sub-retrievers to retrieve nodes from a property graph.

    Args:
        sub_retrievers (List[BasePGRetriever]):
            The sub-retrievers to use.
        num_workers (int, optional):
            The number of workers to use for async retrieval. Defaults to 4.
        use_async (bool, optional):
            Whether to use async retrieval. Defaults to True.
        show_progress (bool, optional):
            Whether to show progress bars. Defaults to False.

    """
    def __init__(self, sub_retrievers: List[BasePGRetriever], num_workers: int = ..., use_async: bool = ..., show_progress: bool = ..., **kwargs: Any) -> None:
        ...
    


