"""
This type stub file was generated by pyright.
"""

import os
import fsspec
from dataclasses import dataclass
from typing import Dict, Optional, Union
from llama_index.core.graph_stores.types import GraphStore, PropertyGraphStore
from llama_index.core.storage.docstore.types import BaseDocumentStore
from llama_index.core.storage.index_store.types import BaseIndexStore
from llama_index.core.vector_stores.types import BasePydanticVectorStore
from llama_index.core.bridge.pydantic import SerializeAsAny

DEFAULT_PERSIST_DIR = ...
IMAGE_STORE_FNAME = ...
IMAGE_VECTOR_STORE_NAMESPACE = ...
@dataclass
class StorageContext:
    """
    Storage context.

    The storage context container is a utility container for storing nodes,
    indices, and vectors. It contains the following:
    - docstore: BaseDocumentStore
    - index_store: BaseIndexStore
    - vector_store: BasePydanticVectorStore
    - graph_store: GraphStore
    - property_graph_store: PropertyGraphStore (lazily initialized)

    """
    docstore: BaseDocumentStore
    index_store: BaseIndexStore
    vector_stores: Dict[str, SerializeAsAny[BasePydanticVectorStore]]
    graph_store: GraphStore
    property_graph_store: Optional[PropertyGraphStore] = ...
    @classmethod
    def from_defaults(cls, docstore: Optional[BaseDocumentStore] = ..., index_store: Optional[BaseIndexStore] = ..., vector_store: Optional[BasePydanticVectorStore] = ..., image_store: Optional[BasePydanticVectorStore] = ..., vector_stores: Optional[Dict[str, BasePydanticVectorStore]] = ..., graph_store: Optional[GraphStore] = ..., property_graph_store: Optional[PropertyGraphStore] = ..., persist_dir: Optional[str] = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> StorageContext:
        """
        Create a StorageContext from defaults.

        Args:
            docstore (Optional[BaseDocumentStore]): document store
            index_store (Optional[BaseIndexStore]): index store
            vector_store (Optional[BasePydanticVectorStore]): vector store
            graph_store (Optional[GraphStore]): graph store
            image_store (Optional[BasePydanticVectorStore]): image store

        """
        ...
    
    def persist(self, persist_dir: Union[str, os.PathLike] = ..., docstore_fname: str = ..., index_store_fname: str = ..., vector_store_fname: str = ..., image_store_fname: str = ..., graph_store_fname: str = ..., pg_graph_store_fname: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """
        Persist the storage context.

        Args:
            persist_dir (str): directory to persist the storage context

        """
        ...
    
    def to_dict(self) -> dict:
        ...
    
    @classmethod
    def from_dict(cls, save_dict: dict) -> StorageContext:
        """Create a StorageContext from dict."""
        ...
    
    @property
    def vector_store(self) -> BasePydanticVectorStore:
        """Backwrds compatibility for vector_store property."""
        ...
    
    def add_vector_store(self, vector_store: BasePydanticVectorStore, namespace: str) -> None:
        """Add a vector store to the storage context."""
        ...
    


