services:

  # --- Custom Services --- 
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      # Service
      - APP_VERSION=${APP_VERSION}

      # Vector Store
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

      # LlamaIndex
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_PROVIDER_API_KEY=${LLM_PROVIDER_API_KEY}
      - LLM_PROVIDER_BASE_URL=${LLM_PROVIDER_BASE_URL}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_EMBEDDING_MODEL=${LLM_EMBEDDING_MODEL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}

      # S3
      - MINIO_URL=${MINIO_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}

      # Auth
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - SECRET_KEY=${AUTH_SECRET_KEY}

      # Database
      - DATABASE_URL=${DATABASE_URL}

      # Hugging Face
      - HF_HUB_DOWNLOAD_TIMEOUT=120
      - HF_HUB_DISABLE_TELEMETRY=1

    volumes:
      - ./backend:/app
      - ./data:/data

      # Hugging Face (Model Caching)
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - qdrant
      - minio
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - rag-network
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - VITE_DEV_API_URL=http://localhost:8001/api/v1
    depends_on:
      - backend
    restart: unless-stopped
  
  # --- External Services ---
  qdrant:
    image: qdrant/qdrant:v1.16
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: [ "server", "--console-address", ":9001", "/data" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=buck1
    networks:
      - rag-network
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

    # --- LOGGING SERVICES ---
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rag-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      # Magia dzieje się tutaj: Promtail czyta pliki logów samego Dockera z hosta!
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - rag-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks:
      - rag-network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_storage:
  ollama_storage:
  minio_data:
    driver: local
  hf_cache:
