"""
This type stub file was generated by pyright.
"""

from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

"""Download."""
LLAMA_HUB_CONTENTS_URL = ...
LLAMA_HUB_PATH = ...
LLAMA_HUB_URL = ...
PATH_TYPE = Union[str, Path]
logger = ...
LLAMAHUB_ANALYTICS_PROXY_SERVER = ...
class MODULE_TYPE(str, Enum):
    LOADER = ...
    TOOL = ...
    LLAMAPACK = ...
    DATASETS = ...


def get_module_info(local_dir_path: PATH_TYPE, remote_dir_path: PATH_TYPE, module_class: str, refresh_cache: bool = ..., library_path: str = ..., disable_library_cache: bool = ...) -> Dict:
    """Get module info."""
    ...

def download_module_and_reqs(local_dir_path: PATH_TYPE, remote_dir_path: PATH_TYPE, module_id: str, extra_files: List[str], refresh_cache: bool = ..., use_gpt_index_import: bool = ..., base_file_name: str = ..., override_path: bool = ...) -> None:
    """Load module."""
    ...

def download_llama_module(module_class: str, llama_hub_url: str = ..., refresh_cache: bool = ..., custom_dir: Optional[str] = ..., custom_path: Optional[str] = ..., library_path: str = ..., base_file_name: str = ..., use_gpt_index_import: bool = ..., disable_library_cache: bool = ..., override_path: bool = ..., skip_load: bool = ...) -> Any:
    """
    Download a module from LlamaHub.

    Can be a loader, tool, pack, or more.

    Args:
        loader_class: The name of the llama module class you want to download,
            such as `GmailOpenAIAgentPack`.
        refresh_cache: If true, the local cache will be skipped and the
            loader will be fetched directly from the remote repo.
        custom_dir: Custom dir name to download loader into (under parent folder).
        custom_path: Custom dirpath to download loader into.
        library_path: File name of the library file.
        use_gpt_index_import: If true, the loader files will use
            llama_index as the base dependency. By default (False),
            the loader files use llama_index as the base dependency.
            NOTE: this is a temporary workaround while we fully migrate all usages
            to llama_index.core.
        is_dataset: whether or not downloading a LlamaDataset

    Returns:
        A Loader, A Pack, An Agent, or A Dataset

    """
    ...

def track_download(module_class: str, module_type: str) -> None:
    """
    Tracks number of downloads via Llamahub proxy.

    Args:
        module_class: The name of the llama module being downloaded, e.g.,`GmailOpenAIAgentPack`.
        module_type: Can be "loader", "tool", "llamapack", or "datasets"

    """
    ...

