"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import List, Optional, Tuple

def get_file_content(url: str, path: str) -> Tuple[str, int]:
    """Get the content of a file from the GitHub REST API."""
    ...

def get_file_content_bytes(url: str, path: str) -> Tuple[bytes, int]:
    """Get the content of a file from the GitHub REST API."""
    ...

def get_exports(raw_content: str) -> List:
    """
    Read content of a Python file and returns a list of exported class names.

    For example:
    ```python
    from .a import A
    from .b import B

    __all__ = ["A", "B"]
    ```
    will return `["A", "B"]`.

    Args:
        - raw_content: The content of a Python file as a string.

    Returns:
        A list of exported class names.

    """
    ...

def rewrite_exports(exports: List[str], dirpath: str) -> None:
    """
    Write the `__all__` variable to the `__init__.py` file in the modules dir.

    Removes the line that contains `__all__` and appends a new line with the updated
    `__all__` variable.

    Args:
        - exports: A list of exported class names.

    """
    ...

def initialize_directory(custom_path: Optional[str] = ..., custom_dir: Optional[str] = ...) -> Path:
    """Initialize directory."""
    ...

def get_source_files_list(source_tree_url: str, path: str) -> List[str]:
    """Get the list of source files to download."""
    ...

def recursive_tree_traverse(tree_urls: List[str], acc: List[str], source_tree_url: str) -> List[str]:
    """Recursively traversge Github trees to get all file paths in a folder."""
    ...

def get_source_files_recursive(source_tree_url: str, path: str) -> List[str]:
    """Get source files of a Github folder recursively."""
    ...

class ChangeDirectory:
    """Context manager for changing the current working directory."""
    def __init__(self, new_path: str) -> None:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, etype: object, value: object, traceback: object) -> None:
        ...
    


