"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""JSON Reader."""
class XMLReader(BaseReader):
    """
    XML reader.

    Reads XML documents with options to help suss out relationships between nodes.

    Args:
        tree_level_split (int): From which level in the xml tree we split documents,
        the default level is the root which is level 0

    """
    def __init__(self, tree_level_split: Optional[int] = ...) -> None:
        """Initialize with arguments."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ...) -> List[Document]:
        """
        Load data from the input file.

        Args:
            file (Path): Path to the input file.
            extra_info (Optional[Dict]): Additional information. Default is None.

        Returns:
            List[Document]: List of documents.

        """
        ...
    


