"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Image parser.

Contains parsers for image files.

"""
class ImageReader(BaseReader):
    """
    Image parser.

    Extract text from images using DONUT or pytesseract.

    """
    def __init__(self, parser_config: Optional[Dict] = ..., keep_image: bool = ..., parse_text: bool = ..., text_type: str = ..., pytesseract_model_kwargs: Dict[str, Any] = ...) -> None:
        """Init parser."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


