"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from llama_index.core.indices.query.query_transform.prompts import DecomposeQueryTransformPrompt, ImageOutputQueryTransformPrompt, StepDecomposeQueryTransformPrompt
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.llms import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.schema import QueryBundle, QueryType

"""Query transform."""
class BaseQueryTransform(PromptMixin, DispatcherSpanMixin):
    """
    Base class for query transform.

    A query transform augments a raw query string with associated transformations
    to improve index querying.

    The query transformation is performed before the query is sent to the index.

    """
    def run(self, query_bundle_or_str: QueryType, metadata: Optional[Dict] = ...) -> QueryBundle:
        """Run query transform."""
        ...
    
    def __call__(self, query_bundle_or_str: QueryType, metadata: Optional[Dict] = ...) -> QueryBundle:
        """Run query processor."""
        ...
    


class IdentityQueryTransform(BaseQueryTransform):
    """
    Identity query transform.

    Do nothing to the query.

    """
    ...


class HyDEQueryTransform(BaseQueryTransform):
    """
    Hypothetical Document Embeddings (HyDE) query transform.

    It uses an LLM to generate hypothetical answer(s) to a given query,
    and use the resulting documents as embedding strings.

    As described in `[Precise Zero-Shot Dense Retrieval without Relevance Labels]
    (https://arxiv.org/abs/2212.10496)`
    """
    def __init__(self, llm: Optional[LLM] = ..., hyde_prompt: Optional[BasePromptTemplate] = ..., include_original: bool = ...) -> None:
        """
        Initialize HyDEQueryTransform.

        Args:
            llm_predictor (Optional[LLM]): LLM for generating
                hypothetical documents
            hyde_prompt (Optional[BasePromptTemplate]): Custom prompt for HyDE
            include_original (bool): Whether to include original query
                string as one of the embedding strings

        """
        ...
    


class DecomposeQueryTransform(BaseQueryTransform):
    """
    Decompose query transform.

    Decomposes query into a subquery given the current index struct.
    Performs a single step transformation.

    Args:
        llm_predictor (Optional[LLM]): LLM for generating
            hypothetical documents

    """
    def __init__(self, llm: Optional[LLM] = ..., decompose_query_prompt: Optional[DecomposeQueryTransformPrompt] = ..., verbose: bool = ...) -> None:
        """Init params."""
        ...
    


class ImageOutputQueryTransform(BaseQueryTransform):
    """
    Image output query transform.

    Adds instructions for formatting image output.
    By default, this prompts the LLM to format image output as an HTML <img> tag,
    which can be displayed nicely in jupyter notebook.
    """
    def __init__(self, width: int = ..., query_prompt: Optional[ImageOutputQueryTransformPrompt] = ...) -> None:
        """
        Init ImageOutputQueryTransform.

        Args:
            width (int): desired image display width in pixels
            query_prompt (ImageOutputQueryTransformPrompt): custom prompt for
                augmenting query with image output instructions.

        """
        ...
    


class StepDecomposeQueryTransform(BaseQueryTransform):
    """
    Step decompose query transform.

    Decomposes query into a subquery given the current index struct
    and previous reasoning.

    NOTE: doesn't work yet.

    Args:
        llm_predictor (Optional[LLM]): LLM for generating
            hypothetical documents

    """
    def __init__(self, llm: Optional[LLM] = ..., step_decompose_query_prompt: Optional[StepDecomposeQueryTransformPrompt] = ..., verbose: bool = ...) -> None:
        """Init params."""
        ...
    


