"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, Dict, List, Optional, Sequence, Tuple
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.llms.llm import LLM
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, IndexNode, TextNode

DEFAULT_SUMMARY_QUERY_STR = ...
class TableColumnOutput(BaseModel):
    """Output from analyzing a table column."""
    col_name: str
    col_type: str
    summary: Optional[str] = ...
    def __str__(self) -> str:
        """Convert to string representation."""
        ...
    


class TableOutput(BaseModel):
    """Output from analyzing a table."""
    summary: str
    table_title: Optional[str] = ...
    table_id: Optional[str] = ...
    columns: List[TableColumnOutput]


class Element(BaseModel):
    """Element object."""
    model_config = ...
    id: str
    type: str
    element: Any
    title_level: Optional[int] = ...
    table_output: Optional[TableOutput] = ...
    table: Optional[Any] = ...
    markdown: Optional[str] = ...
    page_number: Optional[int] = ...


class BaseElementNodeParser(NodeParser):
    """
    Splits a document into Text Nodes and Index Nodes corresponding to embedded objects.

    Supports text and tables currently.
    """
    callback_manager: CallbackManager = ...
    llm: Optional[LLM] = ...
    summary_query_str: str = ...
    num_workers: int = ...
    show_progress: bool = ...
    nested_node_parser: Optional[NodeParser] = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @classmethod
    def from_defaults(cls, callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> BaseElementNodeParser:
        ...
    
    @abstractmethod
    def get_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    async def aget_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    @abstractmethod
    def extract_elements(self, text: str, **kwargs: Any) -> List[Element]:
        """Extract elements from text."""
        ...
    
    def get_table_elements(self, elements: List[Element]) -> List[Element]:
        """Get table elements."""
        ...
    
    def get_text_elements(self, elements: List[Element]) -> List[Element]:
        """Get text elements."""
        ...
    
    def extract_table_summaries(self, elements: List[Element]) -> None:
        """Go through elements, extract out summaries that are tables."""
        ...
    
    async def aextract_table_summaries(self, elements: List[Element]) -> None:
        """Go through elements, extract out summaries that are tables."""
        ...
    
    def get_base_nodes_and_mappings(self, nodes: List[BaseNode]) -> Tuple[List[BaseNode], Dict]:
        """
        Get base nodes and mappings.

        Given a list of nodes and IndexNode objects, return the base nodes and a mapping
        from index id to child nodes (which are excluded from the base nodes).

        """
        ...
    
    def get_nodes_and_objects(self, nodes: List[BaseNode]) -> Tuple[List[BaseNode], List[IndexNode]]:
        ...
    
    def get_nodes_from_elements(self, elements: List[Element], node_inherited: Optional[TextNode] = ..., ref_doc_text: Optional[str] = ...) -> List[BaseNode]:
        """Get nodes and mappings."""
        ...
    
    def __call__(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[BaseNode]:
        ...
    
    async def acall(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[BaseNode]:
        ...
    


