"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Sequence
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, Document

"""Hierarchical node parser."""
def get_leaf_nodes(nodes: List[BaseNode]) -> List[BaseNode]:
    """Get leaf nodes."""
    ...

def get_root_nodes(nodes: List[BaseNode]) -> List[BaseNode]:
    """Get root nodes."""
    ...

def get_child_nodes(nodes: List[BaseNode], all_nodes: List[BaseNode]) -> List[BaseNode]:
    """Get child nodes of nodes from given all_nodes."""
    ...

def get_deeper_nodes(nodes: List[BaseNode], depth: int = ...) -> List[BaseNode]:
    """Get children of root nodes in given nodes that have given depth."""
    ...

class HierarchicalNodeParser(NodeParser):
    """
    Hierarchical node parser.

    Splits a document into a recursive hierarchy Nodes using a NodeParser.

    NOTE: this will return a hierarchy of nodes in a flat list, where there will be
    overlap between parent nodes (e.g. with a bigger chunk size), and child nodes
    per parent (e.g. with a smaller chunk size).

    For instance, this may return a list of nodes like:

    - list of top-level nodes with chunk size 2048
    - list of second-level nodes, where each node is a child of a top-level node,
      chunk size 512
    - list of third-level nodes, where each node is a child of a second-level node,
      chunk size 128
    """
    chunk_sizes: Optional[List[int]] = ...
    node_parser_ids: List[str] = ...
    node_parser_map: Dict[str, NodeParser] = ...
    @classmethod
    def from_defaults(cls, chunk_sizes: Optional[List[int]] = ..., chunk_overlap: int = ..., node_parser_ids: Optional[List[str]] = ..., node_parser_map: Optional[Dict[str, NodeParser]] = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., callback_manager: Optional[CallbackManager] = ...) -> HierarchicalNodeParser:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def get_nodes_from_documents(self, documents: Sequence[Document], show_progress: bool = ..., **kwargs: Any) -> List[BaseNode]:
        """Parse document into nodes."""
        ...
    


