"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional
from llama_index.core.node_parser.relational.base_element import BaseElementNodeParser, Element
from llama_index.core.schema import BaseNode, TextNode

class LlamaParseJsonNodeParser(BaseElementNodeParser):
    """
    Llama Parse Json format element node parser.

    Splits a json format document from LlamaParse into Text Nodes and Index Nodes
    corresponding to embedded objects (e.g. tables).

    """
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def get_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    async def aget_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    def extract_elements(self, text: str, mode: Optional[str] = ..., node_id: Optional[str] = ..., node_metadata: Optional[Dict[str, Any]] = ..., table_filters: Optional[List[Callable]] = ..., **kwargs: Any) -> List[Element]:
        """
        Extract elements from json based nodes.

        Args:
            text: node's text content
            mode: different modes for returning different types of elements based on the selected mode
            node_id: unique id for the node
            node_metadata: metadata for the node. the json output for the nodes contains a lot of fields for elements

        """
        ...
    
    def filter_table(self, table_element: Any) -> bool:
        """Filter tables."""
        ...
    


