"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.relational.base_element import BaseElementNodeParser, Element
from llama_index.core.schema import BaseNode, TextNode

"""Unstructured element node parser."""
class UnstructuredElementNodeParser(BaseElementNodeParser):
    """
    Unstructured element node parser.

    Splits a document into Text Nodes and Index Nodes corresponding to embedded objects
    (e.g. tables).

    """
    partitioning_parameters: Optional[Dict[str, Any]] = ...
    def __init__(self, callback_manager: Optional[CallbackManager] = ..., llm: Optional[Any] = ..., summary_query_str: str = ..., partitioning_parameters: Optional[Dict[str, Any]] = ...) -> None:
        """Initialize."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def get_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    async def aget_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        ...
    
    def extract_elements(self, text: str, table_filters: Optional[List[Callable]] = ..., **kwargs: Any) -> List[Element]:
        """Extract elements from text."""
        ...
    
    def filter_table(self, table_element: Any) -> bool:
        """Filter tables."""
        ...
    


