"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.schema import IndexNode, NodeWithScore, QueryType
from llama_index.core.instrumentation import DispatcherSpanMixin

"""Base retriever."""
dispatcher = ...
class BaseRetriever(PromptMixin, DispatcherSpanMixin):
    """Base retriever."""
    def __init__(self, callback_manager: Optional[CallbackManager] = ..., object_map: Optional[Dict] = ..., objects: Optional[List[IndexNode]] = ..., verbose: bool = ...) -> None:
        ...
    
    @dispatcher.span
    def retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        """
        Retrieve nodes given query.

        Args:
            str_or_query_bundle (QueryType): Either a query string or
                a QueryBundle object.

        """
        ...
    
    @dispatcher.span
    async def aretrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        ...
    


