"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Sequence
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.schema import NodeWithScore, QueryBundle, QueryType
from llama_index.core.instrumentation import DispatcherSpanMixin

"""Base query engine."""
dispatcher = ...
logger = ...
class BaseQueryEngine(PromptMixin, DispatcherSpanMixin):
    """Base query engine."""
    def __init__(self, callback_manager: Optional[CallbackManager]) -> None:
        ...
    
    @dispatcher.span
    def query(self, str_or_query_bundle: QueryType) -> RESPONSE_TYPE:
        ...
    
    @dispatcher.span
    async def aquery(self, str_or_query_bundle: QueryType) -> RESPONSE_TYPE:
        ...
    
    def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    def synthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    
    async def asynthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    


