"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.schema import QueryBundle

class BaseAutoRetriever(BaseRetriever):
    """Base auto retriever."""
    @abstractmethod
    def generate_retrieval_spec(self, query_bundle: QueryBundle, **kwargs: Any) -> BaseModel:
        """Generate retrieval spec synchronously."""
        ...
    
    @abstractmethod
    async def agenerate_retrieval_spec(self, query_bundle: QueryBundle, **kwargs: Any) -> BaseModel:
        """Generate retrieval spec asynchronously."""
        ...
    


