"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

class IPYNBReader(BaseReader):
    """Image parser."""
    def __init__(self, parser_config: Optional[Dict] = ..., concatenate: bool = ...) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


