"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Union
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.callbacks import CallbackManager, trace_method
from llama_index.core.chat_engine.types import AgentChatResponse, BaseChatEngine, StreamingAgentChatResponse
from llama_index.core.indices.base_retriever import BaseRetriever
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import PromptTemplate

logger = ...
DEFAULT_CONTEXT_PROMPT_TEMPLATE = ...
DEFAULT_CONTEXT_REFINE_PROMPT_TEMPLATE = ...
DEFAULT_CONDENSE_PROMPT_TEMPLATE = ...
class CondensePlusContextChatEngine(BaseChatEngine):
    """
    Condensed Conversation & Context Chat Engine.

    First condense a conversation and latest user message to a standalone question
    Then build a context for the standalone question from a retriever,
    Then pass the context along with prompt and user message to LLM to generate a response.
    """
    def __init__(self, retriever: BaseRetriever, llm: LLM, memory: BaseMemory, context_prompt: Optional[Union[str, PromptTemplate]] = ..., context_refine_prompt: Optional[Union[str, PromptTemplate]] = ..., condense_prompt: Optional[Union[str, PromptTemplate]] = ..., system_prompt: Optional[str] = ..., skip_condense: bool = ..., node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., callback_manager: Optional[CallbackManager] = ..., verbose: bool = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, retriever: BaseRetriever, llm: Optional[LLM] = ..., chat_history: Optional[List[ChatMessage]] = ..., memory: Optional[BaseMemory] = ..., system_prompt: Optional[str] = ..., context_prompt: Optional[Union[str, PromptTemplate]] = ..., context_refine_prompt: Optional[Union[str, PromptTemplate]] = ..., condense_prompt: Optional[Union[str, PromptTemplate]] = ..., skip_condense: bool = ..., node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., verbose: bool = ..., **kwargs: Any) -> CondensePlusContextChatEngine:
        """Initialize a CondensePlusContextChatEngine from default parameters."""
        ...
    
    @trace_method("chat")
    def chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    def stream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    @trace_method("chat")
    async def achat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    async def astream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    def reset(self) -> None:
        ...
    
    @property
    def chat_history(self) -> List[ChatMessage]:
        """Get chat history."""
        ...
    


