"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Type
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.callbacks import CallbackManager, trace_method
from llama_index.core.chat_engine.types import AgentChatResponse, BaseChatEngine, StreamingAgentChatResponse
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory
from llama_index.core.prompts.base import BasePromptTemplate

logger = ...
DEFAULT_TEMPLATE = ...
DEFAULT_PROMPT = ...
class CondenseQuestionChatEngine(BaseChatEngine):
    """
    Condense Question Chat Engine.

    First generate a standalone question from conversation context and last message,
    then query the query engine for a response.
    """
    def __init__(self, query_engine: BaseQueryEngine, condense_question_prompt: BasePromptTemplate, memory: BaseMemory, llm: LLM, verbose: bool = ..., callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, query_engine: BaseQueryEngine, condense_question_prompt: Optional[BasePromptTemplate] = ..., chat_history: Optional[List[ChatMessage]] = ..., memory: Optional[BaseMemory] = ..., memory_cls: Type[BaseMemory] = ..., verbose: bool = ..., system_prompt: Optional[str] = ..., prefix_messages: Optional[List[ChatMessage]] = ..., llm: Optional[LLM] = ..., **kwargs: Any) -> CondenseQuestionChatEngine:
        """Initialize a CondenseQuestionChatEngine from default parameters."""
        ...
    
    @trace_method("chat")
    def chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    def stream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    @trace_method("chat")
    async def achat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    async def astream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    def reset(self) -> None:
        ...
    
    @property
    def chat_history(self) -> List[ChatMessage]:
        """Get chat history."""
        ...
    


