"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.callbacks import CallbackManager, trace_method
from llama_index.core.chat_engine.types import AgentChatResponse, BaseChatEngine, StreamingAgentChatResponse
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import PromptTemplate
from llama_index.core.schema import NodeWithScore

DEFAULT_CONTEXT_TEMPLATE = ...
DEFAULT_REFINE_TEMPLATE = ...
class ContextChatEngine(BaseChatEngine):
    """
    Context Chat Engine.

    Uses a retriever to retrieve a context, set the context in the system prompt,
    and then uses an LLM to generate a response, for a fluid chat experience.
    """
    def __init__(self, retriever: BaseRetriever, llm: LLM, memory: BaseMemory, prefix_messages: List[ChatMessage], node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., context_template: Optional[Union[str, PromptTemplate]] = ..., context_refine_template: Optional[Union[str, PromptTemplate]] = ..., callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, retriever: BaseRetriever, chat_history: Optional[List[ChatMessage]] = ..., memory: Optional[BaseMemory] = ..., system_prompt: Optional[str] = ..., prefix_messages: Optional[List[ChatMessage]] = ..., node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., context_template: Optional[Union[str, PromptTemplate]] = ..., context_refine_template: Optional[Union[str, PromptTemplate]] = ..., llm: Optional[LLM] = ..., **kwargs: Any) -> ContextChatEngine:
        """Initialize a ContextChatEngine from default parameters."""
        ...
    
    @trace_method("chat")
    def chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ..., prev_chunks: Optional[List[NodeWithScore]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    def stream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ..., prev_chunks: Optional[List[NodeWithScore]] = ...) -> StreamingAgentChatResponse:
        ...
    
    @trace_method("chat")
    async def achat(self, message: str, chat_history: Optional[List[ChatMessage]] = ..., prev_chunks: Optional[List[NodeWithScore]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    async def astream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ..., prev_chunks: Optional[List[NodeWithScore]] = ...) -> StreamingAgentChatResponse:
        ...
    
    def reset(self) -> None:
        ...
    
    @property
    def chat_history(self) -> List[ChatMessage]:
        """Get chat history."""
        ...
    


