"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Type
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.callbacks import CallbackManager, trace_method
from llama_index.core.chat_engine.types import AgentChatResponse, BaseChatEngine, StreamingAgentChatResponse
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory

class SimpleChatEngine(BaseChatEngine):
    """
    Simple Chat Engine.

    Have a conversation with the LLM.
    This does not make use of a knowledge base.
    """
    def __init__(self, llm: LLM, memory: BaseMemory, prefix_messages: List[ChatMessage], callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, chat_history: Optional[List[ChatMessage]] = ..., memory: Optional[BaseMemory] = ..., memory_cls: Type[BaseMemory] = ..., system_prompt: Optional[str] = ..., prefix_messages: Optional[List[ChatMessage]] = ..., llm: Optional[LLM] = ..., **kwargs: Any) -> SimpleChatEngine:
        """Initialize a SimpleChatEngine from default parameters."""
        ...
    
    @trace_method("chat")
    def chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    def stream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    @trace_method("chat")
    async def achat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> AgentChatResponse:
        ...
    
    @trace_method("chat")
    async def astream_chat(self, message: str, chat_history: Optional[List[ChatMessage]] = ...) -> StreamingAgentChatResponse:
        ...
    
    def reset(self) -> None:
        ...
    
    @property
    def chat_history(self) -> List[ChatMessage]:
        """Get chat history."""
        ...
    


