"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Iterable, List, Optional, Tuple
from sqlalchemy import MetaData
from sqlalchemy.engine import Engine

"""SQL wrapper around SQLDatabase in langchain."""
class SQLDatabase:
    """
    SQL Database.

    This class provides a wrapper around the SQLAlchemy engine to interact with a SQL
    database.
    It provides methods to execute SQL commands, insert data into tables, and retrieve
    information about the database schema.
    It also supports optional features such as including or excluding specific tables,
    sampling rows for table info,
    including indexes in table info, and supporting views.

    Based on langchain SQLDatabase.
    https://github.com/langchain-ai/langchain/blob/e355606b1100097665207ca259de6dc548d44c78/libs/langchain/langchain/utilities/sql_database.py#L39

    Args:
        engine (Engine): The SQLAlchemy engine instance to use for database operations.
        schema (Optional[str]): The name of the schema to use, if any.
        metadata (Optional[MetaData]): The metadata instance to use, if any.
        ignore_tables (Optional[List[str]]): List of table names to ignore. If set,
            include_tables must be None.
        include_tables (Optional[List[str]]): List of table names to include. If set,
            ignore_tables must be None.
        sample_rows_in_table_info (int): The number of sample rows to include in table
            info.
        indexes_in_table_info (bool): Whether to include indexes in table info.
        custom_table_info (Optional[dict]): Custom table info to use.
        view_support (bool): Whether to support views.
        max_string_length (int): The maximum string length to use.

    """
    def __init__(self, engine: Engine, schema: Optional[str] = ..., metadata: Optional[MetaData] = ..., ignore_tables: Optional[List[str]] = ..., include_tables: Optional[List[str]] = ..., sample_rows_in_table_info: int = ..., indexes_in_table_info: bool = ..., custom_table_info: Optional[dict] = ..., view_support: bool = ..., max_string_length: int = ...) -> None:
        """Create engine from database URI."""
        ...
    
    @property
    def engine(self) -> Engine:
        """Return SQL Alchemy engine."""
        ...
    
    @property
    def metadata_obj(self) -> MetaData:
        """Return SQL Alchemy metadata."""
        ...
    
    @classmethod
    def from_uri(cls, database_uri: str, engine_args: Optional[dict] = ..., **kwargs: Any) -> SQLDatabase:
        """Construct a SQLAlchemy engine from URI."""
        ...
    
    @property
    def dialect(self) -> str:
        """Return string representation of dialect to use."""
        ...
    
    def get_usable_table_names(self) -> Iterable[str]:
        """Get names of tables available."""
        ...
    
    def get_table_columns(self, table_name: str) -> List[Any]:
        """Get table columns."""
        ...
    
    def get_single_table_info(self, table_name: str) -> str:
        """Get table info for a single table."""
        ...
    
    def insert_into_table(self, table_name: str, data: dict) -> None:
        """Insert data into a table."""
        ...
    
    def truncate_word(self, content: Any, *, length: int, suffix: str = ...) -> str:
        """
        Truncate a string to a certain number of words, based on the max string
        length.
        """
        ...
    
    def run_sql(self, command: str) -> Tuple[str, Dict]:
        """
        Execute a SQL statement and return a string representing the results.

        If the statement returns rows, a string of the results is returned.
        If the statement returns no rows, an empty string is returned.
        """
        ...
    


