"""
This type stub file was generated by pyright.
"""

from typing import Awaitable, Callable, List, Optional, Sequence
from llama_index.core.base.llms.types import ChatMessage, ChatResponse, ChatResponseAsyncGen, ChatResponseGen, CompletionResponse, CompletionResponseAsyncGen, CompletionResponseGen, ImageBlock
from llama_index.core.schema import ImageNode

def messages_to_history_str(messages: Sequence[ChatMessage]) -> str:
    """Convert messages to a history string."""
    ...

def messages_to_prompt(messages: Sequence[ChatMessage]) -> str:
    """Convert messages to a prompt string."""
    ...

def prompt_to_messages(prompt: str) -> List[ChatMessage]:
    """Convert a string prompt to a sequence of messages."""
    ...

def completion_response_to_chat_response(completion_response: CompletionResponse) -> ChatResponse:
    """Convert a completion response to a chat response."""
    ...

def stream_completion_response_to_chat_response(completion_response_gen: CompletionResponseGen) -> ChatResponseGen:
    """Convert a stream completion response to a stream chat response."""
    ...

def astream_completion_response_to_chat_response(completion_response_gen: CompletionResponseAsyncGen) -> ChatResponseAsyncGen:
    """Convert an async stream completion to an async stream chat response."""
    ...

def chat_response_to_completion_response(chat_response: ChatResponse) -> CompletionResponse:
    """Convert a chat response to a completion response."""
    ...

def stream_chat_response_to_completion_response(chat_response_gen: ChatResponseGen) -> CompletionResponseGen:
    """Convert a stream chat response to a completion response."""
    ...

def completion_to_chat_decorator(func: Callable[..., CompletionResponse]) -> Callable[..., ChatResponse]:
    """Convert a completion function to a chat function."""
    ...

def stream_completion_to_chat_decorator(func: Callable[..., CompletionResponseGen]) -> Callable[..., ChatResponseGen]:
    """Convert a completion function to a chat function."""
    ...

def chat_to_completion_decorator(func: Callable[..., ChatResponse]) -> Callable[..., CompletionResponse]:
    """Convert a chat function to a completion function."""
    ...

def stream_chat_to_completion_decorator(func: Callable[..., ChatResponseGen]) -> Callable[..., CompletionResponseGen]:
    """Convert a chat function to a completion function."""
    ...

def acompletion_to_chat_decorator(func: Callable[..., Awaitable[CompletionResponse]]) -> Callable[..., Awaitable[ChatResponse]]:
    """Convert a completion function to a chat function."""
    ...

def achat_to_completion_decorator(func: Callable[..., Awaitable[ChatResponse]]) -> Callable[..., Awaitable[CompletionResponse]]:
    """Convert a chat function to a completion function."""
    ...

def astream_completion_to_chat_decorator(func: Callable[..., Awaitable[CompletionResponseAsyncGen]]) -> Callable[..., Awaitable[ChatResponseAsyncGen]]:
    """Convert a completion function to a chat function."""
    ...

def astream_chat_to_completion_decorator(func: Callable[..., Awaitable[ChatResponseAsyncGen]]) -> Callable[..., Awaitable[CompletionResponseAsyncGen]]:
    """Convert a chat function to a completion function."""
    ...

def async_stream_completion_response_to_chat_response(completion_response_gen: CompletionResponseAsyncGen) -> ChatResponseAsyncGen:
    """Convert a stream completion response to a stream chat response."""
    ...

def astream_chat_response_to_completion_response(chat_response_gen: ChatResponseAsyncGen) -> CompletionResponseAsyncGen:
    """Convert a stream chat response to a completion response."""
    ...

def get_from_param_or_env(key: str, param: Optional[str] = ..., env_key: Optional[str] = ..., default: Optional[str] = ...) -> str:
    """Get a value from a param or an environment variable."""
    ...

def image_node_to_image_block(image_node: ImageNode) -> ImageBlock:
    """
    Get an ImageBlock from an ImageNode.

    Args:
        image_node (ImageNode): ImageNode to convert.

    Returns:
        ImageBlock: block representation of the node.

    Raises:
        ValueError: when the image provided within the ImageNode is not correctly base64-encoded.

    """
    ...

