"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.query_engine.flare.answer_inserter import BaseLookaheadAnswerInserter
from llama_index.core.query_engine.flare.output_parser import IsDoneOutputParser, QueryTaskOutputParser
from llama_index.core.schema import NodeWithScore, QueryBundle

"""
Query engines based on the FLARE paper.

Active Retrieval Augmented Generation.

"""
DEFAULT_EXAMPLES = ...
DEFAULT_FIRST_SKILL = ...
DEFAULT_SECOND_SKILL = ...
DEFAULT_END = ...
DEFAULT_INSTRUCT_PROMPT_TMPL = ...
DEFAULT_INSTRUCT_PROMPT = ...
class FLAREInstructQueryEngine(BaseQueryEngine):
    """
    FLARE Instruct query engine.

    This is the version of FLARE that uses retrieval-encouraging instructions.

    NOTE: this is a beta feature. Interfaces might change, and it might not
    always give correct answers.

    Args:
        query_engine (BaseQueryEngine): query engine to use
        llm (Optional[LLM]): LLM model. Defaults to None.
        instruct_prompt (Optional[PromptTemplate]): instruct prompt. Defaults to None.
        lookahead_answer_inserter (Optional[BaseLookaheadAnswerInserter]):
            lookahead answer inserter. Defaults to None.
        done_output_parser (Optional[IsDoneOutputParser]): done output parser.
            Defaults to None.
        query_task_output_parser (Optional[QueryTaskOutputParser]):
            query task output parser. Defaults to None.
        max_iterations (int): max iterations. Defaults to 10.
        max_lookahead_query_tasks (int): max lookahead query tasks. Defaults to 1.
        callback_manager (Optional[CallbackManager]): callback manager.
            Defaults to None.
        verbose (bool): give verbose outputs. Defaults to False.

    """
    def __init__(self, query_engine: BaseQueryEngine, llm: Optional[LLM] = ..., instruct_prompt: Optional[BasePromptTemplate] = ..., lookahead_answer_inserter: Optional[BaseLookaheadAnswerInserter] = ..., done_output_parser: Optional[IsDoneOutputParser] = ..., query_task_output_parser: Optional[QueryTaskOutputParser] = ..., max_iterations: int = ..., max_lookahead_query_tasks: int = ..., callback_manager: Optional[CallbackManager] = ..., verbose: bool = ...) -> None:
        """Init params."""
        ...
    
    def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    async def aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    


