"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.data_structs.data_structs import EmptyIndexStruct
from llama_index.core.indices.base import BaseIndex
from llama_index.core.llms.utils import LLMType
from llama_index.core.storage.docstore.types import RefDocInfo

"""
Empty index.

An index that doesn't contain any documents. Can only be used for
pure LLM calls.

"""
class EmptyIndex(BaseIndex[EmptyIndexStruct]):
    """
    Empty Index.

    An index that doesn't contain any documents. Used for
    pure LLM calls.
    NOTE: this exists because an empty index it allows certain properties,
    such as the ability to be composed with other indices + token
    counting + others.

    """
    index_struct_cls = ...
    def __init__(self, index_struct: Optional[EmptyIndexStruct] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        ...
    
    def as_query_engine(self, llm: Optional[LLMType] = ..., **kwargs: Any) -> BaseQueryEngine:
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


GPTEmptyIndex = EmptyIndex
