"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.empty.base import EmptyIndex
from llama_index.core.prompts import BasePromptTemplate

"""Default query for EmptyIndex."""
class EmptyIndexRetriever(BaseRetriever):
    """
    EmptyIndex query.

    Passes the raw LLM call to the underlying LLM model.

    Args:
        input_prompt (Optional[BasePromptTemplate]): A Simple Input Prompt
            (see :ref:`Prompt-Templates`).

    """
    def __init__(self, index: EmptyIndex, input_prompt: Optional[BasePromptTemplate] = ..., callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


