"""
This type stub file was generated by pyright.
"""

from fsspec import AbstractFileSystem
from pathlib import Path
from typing import Any, Dict, List, Optional
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""Flat reader."""
class FlatReader(BaseReader):
    """
    Flat reader.

    Extract raw text from a file and save the file type in the metadata
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file into string."""
        ...
    


