"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.bridge.pydantic import SerializeAsAny, field_serializer, model_validator
from llama_index.core.llms.llm import LLM
from llama_index.core.memory.types import BaseMemory
from llama_index.core.storage.chat_store import BaseChatStore

DEFAULT_TOKEN_LIMIT_RATIO = ...
DEFAULT_TOKEN_LIMIT = ...
SUMMARIZE_PROMPT = ...
logger = ...
class ChatSummaryMemoryBuffer(BaseMemory):
    """
    Deprecated: Please use `llama_index.core.memory.Memory` instead.

    Buffer for storing chat history that uses the full text for the latest
    {token_limit}.

    All older messages are iteratively summarized using the {llm} provided, with
    the max number of tokens defined by the {llm}.

    User can specify whether initial tokens (usually a system prompt)
    should be counted as part of the {token_limit}
    using the parameter {count_initial_tokens}.

    This buffer is useful to retain the most important information from a
    long chat history, while limiting the token count and latency
    of each request to the LLM.
    """
    token_limit: int
    count_initial_tokens: bool = ...
    llm: Optional[SerializeAsAny[LLM]] = ...
    summarize_prompt: Optional[str] = ...
    tokenizer_fn: Callable[[str], List] = ...
    chat_store: SerializeAsAny[BaseChatStore] = ...
    chat_store_key: str = ...
    _token_count: int = ...
    @field_serializer("chat_store")
    def serialize_courses_in_order(self, chat_store: BaseChatStore) -> dict:
        ...
    
    @model_validator(mode="before")
    @classmethod
    def validate_memory(cls, values: dict) -> dict:
        """Validate the memory."""
        ...
    
    @classmethod
    def from_defaults(cls, chat_history: Optional[List[ChatMessage]] = ..., llm: Optional[LLM] = ..., chat_store: Optional[BaseChatStore] = ..., chat_store_key: str = ..., token_limit: Optional[int] = ..., tokenizer_fn: Optional[Callable[[str], List]] = ..., summarize_prompt: Optional[str] = ..., count_initial_tokens: bool = ..., **kwargs: Any) -> ChatSummaryMemoryBuffer:
        """
        Create a chat memory buffer from an LLM
        and an initial list of chat history messages.
        """
        ...
    
    @classmethod
    def class_name(cls) -> str:
        """Get class name."""
        ...
    
    def to_string(self) -> str:
        """Convert memory to string."""
        ...
    
    def to_dict(self, **kwargs: Any) -> dict:
        """Convert memory to dict."""
        ...
    
    @classmethod
    def from_string(cls, json_str: str, **kwargs: Any) -> ChatSummaryMemoryBuffer:
        """Create a chat memory buffer from a string."""
        ...
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> ChatSummaryMemoryBuffer:
        ...
    
    def get(self, input: Optional[str] = ..., initial_token_count: int = ..., **kwargs: Any) -> List[ChatMessage]:
        """Get chat history."""
        ...
    
    def get_all(self) -> List[ChatMessage]:
        """Get all chat history."""
        ...
    
    def put(self, message: ChatMessage) -> None:
        """Put chat history."""
        ...
    
    async def aput(self, message: ChatMessage) -> None:
        """Put chat history."""
        ...
    
    def set(self, messages: List[ChatMessage]) -> None:
        """Set chat history."""
        ...
    
    def reset(self) -> None:
        """Reset chat history."""
        ...
    
    def get_token_count(self) -> int:
        """Returns the token count of the memory buffer (excluding the last assistant response)."""
        ...
    


