"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.bridge.pydantic import model_validator
from llama_index.core.llms.llm import LLM
from llama_index.core.memory.types import BaseChatStoreMemory
from llama_index.core.storage.chat_store import BaseChatStore

DEFAULT_TOKEN_LIMIT_RATIO = ...
DEFAULT_TOKEN_LIMIT = ...
class ChatMemoryBuffer(BaseChatStoreMemory):
    """
    Deprecated: Please use `llama_index.core.memory.Memory` instead.

    Simple buffer for storing chat history.
    """
    token_limit: int
    tokenizer_fn: Callable[[str], List] = ...
    @classmethod
    def class_name(cls) -> str:
        """Get class name."""
        ...
    
    @model_validator(mode="before")
    @classmethod
    def validate_memory(cls, values: dict) -> dict:
        ...
    
    @classmethod
    def from_defaults(cls, chat_history: Optional[List[ChatMessage]] = ..., llm: Optional[LLM] = ..., chat_store: Optional[BaseChatStore] = ..., chat_store_key: str = ..., token_limit: Optional[int] = ..., tokenizer_fn: Optional[Callable[[str], List]] = ..., **kwargs: Any) -> ChatMemoryBuffer:
        """Create a chat memory buffer from an LLM."""
        ...
    
    def to_string(self) -> str:
        """Convert memory to string."""
        ...
    
    @classmethod
    def from_string(cls, json_str: str) -> ChatMemoryBuffer:
        """Create a chat memory buffer from a string."""
        ...
    
    def to_dict(self, **kwargs: Any) -> dict:
        """Convert memory to dict."""
        ...
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> ChatMemoryBuffer:
        ...
    
    def get(self, input: Optional[str] = ..., initial_token_count: int = ..., **kwargs: Any) -> List[ChatMessage]:
        """Get chat history."""
        ...
    
    async def aget(self, input: Optional[str] = ..., initial_token_count: int = ..., **kwargs: Any) -> List[ChatMessage]:
        """Get chat history."""
        ...
    


