"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Set
from dataclasses_json import DataClassJsonMixin
from llama_index.core.data_structs.struct_type import IndexStructType
from llama_index.core.schema import BaseNode, TextNode

"""
Data structures.

Nodes are decoupled from the indices.

"""
Node = TextNode
@dataclass
class IndexStruct(DataClassJsonMixin):
    """A base data struct for a LlamaIndex."""
    index_id: str = ...
    summary: Optional[str] = ...
    def get_summary(self) -> str:
        """Get text summary."""
        ...
    
    @classmethod
    @abstractmethod
    def get_type(cls) -> IndexStructType:
        """Get index struct type."""
        ...
    


@dataclass
class IndexGraph(IndexStruct):
    """A graph representing the tree-structured index."""
    all_nodes: Dict[int, str] = ...
    root_nodes: Dict[int, str] = ...
    node_id_to_children_ids: Dict[str, List[str]] = ...
    @property
    def node_id_to_index(self) -> Dict[str, int]:
        """Map from node id to index."""
        ...
    
    @property
    def size(self) -> int:
        """Get the size of the graph."""
        ...
    
    def get_index(self, node: BaseNode) -> int:
        """Get index of node."""
        ...
    
    def insert(self, node: BaseNode, index: Optional[int] = ..., children_nodes: Optional[Sequence[BaseNode]] = ...) -> None:
        """Insert node."""
        ...
    
    def get_children(self, parent_node: Optional[BaseNode]) -> Dict[int, str]:
        """Get children nodes."""
        ...
    
    def insert_under_parent(self, node: BaseNode, parent_node: Optional[BaseNode], new_index: Optional[int] = ...) -> None:
        """Insert under parent node."""
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class KeywordTable(IndexStruct):
    """A table of keywords mapping keywords to text chunks."""
    table: Dict[str, Set[str]] = ...
    def add_node(self, keywords: List[str], node: BaseNode) -> None:
        """Add text to table."""
        ...
    
    @property
    def node_ids(self) -> Set[str]:
        """Get all node ids."""
        ...
    
    @property
    def keywords(self) -> Set[str]:
        """Get all keywords in the table."""
        ...
    
    @property
    def size(self) -> int:
        """Get the size of the table."""
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class IndexList(IndexStruct):
    """A list of documents."""
    nodes: List[str] = ...
    def add_node(self, node: BaseNode) -> None:
        """Add text to table, return current position in list."""
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class IndexLPG(IndexStruct):
    """An index struct for LPG index (doesn't actually store anything)."""
    def add_node(self, node: BaseNode) -> None:
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        ...
    


@dataclass
class IndexDict(IndexStruct):
    """A simple dictionary of documents."""
    nodes_dict: Dict[str, str] = ...
    doc_id_dict: Dict[str, List[str]] = ...
    embeddings_dict: Dict[str, List[float]] = ...
    def add_node(self, node: BaseNode, text_id: Optional[str] = ...) -> str:
        """Add text to table, return current position in list."""
        ...
    
    def delete(self, doc_id: str) -> None:
        """Delete a Node."""
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class MultiModelIndexDict(IndexDict):
    """A simple dictionary of documents, but loads a MultiModelVectorStore."""
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class KG(IndexStruct):
    """A table of keywords mapping keywords to text chunks."""
    table: Dict[str, Set[str]] = ...
    rel_map: Dict[str, List[List[str]]] = ...
    embedding_dict: Dict[str, List[float]] = ...
    @property
    def node_ids(self) -> Set[str]:
        """Get all node ids."""
        ...
    
    def add_to_embedding_dict(self, triplet_str: str, embedding: List[float]) -> None:
        """Add embedding to dict."""
        ...
    
    def add_node(self, keywords: List[str], node: BaseNode) -> None:
        """Add text to table."""
        ...
    
    def search_node_by_keyword(self, keyword: str) -> List[str]:
        """Search for nodes by keyword."""
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class EmptyIndexStruct(IndexStruct):
    """Empty index."""
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


