"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, List
from llama_index.core.data_structs.data_structs import IndexStruct
from llama_index.core.data_structs.struct_type import IndexStructType
from llama_index.core.schema import BaseNode

"""Data struct for document summary index."""
@dataclass
class IndexDocumentSummary(IndexStruct):
    """
    A simple struct containing a mapping from summary node_id to doc node_ids.

    Also mapping vice versa.

    """
    summary_id_to_node_ids: Dict[str, List[str]] = ...
    node_id_to_summary_id: Dict[str, str] = ...
    doc_id_to_summary_id: Dict[str, str] = ...
    def add_summary_and_nodes(self, summary_node: BaseNode, nodes: List[BaseNode]) -> str:
        """Add node and summary."""
        ...
    
    @property
    def summary_ids(self) -> List[str]:
        """Get summary ids."""
        ...
    
    def delete(self, doc_id: str) -> None:
        """Delete a document and its nodes."""
        ...
    
    def delete_nodes(self, node_ids: List[str]) -> None:
        ...
    
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


