"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict
from dataclasses_json import DataClassJsonMixin
from llama_index.core.data_structs.data_structs import IndexStruct
from llama_index.core.data_structs.struct_type import IndexStructType

"""Struct store schema."""
@dataclass
class StructDatapoint(DataClassJsonMixin):
    """Struct outputs."""
    fields: Dict[str, Any]
    ...


@dataclass
class BaseStructTable(IndexStruct):
    """Struct outputs."""
    ...


@dataclass
class SQLStructTable(BaseStructTable):
    """SQL struct outputs."""
    context_dict: Dict[str, str] = ...
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


@dataclass
class PandasStructTable(BaseStructTable):
    """Pandas struct outputs."""
    @classmethod
    def get_type(cls) -> IndexStructType:
        """Get type."""
        ...
    


