"""
This type stub file was generated by pyright.
"""

import fsspec
from typing import Optional
from llama_index.core.storage.index_store.keyval_index_store import KVIndexStore
from llama_index.core.storage.kvstore.simple_kvstore import SimpleKVStore

class SimpleIndexStore(KVIndexStore):
    """
    Simple in-memory Index store.

    Args:
        simple_kvstore (SimpleKVStore): simple key-value store

    """
    def __init__(self, simple_kvstore: Optional[SimpleKVStore] = ...) -> None:
        """Init a SimpleIndexStore."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleIndexStore:
        """Create a SimpleIndexStore from a persist directory."""
        ...
    
    @classmethod
    def from_persist_path(cls, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleIndexStore:
        """Create a SimpleIndexStore from a persist path."""
        ...
    
    def persist(self, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the store."""
        ...
    
    @classmethod
    def from_dict(cls, save_dict: dict) -> SimpleIndexStore:
        ...
    
    def to_dict(self) -> dict:
        ...
    


