"""
This type stub file was generated by pyright.
"""

import fsspec
from abc import ABC, abstractmethod
from typing import List, Optional
from llama_index.core.data_structs.data_structs import IndexStruct

DEFAULT_PERSIST_DIR = ...
DEFAULT_PERSIST_FNAME = ...
DEFAULT_PERSIST_PATH = ...
class BaseIndexStore(ABC):
    @abstractmethod
    def index_structs(self) -> List[IndexStruct]:
        ...
    
    @abstractmethod
    async def async_index_structs(self) -> List[IndexStruct]:
        ...
    
    @abstractmethod
    def add_index_struct(self, index_struct: IndexStruct) -> None:
        ...
    
    @abstractmethod
    async def async_add_index_struct(self, index_struct: IndexStruct) -> None:
        ...
    
    @abstractmethod
    def delete_index_struct(self, key: str) -> None:
        ...
    
    @abstractmethod
    async def adelete_index_struct(self, key: str) -> None:
        ...
    
    @abstractmethod
    def get_index_struct(self, struct_id: Optional[str] = ...) -> Optional[IndexStruct]:
        ...
    
    @abstractmethod
    async def aget_index_struct(self, struct_id: Optional[str] = ...) -> Optional[IndexStruct]:
        ...
    
    def persist(self, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the index store to disk."""
        ...
    


