"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Sequence
from llama_index.core.data_structs.data_structs import IndexGraph
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode
from llama_index.core.storage.docstore import BaseDocumentStore

"""Common classes/functions for tree index operations."""
logger = ...
class GPTTreeIndexBuilder:
    """
    GPT tree index builder.

    Helper class to build the tree-structured index,
    or to synthesize an answer.

    """
    def __init__(self, num_children: int, summary_prompt: BasePromptTemplate, llm: Optional[LLM] = ..., docstore: Optional[BaseDocumentStore] = ..., show_progress: bool = ..., use_async: bool = ...) -> None:
        """Initialize with params."""
        ...
    
    @property
    def docstore(self) -> BaseDocumentStore:
        """Return docstore."""
        ...
    
    def build_from_nodes(self, nodes: Sequence[BaseNode], build_tree: bool = ...) -> IndexGraph:
        """
        Build from text.

        Returns:
            IndexGraph: graph object consisting of all_nodes, root_nodes

        """
        ...
    
    def build_index_from_nodes(self, index_graph: IndexGraph, cur_node_ids: Dict[int, str], all_node_ids: Dict[int, str], level: int = ...) -> IndexGraph:
        """Consolidates chunks recursively, in a bottoms-up fashion."""
        ...
    
    async def abuild_index_from_nodes(self, index_graph: IndexGraph, cur_node_ids: Dict[int, str], all_node_ids: Dict[int, str], level: int = ...) -> IndexGraph:
        """Consolidates chunks recursively, in a bottoms-up fashion."""
        ...
    


