"""
This type stub file was generated by pyright.
"""

from typing import Awaitable, Callable, List, Optional, Sequence, Union
from llama_index.core.agent.workflow.base_agent import BaseWorkflowAgent
from llama_index.core.agent.workflow.workflow_events import AgentOutput, ToolCallResult
from llama_index.core.llms import ChatMessage
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory
from llama_index.core.objects import ObjectRetriever
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.tools import BaseTool
from llama_index.core.workflow import Context

DEFAULT_CODE_ACT_PROMPT = ...
EXECUTE_TOOL_NAME = ...
class CodeActAgent(BaseWorkflowAgent):
    """
    A workflow agent that can execute code.
    """
    scratchpad_key: str = ...
    code_execute_fn: Union[Callable, Awaitable] = ...
    code_act_system_prompt: Union[str, BasePromptTemplate] = ...
    def __init__(self, code_execute_fn: Union[Callable, Awaitable], name: str = ..., description: str = ..., system_prompt: Optional[str] = ..., tools: Optional[List[Union[BaseTool, Callable]]] = ..., tool_retriever: Optional[ObjectRetriever] = ..., can_handoff_to: Optional[List[str]] = ..., llm: Optional[LLM] = ..., code_act_system_prompt: Union[str, BasePromptTemplate] = ..., streaming: bool = ...) -> None:
        ...
    
    async def take_step(self, ctx: Context, llm_input: List[ChatMessage], tools: Sequence[BaseTool], memory: BaseMemory) -> AgentOutput:
        """Take a single step with the code act agent."""
        ...
    
    async def handle_tool_call_results(self, ctx: Context, results: List[ToolCallResult], memory: BaseMemory) -> None:
        """Handle tool call results for code act agent."""
        ...
    
    async def finalize(self, ctx: Context, output: AgentOutput, memory: BaseMemory) -> AgentOutput:
        """
        Finalize the code act agent.

        Adds all in-progress messages to memory.
        """
        ...
    


