"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Sequence
from llama_index.core.agent.workflow.base_agent import BaseWorkflowAgent
from llama_index.core.agent.workflow.workflow_events import AgentOutput, ToolCallResult
from llama_index.core.llms import ChatMessage
from llama_index.core.memory import BaseMemory
from llama_index.core.tools import AsyncBaseTool
from llama_index.core.workflow import Context

class FunctionAgent(BaseWorkflowAgent):
    """Function calling agent implementation."""
    scratchpad_key: str = ...
    initial_tool_choice: Optional[str] = ...
    allow_parallel_tool_calls: bool = ...
    async def take_step(self, ctx: Context, llm_input: List[ChatMessage], tools: Sequence[AsyncBaseTool], memory: BaseMemory) -> AgentOutput:
        """Take a single step with the function calling agent."""
        ...
    
    async def handle_tool_call_results(self, ctx: Context, results: List[ToolCallResult], memory: BaseMemory) -> None:
        """Handle tool call results for function calling agent."""
        ...
    
    async def finalize(self, ctx: Context, output: AgentOutput, memory: BaseMemory) -> AgentOutput:
        """
        Finalize the function calling agent.

        Adds all in-progress messages to memory.
        """
        ...
    


