"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta
from typing import Any, Callable, Dict, List, Optional, Sequence, Type, Union
from pydantic import BaseModel
from llama_index.core.agent.workflow.base_agent import BaseWorkflowAgent
from llama_index.core.agent.workflow.workflow_events import AgentInput, AgentOutput, AgentSetup, AgentWorkflowStartEvent, ToolCall, ToolCallResult
from llama_index.core.llms import ChatMessage
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import BaseMemory
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.tools import AsyncBaseTool, BaseTool
from llama_index.core.workflow import Context, StopEvent, Workflow, step
from llama_index.core.workflow.handler import WorkflowHandler
from llama_index.core.workflow.workflow import WorkflowMeta

async def handoff(ctx: Context, to_agent: str, reason: str) -> str:
    """Handoff control of that chat to the given agent."""
    ...

class AgentWorkflowMeta(WorkflowMeta, ABCMeta):
    """Metaclass for AgentWorkflow that inherits from WorkflowMeta."""
    ...


class AgentWorkflow(Workflow, PromptMixin, metaclass=AgentWorkflowMeta):
    """A workflow for managing multiple agents with handoffs."""
    def __init__(self, agents: List[BaseWorkflowAgent], initial_state: Optional[Dict] = ..., root_agent: Optional[str] = ..., handoff_prompt: Optional[Union[str, BasePromptTemplate]] = ..., handoff_output_prompt: Optional[Union[str, BasePromptTemplate]] = ..., state_prompt: Optional[Union[str, BasePromptTemplate]] = ..., timeout: Optional[float] = ..., output_cls: Optional[Type[BaseModel]] = ..., structured_output_fn: Optional[Callable[[List[ChatMessage]], Dict[str, Any]]] = ..., **workflow_kwargs: Any) -> None:
        ...
    
    async def get_tools(self, agent_name: str, input_str: Optional[str] = ...) -> Sequence[AsyncBaseTool]:
        """Get tools for the given agent."""
        ...
    
    @step
    async def init_run(self, ctx: Context, ev: AgentWorkflowStartEvent) -> AgentInput:
        """Sets up the workflow and validates inputs."""
        ...
    
    @step
    async def setup_agent(self, ctx: Context, ev: AgentInput) -> AgentSetup:
        """Main agent handling logic."""
        ...
    
    @step
    async def run_agent_step(self, ctx: Context, ev: AgentSetup) -> AgentOutput:
        """Run the agent."""
        ...
    
    @step
    async def parse_agent_output(self, ctx: Context, ev: AgentOutput) -> Union[StopEvent, AgentInput, ToolCall, None]:
        ...
    
    @step
    async def call_tool(self, ctx: Context, ev: ToolCall) -> ToolCallResult:
        """Calls the tool and handles the result."""
        ...
    
    @step
    async def aggregate_tool_results(self, ctx: Context, ev: ToolCallResult) -> Union[AgentInput, StopEvent, None]:
        """Aggregate tool results and return the next agent input."""
        ...
    
    def run(self, user_msg: Optional[Union[str, ChatMessage]] = ..., chat_history: Optional[List[ChatMessage]] = ..., memory: Optional[BaseMemory] = ..., ctx: Optional[Context] = ..., max_iterations: Optional[int] = ..., start_event: Optional[AgentWorkflowStartEvent] = ..., **kwargs: Any) -> WorkflowHandler:
        ...
    
    @classmethod
    def from_tools_or_functions(cls, tools_or_functions: List[Union[BaseTool, Callable]], llm: Optional[LLM] = ..., system_prompt: Optional[str] = ..., state_prompt: Optional[Union[str, BasePromptTemplate]] = ..., initial_state: Optional[dict] = ..., output_cls: Optional[Type[BaseModel]] = ..., structured_output_fn: Optional[Callable[[List[ChatMessage]], Dict[str, Any]]] = ..., timeout: Optional[float] = ..., verbose: bool = ...) -> AgentWorkflow:
        """
        Initializes an AgentWorkflow from a list of tools or functions.

        The workflow will be initialized with a single agent that uses the provided tools or functions.

        If the LLM is a function calling model, the workflow will use the FunctionAgent.
        Otherwise, it will use the ReActAgent.
        """
        ...
    


