"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Sequence
from llama_index.core.agent.react.formatter import ReActChatFormatter
from llama_index.core.agent.react.output_parser import ReActOutputParser
from llama_index.core.agent.workflow.base_agent import BaseWorkflowAgent
from llama_index.core.agent.workflow.workflow_events import AgentOutput, ToolCallResult
from llama_index.core.bridge.pydantic import model_validator
from llama_index.core.llms import ChatMessage
from llama_index.core.memory import BaseMemory
from llama_index.core.tools import AsyncBaseTool
from llama_index.core.workflow import Context

def default_formatter(fields: Optional[dict] = ...) -> ReActChatFormatter:
    """Sets up a default formatter so that the proper react header is set."""
    ...

class ReActAgent(BaseWorkflowAgent):
    """React agent implementation."""
    reasoning_key: str = ...
    output_parser: ReActOutputParser = ...
    formatter: ReActChatFormatter = ...
    @model_validator(mode="after")
    def validate_formatter(self) -> ReActAgent:
        """Validate the formatter."""
        ...
    
    async def take_step(self, ctx: Context, llm_input: List[ChatMessage], tools: Sequence[AsyncBaseTool], memory: BaseMemory) -> AgentOutput:
        """Take a single step with the React agent."""
        ...
    
    async def handle_tool_call_results(self, ctx: Context, results: List[ToolCallResult], memory: BaseMemory) -> None:
        """Handle tool call results for React agent."""
        ...
    
    async def finalize(self, ctx: Context, output: AgentOutput, memory: BaseMemory) -> AgentOutput:
        """Finalize the React agent."""
        ...
    


