"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, List, Optional
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.interface import TextSplitter
from llama_index.core.schema import Document

"""Code splitter."""
DEFAULT_CHUNK_LINES = ...
DEFAULT_LINES_OVERLAP = ...
DEFAULT_MAX_CHARS = ...
class CodeSplitter(TextSplitter):
    """
    Split code using a AST parser.

    Thank you to Kevin Lu / SweepAI for suggesting this elegant code splitting solution.
    https://docs.sweep.dev/blogs/chunking-2m-files
    """
    language: str = ...
    chunk_lines: int = ...
    chunk_lines_overlap: int = ...
    max_chars: int = ...
    _parser: Any = ...
    def __init__(self, language: str, chunk_lines: int = ..., chunk_lines_overlap: int = ..., max_chars: int = ..., parser: Any = ..., callback_manager: Optional[CallbackManager] = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., id_func: Optional[Callable[[int, Document], str]] = ...) -> None:
        """Initialize a CodeSplitter."""
        ...
    
    @classmethod
    def from_defaults(cls, language: str, chunk_lines: int = ..., chunk_lines_overlap: int = ..., max_chars: int = ..., callback_manager: Optional[CallbackManager] = ..., parser: Any = ...) -> CodeSplitter:
        """Create a CodeSplitter with default values."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def split_text(self, text: str) -> List[str]:
        """
        Split incoming code into chunks using the AST parser.

        This method parses the input code into an AST and then chunks it while preserving
        syntactic structure. It handles error cases and ensures the code can be properly parsed.

        Args:
            text (str): The source code text to split.

        Returns:
            List[str]: A list of code chunks.

        Raises:
            ValueError: If the code cannot be parsed for the specified language.

        """
        ...
    


