"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, TYPE_CHECKING
from llama_index.core.callbacks import CallbackManager
from llama_index.core.node_parser.interface import TextSplitter
from llama_index.core.schema import Document
from langchain.text_splitter import TextSplitter as LC_TextSplitter

if TYPE_CHECKING:
    ...
class LangchainNodeParser(TextSplitter):
    """
    Basic wrapper around langchain's text splitter.

    TODO: Figure out how to make this metadata aware.
    """
    _lc_splitter: LC_TextSplitter = ...
    def __init__(self, lc_splitter: LC_TextSplitter, callback_manager: Optional[CallbackManager] = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., id_func: Optional[Callable[[int, Document], str]] = ...) -> None:
        """Initialize with parameters."""
        ...
    
    def split_text(self, text: str) -> List[str]:
        """Split text into sentences."""
        ...
    


