"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, Sequence, TypedDict
from typing_extensions import Annotated
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.bridge.pydantic import SerializeAsAny, WithJsonSchema
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser import NodeParser
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, Document

DEFAULT_OG_TEXT_METADATA_KEY = ...
class SentenceCombination(TypedDict):
    sentence: str
    index: int
    combined_sentence: str
    combined_sentence_embedding: List[float]
    ...


SentenceSplitterCallable = Annotated[Callable[[str], List[str]], WithJsonSchema({ "type": "string" }, mode="serialization"), WithJsonSchema({ "type": "string" }, mode="validation"),]
class SemanticSplitterNodeParser(NodeParser):
    """
    Semantic node parser.

    Splits a document into Nodes, with each node being a group of semantically related sentences.

    Args:
        buffer_size (int): number of sentences to group together when evaluating semantic similarity
        embed_model: (BaseEmbedding): embedding model to use
        sentence_splitter (Optional[Callable]): splits text into sentences
        breakpoint_percentile_threshold (int): dissimilarity threshold for creating semantic breakpoints, lower value will generate more nodes
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships

    """
    sentence_splitter: SentenceSplitterCallable = ...
    embed_model: SerializeAsAny[BaseEmbedding] = ...
    buffer_size: int = ...
    breakpoint_percentile_threshold: int = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @classmethod
    def from_defaults(cls, embed_model: Optional[BaseEmbedding] = ..., breakpoint_percentile_threshold: Optional[int] = ..., buffer_size: Optional[int] = ..., sentence_splitter: Optional[Callable[[str], List[str]]] = ..., original_text_metadata_key: str = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., callback_manager: Optional[CallbackManager] = ..., id_func: Optional[Callable[[int, Document], str]] = ...) -> SemanticSplitterNodeParser:
        ...
    
    def build_semantic_nodes_from_documents(self, documents: Sequence[Document], show_progress: bool = ...) -> List[BaseNode]:
        """Build window nodes from documents."""
        ...
    
    async def abuild_semantic_nodes_from_documents(self, documents: Sequence[Document], show_progress: bool = ...) -> List[BaseNode]:
        """Asynchronously build window nodes from documents."""
        ...
    


