"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List, Optional, Sequence
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser import NodeParser
from llama_index.core.schema import BaseNode, Document

DEFAULT_OG_TEXT_METADATA_KEY = ...
LANGUAGES: List[str] = ...
LANGUAGE_MODELS: Dict[str, List[str]] = ...
class LanguageConfig:
    def __init__(self, language: str = ..., spacy_model: str = ..., model_validation: bool = ...) -> None:
        ...
    
    def load_model(self) -> None:
        ...
    


class SemanticDoubleMergingSplitterNodeParser(NodeParser):
    """
    Semantic double merging text splitter.

    Splits a document into Nodes, with each node being a group of semantically related sentences.

    Args:
        language_config (LanguageConfig): chooses language and spacy language model to be used
        initial_threshold (float): sets threshold for initializing new chunk
        appending_threshold (float): sets threshold for appending new sentences to chunk
        merging_threshold (float): sets threshold for merging whole chunks
        max_chunk_size (int): maximum size of chunk (in characters)
        merging_range (int): How many chunks 'ahead' beyond the nearest neighbor to be merged if similar (1 or 2 available)
        merging_separator (str): The separator to use when merging chunks. Defaults to a single space.
        sentence_splitter (Optional[Callable]): splits text into sentences

    """
    language_config: LanguageConfig = ...
    initial_threshold: float = ...
    appending_threshold: float = ...
    merging_threshold: float = ...
    max_chunk_size: int = ...
    merging_range: int = ...
    merging_separator: str = ...
    sentence_splitter: Callable[[str], List[str]] = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @classmethod
    def from_defaults(cls, language_config: Optional[LanguageConfig] = ..., initial_threshold: Optional[float] = ..., appending_threshold: Optional[float] = ..., merging_threshold: Optional[float] = ..., max_chunk_size: Optional[int] = ..., merging_range: Optional[int] = ..., merging_separator: Optional[str] = ..., sentence_splitter: Optional[Callable[[str], List[str]]] = ..., original_text_metadata_key: str = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., callback_manager: Optional[CallbackManager] = ..., id_func: Optional[Callable[[int, Document], str]] = ...) -> SemanticDoubleMergingSplitterNodeParser:
        ...
    
    def build_semantic_nodes_from_documents(self, documents: Sequence[Document]) -> List[BaseNode]:
        """Build window nodes from documents."""
        ...
    
    def build_semantic_nodes_from_nodes(self, nodes: Sequence[BaseNode]) -> List[BaseNode]:
        """Build window nodes from nodes."""
        ...
    


