"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, Sequence
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, Document

"""Simple node parser."""
DEFAULT_WINDOW_SIZE = ...
DEFAULT_WINDOW_METADATA_KEY = ...
DEFAULT_OG_TEXT_METADATA_KEY = ...
class SentenceWindowNodeParser(NodeParser):
    """
    Sentence window node parser.

    Splits a document into Nodes, with each node being a sentence.
    Each node contains a window from the surrounding sentences in the metadata.

    Args:
        sentence_splitter (Optional[Callable]): splits text into sentences
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships

    """
    sentence_splitter: Callable[[str], List[str]] = ...
    window_size: int = ...
    window_metadata_key: str = ...
    original_text_metadata_key: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @classmethod
    def from_defaults(cls, sentence_splitter: Optional[Callable[[str], List[str]]] = ..., window_size: int = ..., window_metadata_key: str = ..., original_text_metadata_key: str = ..., include_metadata: bool = ..., include_prev_next_rel: bool = ..., callback_manager: Optional[CallbackManager] = ..., id_func: Optional[Callable[[int, Document], str]] = ...) -> SentenceWindowNodeParser:
        ...
    
    def build_window_nodes_from_documents(self, documents: Sequence[Document]) -> List[BaseNode]:
        """Build window nodes from documents."""
        ...
    


