"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, Sequence, Union
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import PromptTemplate
from llama_index.core.schema import BaseNode, TransformComponent

class SimpleLLMPathExtractor(TransformComponent):
    """
    Extract triples from a graph.

    Uses an LLM and a simple prompt + output parsing to extract paths (i.e. triples) from text.

    Args:
        llm (LLM):
            The language model to use.
        extract_prompt (Union[str, PromptTemplate]):
            The prompt to use for extracting triples.
        parse_fn (callable):
            A function to parse the output of the language model.
        num_workers (int):
            The number of workers to use for parallel processing.
        max_paths_per_chunk (int):
            The maximum number of paths to extract per chunk.

    """
    llm: LLM
    extract_prompt: PromptTemplate
    parse_fn: Callable
    num_workers: int
    max_paths_per_chunk: int
    def __init__(self, llm: Optional[LLM] = ..., extract_prompt: Optional[Union[str, PromptTemplate]] = ..., parse_fn: Callable = ..., max_paths_per_chunk: int = ..., num_workers: int = ...) -> None:
        """Init params."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def __call__(self, nodes: Sequence[BaseNode], show_progress: bool = ..., **kwargs: Any) -> Sequence[BaseNode]:
        """Extract triples from nodes."""
        ...
    
    async def acall(self, nodes: Sequence[BaseNode], show_progress: bool = ..., **kwargs: Any) -> Sequence[BaseNode]:
        """Extract triples from nodes async."""
        ...
    


