apiVersion: 1
datasources:
  - id: 1
    uid: "P872257576FE01AA9"
    orgId: 1
    name: "Backend-Health"
    type: "yesoreyeram-infinity-datasource"
    url: "http://backend:8000/api/v1"
    basicAuth: false
    basicAuthUser: ""
    isDefault: true
    jsonData:
      authType: "none"
      global_queries: []
      httpMethod: "GET"
      pdcInjected: false
    readOnly: true
    apiVersion: ""
