"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.list.base import SummaryIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import PromptTemplate

"""Retrievers for SummaryIndex."""
logger = ...
class SummaryIndexRetriever(BaseRetriever):
    """
    Simple retriever for SummaryIndex that returns all nodes.

    Args:
        index (SummaryIndex): The index to retrieve from.

    """
    def __init__(self, index: SummaryIndex, callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        ...
    


class SummaryIndexEmbeddingRetriever(BaseRetriever):
    """
    Embedding based retriever for SummaryIndex.

    Generates embeddings in a lazy fashion for all
    nodes that are traversed.

    Args:
        index (SummaryIndex): The index to retrieve from.
        similarity_top_k (Optional[int]): The number of top nodes to return.

    """
    def __init__(self, index: SummaryIndex, embed_model: Optional[BaseEmbedding] = ..., similarity_top_k: Optional[int] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        ...
    


class SummaryIndexLLMRetriever(BaseRetriever):
    """
    LLM retriever for SummaryIndex.

    Args:
        index (SummaryIndex): The index to retrieve from.
        choice_select_prompt (Optional[PromptTemplate]): A Choice-Select Prompt
           (see :ref:`Prompt-Templates`).)
        choice_batch_size (int): The number of nodes to query at a time.
        format_node_batch_fn (Optional[Callable]): A function that formats a
            batch of nodes.
        parse_choice_select_answer_fn (Optional[Callable]): A function that parses the
            choice select answer.

    """
    def __init__(self, index: SummaryIndex, llm: Optional[LLM] = ..., choice_select_prompt: Optional[PromptTemplate] = ..., choice_batch_size: int = ..., format_node_batch_fn: Optional[Callable] = ..., parse_choice_select_answer_fn: Optional[Callable] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        ...
    


ListIndexEmbeddingRetriever = SummaryIndexEmbeddingRetriever
ListIndexLLMRetriever = SummaryIndexLLMRetriever
ListIndexRetriever = SummaryIndexRetriever
