"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type
from deprecated import deprecated
from llama_index.core.readers.base import BaseReader

"""
Download loader from Llama Hub.

NOTE: using `download_loader` is now deprecated.
Please do `pip install llama-index-reader-<reader_name>` instead.

"""
@deprecated("`download_loader()` is deprecated. " "Please install tool using pip install directly instead.")
def download_loader(loader_class: str, loader_hub_url: str = ..., refresh_cache: bool = ..., use_gpt_index_import: bool = ..., custom_path: Optional[str] = ...) -> Type[BaseReader]:
    """
    Download a single loader from the Loader Hub.

    Args:
        loader_class: The name of the loader class you want to download,
            such as `SimpleWebPageReader`.
        refresh_cache: If true, the local cache will be skipped and the
            loader will be fetched directly from the remote repo.
        use_gpt_index_import: If true, the loader files will use
            llama_index as the base dependency. By default (False),
            the loader files use llama_index as the base dependency.
            NOTE: this is a temporary workaround while we fully migrate all usages
            to llama_index.
        custom_path: Custom dirpath to download loader into.

    Returns:
        A Loader.

    """
    ...

