"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

class ImageTabularChartReader(BaseReader):
    """
    Image parser.

    Extract tabular data from a chart or figure.

    """
    def __init__(self, parser_config: Optional[Dict] = ..., keep_image: bool = ..., max_output_tokens=..., prompt: str = ...) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ...) -> List[Document]:
        """Parse file."""
        ...
    


