"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, List, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.graph_stores.types import PropertyGraphStore
from llama_index.core.schema import NodeWithScore, QueryBundle

DEFAULT_PREAMBLE = ...
class BasePGRetriever(BaseRetriever):
    """
    The base class for property graph retrievers.

    By default, will retrieve nodes from the graph store and add source text to the nodes if needed.

    Args:
        graph_store (PropertyGraphStore):
            The graph store to retrieve data from.
        include_text (bool, optional):
            Whether to include source text in the retrieved nodes. Defaults to True.
        include_text_preamble (Optional[str], optional):
            The preamble to include before the source text. Defaults to DEFAULT_PREAMBLE.

    """
    def __init__(self, graph_store: PropertyGraphStore, include_text: bool = ..., include_text_preamble: Optional[str] = ..., include_properties: bool = ..., **kwargs: Any) -> None:
        ...
    
    def add_source_text(self, nodes: List[NodeWithScore]) -> List[NodeWithScore]:
        """Combine retrieved nodes/triplets with their source text."""
        ...
    
    async def async_add_source_text(self, nodes: List[NodeWithScore]) -> List[NodeWithScore]:
        """Combine retrieved nodes/triplets with their source text."""
        ...
    
    @abstractmethod
    def retrieve_from_graph(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes from the labelled property graph."""
        ...
    
    @abstractmethod
    async def aretrieve_from_graph(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes from the labelled property graph."""
        ...
    


