"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Type
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.graph_stores.types import PropertyGraphStore
from llama_index.core.indices.property_graph.sub_retrievers.base import BasePGRetriever
from llama_index.core.llms import LLM
from llama_index.core.schema import NodeWithScore, QueryBundle

class CypherTemplateRetriever(BasePGRetriever):
    """
    A Cypher retriever that fills in params for a cypher query using an LLM.

    Args:
        graph_store (PropertyGraphStore):
            The graph store to retrieve data from.
        output_cls (Type[BaseModel]):
            The output class to use for the LLM.
            Should contain the params needed for the cypher query.
        cypher_query (str):
            The cypher query to use, with templated params.
        llm (Optional[LLM], optional):
            The language model to use. Defaults to Settings.llm.

    """
    def __init__(self, graph_store: PropertyGraphStore, output_cls: Type[BaseModel], cypher_query: str, llm: Optional[LLM] = ..., **kwargs: Any) -> None:
        ...
    
    def retrieve_from_graph(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    async def aretrieve_from_graph(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    


