"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.indices.property_graph.sub_retrievers.base import BasePGRetriever
from llama_index.core.graph_stores.types import PropertyGraphStore
from llama_index.core.schema import NodeWithScore, QueryBundle
from llama_index.core.vector_stores.types import BasePydanticVectorStore, MetadataFilters

class VectorContextRetriever(BasePGRetriever):
    """
    A retriever that uses a vector store to retrieve nodes based on a query.

    Args:
        graph_store (PropertyGraphStore):
            The graph store to retrieve data from.
        include_text (bool, optional):
            Whether to include source text in the retrieved nodes. Defaults to True.
        embed_model (Optional[BaseEmbedding], optional):
            The embedding model to use. Defaults to Settings.embed_model.
        vector_store (Optional[BasePydanticVectorStore], optional):
            The vector store to use. Defaults to None.
            Should be supplied if the graph store does not support vector queries.
        similarity_top_k (int, optional):
            The number of top similar kg nodes to retrieve. Defaults to 4.
        path_depth (int, optional):
            The depth of the path to retrieve for each node. Defaults to 1 (i.e. a triple).
        similarity_score (float, optional):
            The minimum similarity score to retrieve the nodes. Defaults to None.

    """
    def __init__(self, graph_store: PropertyGraphStore, include_text: bool = ..., include_properties: bool = ..., embed_model: Optional[BaseEmbedding] = ..., vector_store: Optional[BasePydanticVectorStore] = ..., similarity_top_k: int = ..., path_depth: int = ..., limit: int = ..., similarity_score: Optional[float] = ..., filters: Optional[MetadataFilters] = ..., **kwargs: Any) -> None:
        ...
    
    def retrieve_from_graph(self, query_bundle: QueryBundle, limit: Optional[int] = ...) -> List[NodeWithScore]:
        ...
    
    async def aretrieve_from_graph(self, query_bundle: QueryBundle, limit: Optional[int] = ...) -> List[NodeWithScore]:
        ...
    


