{
 "title": "Main Dashboard",
 "time": { "from": "2026-03-07T10:55:30.000Z", "to": "2026-03-07T16:55:30.000Z" },
 "panels": [
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "services.api", "text": "API", "type": "string" },
      { "selector": "services.qdrant", "text": "Qdrant", "type": "string" },
      { "selector": "services.minio", "text": "MinIO", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/health",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"backend\"} | json | __error__!=\"JSONParserErr\""
    }
   ]
  },
  {
   "title": "API Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({container=\"backend\"} | json [1m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(levelname) (count_over_time({container=\"backend\"} | json | levelname=\"ERROR\" [5m]))"
    }
   ]
  }
 ]
}