"""
This type stub file was generated by pyright.
"""

from abc import ABC
from contextlib import contextmanager
from typing import Any, Dict, Generator, List, Optional, Type
from llama_index.core.callbacks.base_handler import BaseCallbackHandler
from llama_index.core.callbacks.schema import CBEventType
from llama_index.core.bridge.pydantic import GetCoreSchemaHandler, GetJsonSchemaHandler
from llama_index.core.bridge.pydantic_core import CoreSchema

logger = ...
global_stack_trace = ...
empty_trace_ids: List[str] = ...
global_stack_trace_ids = ...
class CallbackManager(BaseCallbackHandler, ABC):
    """
    Callback manager that handles callbacks for events within LlamaIndex.

    The callback manager provides a way to call handlers on event starts/ends.

    Additionally, the callback manager traces the current stack of events.
    It does this by using a few key attributes.
    - trace_stack - The current stack of events that have not ended yet.
                    When an event ends, it's removed from the stack.
                    Since this is a contextvar, it is unique to each
                    thread/task.
    - trace_map - A mapping of event ids to their children events.
                  On the start of events, the bottom of the trace stack
                  is used as the current parent event for the trace map.
    - trace_id - A simple name for the current trace, usually denoting the
                 entrypoint (query, index_construction, insert, etc.)

    Args:
        handlers (List[BaseCallbackHandler]): list of handlers to use.

    Usage:
        with callback_manager.event(CBEventType.QUERY) as event:
            event.on_start(payload={key, val})
            ...
            event.on_end(payload={key, val})

    """
    def __init__(self, handlers: Optional[List[BaseCallbackHandler]] = ...) -> None:
        """Initialize the manager with a list of handlers."""
        ...
    
    def on_event_start(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: Optional[str] = ..., parent_id: Optional[str] = ..., **kwargs: Any) -> str:
        """Run handlers when an event starts and return id of event."""
        ...
    
    def on_event_end(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: Optional[str] = ..., **kwargs: Any) -> None:
        """Run handlers when an event ends."""
        ...
    
    def add_handler(self, handler: BaseCallbackHandler) -> None:
        """Add a handler to the callback manager."""
        ...
    
    def remove_handler(self, handler: BaseCallbackHandler) -> None:
        """Remove a handler from the callback manager."""
        ...
    
    def set_handlers(self, handlers: List[BaseCallbackHandler]) -> None:
        """Set handlers as the only handlers on the callback manager."""
        ...
    
    @contextmanager
    def event(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: Optional[str] = ...) -> Generator[EventContext, None, None]:
        """
        Context manager for lanching and shutdown of events.

        Handles sending on_evnt_start and on_event_end to handlers for specified event.

        Usage:
            with callback_manager.event(CBEventType.QUERY, payload={key, val}) as event:
                ...
                event.on_end(payload={key, val})  # optional
        """
        ...
    
    @contextmanager
    def as_trace(self, trace_id: str) -> Generator[None, None, None]:
        """Context manager tracer for lanching and shutdown of traces."""
        ...
    
    def start_trace(self, trace_id: Optional[str] = ...) -> None:
        """Run when an overall trace is launched."""
        ...
    
    def end_trace(self, trace_id: Optional[str] = ..., trace_map: Optional[Dict[str, List[str]]] = ...) -> None:
        """Run when an overall trace is exited."""
        ...
    
    @property
    def trace_map(self) -> Dict[str, List[str]]:
        ...
    
    @classmethod
    def __get_pydantic_core_schema__(cls, source: Type[Any], handler: GetCoreSchemaHandler) -> CoreSchema:
        ...
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: CoreSchema, handler: GetJsonSchemaHandler) -> Dict[str, Any]:
        ...
    


class EventContext:
    """
    Simple wrapper to call callbacks on event starts and ends
    with an event type and id.
    """
    def __init__(self, callback_manager: CallbackManager, event_type: CBEventType, event_id: Optional[str] = ...) -> None:
        ...
    
    def on_start(self, payload: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None:
        ...
    
    def on_end(self, payload: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None:
        ...
    


