"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.callbacks.base_handler import BaseCallbackHandler

def set_global_handler(eval_mode: str, **eval_params: Any) -> None:
    """Set global eval handlers."""
    ...

def create_global_handler(eval_mode: str, **eval_params: Any) -> Optional[BaseCallbackHandler]:
    """Get global eval handler."""
    ...

