"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Dict, List, Optional
from llama_index.core.callbacks.pythonically_printing_base_handler import PythonicallyPrintingBaseHandler
from llama_index.core.callbacks.schema import CBEventType

class SimpleLLMHandler(PythonicallyPrintingBaseHandler):
    """Callback handler for printing llms inputs/outputs."""
    def __init__(self, logger: Optional[logging.Logger] = ...) -> None:
        ...
    
    def start_trace(self, trace_id: Optional[str] = ...) -> None:
        ...
    
    def end_trace(self, trace_id: Optional[str] = ..., trace_map: Optional[Dict[str, List[str]]] = ...) -> None:
        ...
    
    def on_event_start(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., parent_id: str = ..., **kwargs: Any) -> str:
        ...
    
    def on_event_end(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., **kwargs: Any) -> None:
        """Count the LLM or Embedding tokens as needed."""
        ...
    


