"""
This type stub file was generated by pyright.
"""

import logging
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, TYPE_CHECKING, Tuple, Union
from llama_index.core.callbacks.pythonically_printing_base_handler import PythonicallyPrintingBaseHandler
from llama_index.core.callbacks.schema import CBEventType
from llama_index.core.utilities.token_counting import TokenCounter
from llama_index.core.llms import ChatResponse, CompletionResponse

if TYPE_CHECKING:
    ...
@dataclass
class TokenCountingEvent:
    prompt: str
    completion: str
    completion_token_count: int
    prompt_token_count: int
    total_token_count: int = ...
    event_id: str = ...
    def __post_init__(self) -> None:
        ...
    


def get_tokens_from_response(response: Union[CompletionResponse, ChatResponse]) -> Tuple[int, int]:
    """Get the token counts from a raw response."""
    ...

def get_llm_token_counts(token_counter: TokenCounter, payload: Dict[str, Any], event_id: str = ...) -> TokenCountingEvent:
    ...

class TokenCountingHandler(PythonicallyPrintingBaseHandler):
    """
    Callback handler for counting tokens in LLM and Embedding events.

    Args:
        tokenizer:
            Tokenizer to use. Defaults to the global tokenizer
            (see llama_index.core.utils.globals_helper).
        event_starts_to_ignore: List of event types to ignore at the start of a trace.
        event_ends_to_ignore: List of event types to ignore at the end of a trace.

    """
    def __init__(self, tokenizer: Optional[Callable[[str], List]] = ..., event_starts_to_ignore: Optional[List[CBEventType]] = ..., event_ends_to_ignore: Optional[List[CBEventType]] = ..., verbose: bool = ..., logger: Optional[logging.Logger] = ...) -> None:
        ...
    
    def start_trace(self, trace_id: Optional[str] = ...) -> None:
        ...
    
    def end_trace(self, trace_id: Optional[str] = ..., trace_map: Optional[Dict[str, List[str]]] = ...) -> None:
        ...
    
    def on_event_start(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., parent_id: str = ..., **kwargs: Any) -> str:
        ...
    
    def on_event_end(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., **kwargs: Any) -> None:
        """Count the LLM or Embedding tokens as needed."""
        ...
    
    @property
    def total_llm_token_count(self) -> int:
        """Get the current total LLM token count."""
        ...
    
    @property
    def prompt_llm_token_count(self) -> int:
        """Get the current total LLM prompt token count."""
        ...
    
    @property
    def completion_llm_token_count(self) -> int:
        """Get the current total LLM completion token count."""
        ...
    
    @property
    def total_embedding_token_count(self) -> int:
        """Get the current total Embedding token count."""
        ...
    
    def reset_counts(self) -> None:
        """Reset the token counts."""
        ...
    


