"""
This type stub file was generated by pyright.
"""

from typing import Callable

logger = ...
def trace_method(trace_id: str, callback_manager_attr: str = ...) -> Callable[[Callable], Callable]:
    """
    Decorator to trace a method.

    Example:
        @trace_method("my_trace_id")
        def my_method(self):
            pass

    Assumes that the self instance has a CallbackManager instance in an attribute
    named `callback_manager`.
    This can be overridden by passing in a `callback_manager_attr` keyword argument.

    """
    ...

