"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional, Union
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""Read PDF files using PyMuPDF library."""
class PyMuPDFReader(BaseReader):
    """Read PDF files using PyMuPDF library."""
    def load_data(self, file_path: Union[Path, str], metadata: bool = ..., extra_info: Optional[Dict] = ...) -> List[Document]:
        """Loads list of documents from PDF file and also accepts extra information in dict format."""
        ...
    
    def load(self, file_path: Union[Path, str], metadata: bool = ..., extra_info: Optional[Dict] = ...) -> List[Document]:
        """
        Loads list of documents from PDF file and also accepts extra information in dict format.

        Args:
            file_path (Union[Path, str]): file path of PDF file (accepts string or Path).
            metadata (bool, optional): if metadata to be included or not. Defaults to True.
            extra_info (Optional[Dict], optional): extra information related to each document in dict format. Defaults to None.

        Raises:
            TypeError: if extra_info is not a dictionary.
            TypeError: if file_path is not a string or Path.

        Returns:
            List[Document]: list of documents.

        """
        ...
    


