"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Paged CSV reader.

A parser for tabular data files.

"""
class PagedCSVReader(BaseReader):
    """
    Paged CSV parser.

    Displayed each row in an LLM-friendly format on a separate document.

    Args:
        encoding (str): Encoding used to open the file.
            utf-8 by default.

    """
    def __init__(self, *args: Any, encoding: str = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., delimiter: str = ..., quotechar: str = ...) -> List[Document]:
        """Parse file."""
        ...
    


