"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.data_structs.data_structs import MultiModelIndexDict
from llama_index.core.embeddings.multi_modal_base import MultiModalEmbedding
from llama_index.core.embeddings.utils import EmbedType
from llama_index.core.indices.multi_modal.retriever import MultiModalVectorIndexRetriever
from llama_index.core.indices.vector_store.base import VectorStoreIndex
from llama_index.core.llms.utils import LLMType
from llama_index.core.query_engine.multi_modal import SimpleMultiModalQueryEngine
from llama_index.core.schema import BaseNode
from llama_index.core.storage.storage_context import StorageContext
from llama_index.core.vector_stores.types import BasePydanticVectorStore

"""
Multi Modal Vector Store Index.

An index that is built on top of multiple vector stores for different modalities.

"""
logger = ...
class MultiModalVectorStoreIndex(VectorStoreIndex):
    """
    Multi-Modal Vector Store Index.

    Args:
        use_async (bool): Whether to use asynchronous calls. Defaults to False.
        show_progress (bool): Whether to show tqdm progress bars. Defaults to False.
        store_nodes_override (bool): set to True to always store Node objects in index
            store and document store even if vector store keeps text. Defaults to False

    """
    image_namespace = ...
    index_struct_cls = MultiModelIndexDict
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., index_struct: Optional[MultiModelIndexDict] = ..., embed_model: Optional[BaseEmbedding] = ..., storage_context: Optional[StorageContext] = ..., use_async: bool = ..., store_nodes_override: bool = ..., show_progress: bool = ..., image_vector_store: Optional[BasePydanticVectorStore] = ..., image_embed_model: EmbedType = ..., is_image_to_text: bool = ..., is_image_vector_store_empty: bool = ..., is_text_vector_store_empty: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def image_vector_store(self) -> BasePydanticVectorStore:
        ...
    
    @property
    def image_embed_model(self) -> MultiModalEmbedding:
        ...
    
    @property
    def is_image_vector_store_empty(self) -> bool:
        ...
    
    @property
    def is_text_vector_store_empty(self) -> bool:
        ...
    
    def as_retriever(self, **kwargs: Any) -> MultiModalVectorIndexRetriever:
        ...
    
    def as_query_engine(self, llm: Optional[LLMType] = ..., **kwargs: Any) -> SimpleMultiModalQueryEngine:
        ...
    
    @classmethod
    def from_vector_store(cls, vector_store: BasePydanticVectorStore, embed_model: Optional[EmbedType] = ..., image_vector_store: Optional[BasePydanticVectorStore] = ..., image_embed_model: EmbedType = ..., **kwargs: Any) -> MultiModalVectorStoreIndex:
        ...
    
    def delete_ref_doc(self, ref_doc_id: str, delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """Delete a document and it's nodes by using ref_doc_id."""
        ...
    


