"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import List, Optional, Sequence
from llama_index.core.agent.react.types import BaseReasoningStep
from llama_index.core.base.llms.types import ChatMessage, MessageRole
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.tools import BaseTool

logger = ...
def get_react_tool_descriptions(tools: Sequence[BaseTool]) -> List[str]:
    """Tool."""
    ...

class BaseAgentChatFormatter(BaseModel):
    """Base chat formatter."""
    model_config = ...
    @abstractmethod
    def format(self, tools: Sequence[BaseTool], chat_history: List[ChatMessage], current_reasoning: Optional[List[BaseReasoningStep]] = ...) -> List[ChatMessage]:
        """Format chat history into list of ChatMessage."""
        ...
    


class ReActChatFormatter(BaseAgentChatFormatter):
    """ReAct chat formatter."""
    system_header: str = ...
    context: str = ...
    observation_role: MessageRole = ...
    def format(self, tools: Sequence[BaseTool], chat_history: List[ChatMessage], current_reasoning: Optional[List[BaseReasoningStep]] = ...) -> List[ChatMessage]:
        """Format chat history into list of ChatMessage."""
        ...
    
    @classmethod
    def from_defaults(cls, system_header: Optional[str] = ..., context: Optional[str] = ..., observation_role: MessageRole = ...) -> ReActChatFormatter:
        """Create ReActChatFormatter from defaults."""
        ...
    
    @classmethod
    def from_context(cls, context: str) -> ReActChatFormatter:
        """
        Create ReActChatFormatter from context.

        NOTE: deprecated

        """
        ...
    


