"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional, TYPE_CHECKING
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

if TYPE_CHECKING:
    ...
class HTMLTagReader(BaseReader):
    """
    Read HTML files and extract text from a specific tag with BeautifulSoup.

    By default, reads the text from the ``<section>`` tag.
    """
    def __init__(self, tag: str = ..., ignore_no_id: bool = ...) -> None:
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ...) -> List[Document]:
        ...
    


