"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, Tuple
from llama_index.core.vector_stores.types import VectorStoreQueryMode

"""Embedding utils for queries."""
def get_top_k_embeddings(query_embedding: List[float], embeddings: List[List[float]], similarity_fn: Optional[Callable[..., float]] = ..., similarity_top_k: Optional[int] = ..., embedding_ids: Optional[List] = ..., similarity_cutoff: Optional[float] = ...) -> Tuple[List[float], List]:
    """Get top nodes by similarity to the query."""
    ...

def get_top_k_embeddings_learner(query_embedding: List[float], embeddings: List[List[float]], similarity_top_k: Optional[int] = ..., embedding_ids: Optional[List] = ..., query_mode: VectorStoreQueryMode = ...) -> Tuple[List[float], List]:
    """
    Get top embeddings by fitting a learner against query.

    Inspired by Karpathy's SVM demo:
    https://github.com/karpathy/randomfun/blob/master/knn_vs_svm.ipynb

    Can fit SVM, linear regression, and more.

    """
    ...

def get_top_k_mmr_embeddings(query_embedding: List[float], embeddings: List[List[float]], similarity_fn: Optional[Callable[..., float]] = ..., similarity_top_k: Optional[int] = ..., embedding_ids: Optional[List] = ..., similarity_cutoff: Optional[float] = ..., mmr_threshold: Optional[float] = ...) -> Tuple[List[float], List]:
    """
    Get top nodes by similarity to the query,
    discount by their similarity to previous results.

    A mmr_threshold of 0 will strongly avoid similarity to previous results.
    A mmr_threshold of 1 will check similarity the query and ignore previous results.

    """
    ...

