"""
This type stub file was generated by pyright.
"""

import fsspec
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence
from dataclasses_json import DataClassJsonMixin
from llama_index.core.schema import BaseNode
from llama_index.core.vector_stores.types import BasePydanticVectorStore, MetadataFilters, VectorStoreQuery, VectorStoreQueryResult

"""Simple vector store index."""
logger = ...
LEARNER_MODES = ...
MMR_MODE = ...
NAMESPACE_SEP = ...
DEFAULT_VECTOR_STORE = ...
@dataclass
class SimpleVectorStoreData(DataClassJsonMixin):
    """
    Simple Vector Store Data container.

    Args:
        embedding_dict (Optional[dict]): dict mapping node_ids to embeddings.
        text_id_to_ref_doc_id (Optional[dict]):
            dict mapping text_ids/node_ids to ref_doc_ids.

    """
    embedding_dict: Dict[str, List[float]] = ...
    text_id_to_ref_doc_id: Dict[str, str] = ...
    metadata_dict: Dict[str, Any] = ...


class SimpleVectorStore(BasePydanticVectorStore):
    """
    Simple Vector Store.

    In this vector store, embeddings are stored within a simple, in-memory dictionary.

    Args:
        simple_vector_store_data_dict (Optional[dict]): data dict
            containing the embeddings and doc_ids. See SimpleVectorStoreData
            for more details.

    """
    stores_text: bool = ...
    data: SimpleVectorStoreData = ...
    _fs: fsspec.AbstractFileSystem = ...
    def __init__(self, data: Optional[SimpleVectorStoreData] = ..., fs: Optional[fsspec.AbstractFileSystem] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., namespace: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleVectorStore:
        """Load from persist dir."""
        ...
    
    @classmethod
    def from_namespaced_persist_dir(cls, persist_dir: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> Dict[str, BasePydanticVectorStore]:
        """Load from namespaced persist dir."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        """Class name."""
        ...
    
    @property
    def client(self) -> None:
        """Get client."""
        ...
    
    def get(self, text_id: str) -> List[float]:
        """Get embedding."""
        ...
    
    def get_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ...) -> List[BaseNode]:
        """Get nodes."""
        ...
    
    def add(self, nodes: Sequence[BaseNode], **add_kwargs: Any) -> List[str]:
        """Add nodes to index."""
        ...
    
    def delete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id.

        Args:
            ref_doc_id (str): The doc_id of the document to delete.

        """
        ...
    
    def delete_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., **delete_kwargs: Any) -> None:
        ...
    
    def clear(self) -> None:
        """Clear the store."""
        ...
    
    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """Get nodes for response."""
        ...
    
    def persist(self, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the SimpleVectorStore to a directory."""
        ...
    
    @classmethod
    def from_persist_path(cls, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleVectorStore:
        """Create a SimpleKVStore from a persist directory."""
        ...
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any], **kwargs: Any) -> SimpleVectorStore:
        ...
    
    def to_dict(self, **kwargs: Any) -> Dict[str, Any]:
        ...
    


