"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Mapping, Optional, Tuple
from llama_index.core.schema import BaseNode
from llama_index.core.vector_stores.types import MetadataFilters

DEFAULT_TEXT_KEY = ...
DEFAULT_TEXT_RESOURCE_KEY = ...
DEFAULT_EMBEDDING_KEY = ...
DEFAULT_DOC_ID_KEY = ...
def node_to_metadata_dict(node: BaseNode, remove_text: bool = ..., text_field: str = ..., text_resource_field: str = ..., flat_metadata: bool = ...) -> Dict[str, Any]:
    """Common logic for saving Node data into metadata dict."""
    ...

def metadata_dict_to_node(metadata: dict, text: Optional[str] = ...) -> BaseNode:
    """Common logic for loading Node data from metadata dict."""
    ...

def build_metadata_filter_fn(metadata_lookup_fn: Callable[[str], Mapping[str, Any]], metadata_filters: Optional[MetadataFilters] = ...) -> Callable[[str], bool]:
    """Build metadata filter function."""
    ...

def legacy_metadata_dict_to_node(metadata: dict, text_key: str = ...) -> Tuple[dict, dict, dict]:
    """Common logic for loading Node data from metadata dict."""
    ...

