"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Sequence
from llama_index.core.schema import BaseNode
from llama_index.core.storage.docstore.types import BaseDocumentStore, RefDocInfo
from llama_index.core.storage.kvstore.types import BaseKVStore

"""Document store."""
DEFAULT_NAMESPACE = ...
DEFAULT_COLLECTION_DATA_SUFFIX = ...
DEFAULT_REF_DOC_COLLECTION_SUFFIX = ...
DEFAULT_METADATA_COLLECTION_SUFFIX = ...
class KVDocumentStore(BaseDocumentStore):
    """
    Document (Node) store.

    NOTE: at the moment, this store is primarily used to store Node objects.
    Each node will be assigned an ID.

    The same docstore can be reused across index structures. This
    allows you to reuse the same storage for multiple index structures;
    otherwise, each index would create a docstore under the hood.

    .. code-block:: python
        nodes = SentenceSplitter().get_nodes_from_documents()
        docstore = SimpleDocumentStore()
        docstore.add_documents(nodes)
        storage_context = StorageContext.from_defaults(docstore=docstore)

        summary_index = SummaryIndex(nodes, storage_context=storage_context)
        vector_index = VectorStoreIndex(nodes, storage_context=storage_context)
        keyword_table_index = SimpleKeywordTableIndex(nodes, storage_context=storage_context)

    This will use the same docstore for multiple index structures.

    Args:
        kvstore (BaseKVStore): key-value store
        namespace (str): namespace for the docstore

    """
    def __init__(self, kvstore: BaseKVStore, namespace: Optional[str] = ..., batch_size: int = ..., node_collection_suffix: Optional[str] = ..., ref_doc_collection_suffix: Optional[str] = ..., metadata_collection_suffix: Optional[str] = ...) -> None:
        """Init a KVDocumentStore."""
        ...
    
    @property
    def docs(self) -> Dict[str, BaseNode]:
        """
        Get all documents.

        Returns:
            Dict[str, BaseDocument]: documents

        """
        ...
    
    def add_documents(self, docs: Sequence[BaseNode], allow_update: bool = ..., batch_size: Optional[int] = ..., store_text: bool = ...) -> None:
        """
        Add a document to the store.

        Args:
            docs (List[BaseDocument]): documents
            allow_update (bool): allow update of docstore from document

        """
        ...
    
    async def async_add_documents(self, docs: Sequence[BaseNode], allow_update: bool = ..., batch_size: Optional[int] = ..., store_text: bool = ...) -> None:
        """
        Add a document to the store.

        Args:
            docs (List[BaseDocument]): documents
            allow_update (bool): allow update of docstore from document

        """
        ...
    
    def get_document(self, doc_id: str, raise_error: bool = ...) -> Optional[BaseNode]:
        """
        Get a document from the store.

        Args:
            doc_id (str): document id
            raise_error (bool): raise error if doc_id not found

        """
        ...
    
    async def aget_document(self, doc_id: str, raise_error: bool = ...) -> Optional[BaseNode]:
        """
        Get a document from the store.

        Args:
            doc_id (str): document id
            raise_error (bool): raise error if doc_id not found

        """
        ...
    
    def get_ref_doc_info(self, ref_doc_id: str) -> Optional[RefDocInfo]:
        """Get the RefDocInfo for a given ref_doc_id."""
        ...
    
    async def aget_ref_doc_info(self, ref_doc_id: str) -> Optional[RefDocInfo]:
        """Get the RefDocInfo for a given ref_doc_id."""
        ...
    
    def get_all_ref_doc_info(self) -> Optional[Dict[str, RefDocInfo]]:
        """Get a mapping of ref_doc_id -> RefDocInfo for all ingested documents."""
        ...
    
    async def aget_all_ref_doc_info(self) -> Optional[Dict[str, RefDocInfo]]:
        """Get a mapping of ref_doc_id -> RefDocInfo for all ingested documents."""
        ...
    
    def ref_doc_exists(self, ref_doc_id: str) -> bool:
        """Check if a ref_doc_id has been ingested."""
        ...
    
    async def aref_doc_exists(self, ref_doc_id: str) -> bool:
        """Check if a ref_doc_id has been ingested."""
        ...
    
    def document_exists(self, doc_id: str) -> bool:
        """Check if document exists."""
        ...
    
    async def adocument_exists(self, doc_id: str) -> bool:
        """Check if document exists."""
        ...
    
    def delete_document(self, doc_id: str, raise_error: bool = ...) -> None:
        """Delete a document from the store."""
        ...
    
    async def adelete_document(self, doc_id: str, raise_error: bool = ...) -> None:
        """Delete a document from the store."""
        ...
    
    def delete_ref_doc(self, ref_doc_id: str, raise_error: bool = ...) -> None:
        """Delete a ref_doc and all it's associated nodes."""
        ...
    
    async def adelete_ref_doc(self, ref_doc_id: str, raise_error: bool = ...) -> None:
        """Delete a ref_doc and all it's associated nodes."""
        ...
    
    def set_document_hash(self, doc_id: str, doc_hash: str) -> None:
        """Set the hash for a given doc_id."""
        ...
    
    def set_document_hashes(self, doc_hashes: Dict[str, str]) -> None:
        """Set the hash for a given doc_id."""
        ...
    
    async def aset_document_hash(self, doc_id: str, doc_hash: str) -> None:
        """Set the hash for a given doc_id."""
        ...
    
    async def aset_document_hashes(self, doc_hashes: Dict[str, str]) -> None:
        """Set the hash for a given doc_id."""
        ...
    
    def get_document_hash(self, doc_id: str) -> Optional[str]:
        """Get the stored hash for a document, if it exists."""
        ...
    
    async def aget_document_hash(self, doc_id: str) -> Optional[str]:
        """Get the stored hash for a document, if it exists."""
        ...
    
    def get_all_document_hashes(self) -> Dict[str, str]:
        """Get the stored hash for all documents."""
        ...
    
    async def aget_all_document_hashes(self) -> Dict[str, str]:
        """Get the stored hash for all documents."""
        ...
    


