"""
This type stub file was generated by pyright.
"""

from typing import Optional
from llama_index.core.base.base_selector import BaseSelector
from llama_index.core.llms import LLM
from llama_index.core.selectors.prompts import MultiSelectPrompt, SingleSelectPrompt
from llama_index.core.types import BaseOutputParser

class LLMSingleSelector(BaseSelector):
    """
    LLM single selector.

    LLM-based selector that chooses one out of many options.

    Args:
        LLM (LLM): An LLM.
        prompt (SingleSelectPrompt): A LLM prompt for selecting one out of many options.

    """
    def __init__(self, llm: LLM, prompt: SingleSelectPrompt) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, llm: Optional[LLM] = ..., prompt_template_str: Optional[str] = ..., output_parser: Optional[BaseOutputParser] = ...) -> LLMSingleSelector:
        ...
    


class LLMMultiSelector(BaseSelector):
    """
    LLM multi selector.

    LLM-based selector that chooses multiple out of many options.

    Args:
        llm (LLM): An LLM.
        prompt (SingleSelectPrompt): A LLM prompt for selecting multiple out of many
            options.

    """
    def __init__(self, llm: LLM, prompt: MultiSelectPrompt, max_outputs: Optional[int] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, llm: Optional[LLM] = ..., prompt_template_str: Optional[str] = ..., output_parser: Optional[BaseOutputParser] = ..., max_outputs: Optional[int] = ...) -> LLMMultiSelector:
        ...
    


