"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING
from llama_index.core.base.base_selector import BaseSelector
from llama_index.core.types import BasePydanticProgram
from llama_index.llms.openai import OpenAI

if TYPE_CHECKING:
    ...
class PydanticSingleSelector(BaseSelector):
    def __init__(self, selector_program: BasePydanticProgram) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, program: Optional[BasePydanticProgram] = ..., llm: Optional[OpenAI] = ..., prompt_template_str: str = ..., verbose: bool = ...) -> PydanticSingleSelector:
        ...
    


class PydanticMultiSelector(BaseSelector):
    def __init__(self, selector_program: BasePydanticProgram, max_outputs: Optional[int] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, program: Optional[BasePydanticProgram] = ..., llm: Optional[OpenAI] = ..., prompt_template_str: str = ..., max_outputs: Optional[int] = ..., verbose: bool = ...) -> PydanticMultiSelector:
        ...
    


