"""
This type stub file was generated by pyright.
"""

from llama_index.core.base.base_selector import BaseSelector
from llama_index.core.llms.llm import LLM

def get_selector_from_llm(llm: LLM, is_multi: bool = ...) -> BaseSelector:
    """Get a selector from a service context. Prefers Pydantic selectors if possible."""
    ...

