"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Generic, List, Optional, Sequence, Type, TypeVar
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.chat_engine.types import BaseChatEngine, ChatMode
from llama_index.core.data_structs.data_structs import IndexStruct
from llama_index.core.llms.utils import LLMType
from llama_index.core.schema import BaseNode, Document, IndexNode, TransformComponent
from llama_index.core.storage.docstore.types import BaseDocumentStore, RefDocInfo
from llama_index.core.storage.storage_context import StorageContext

"""Base index classes."""
IS = TypeVar("IS", bound=IndexStruct)
IndexType = TypeVar("IndexType", bound="BaseIndex")
logger = ...
class BaseIndex(Generic[IS], ABC):
    """
    Base LlamaIndex.

    Args:
        nodes (List[Node]): List of nodes to index
        show_progress (bool): Whether to show tqdm progress bars. Defaults to False.

    """
    index_struct_cls: Type[IS]
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., objects: Optional[Sequence[IndexNode]] = ..., index_struct: Optional[IS] = ..., storage_context: Optional[StorageContext] = ..., callback_manager: Optional[CallbackManager] = ..., transformations: Optional[List[TransformComponent]] = ..., show_progress: bool = ..., **kwargs: Any) -> None:
        """Initialize with parameters."""
        ...
    
    @classmethod
    def from_documents(cls: Type[IndexType], documents: Sequence[Document], storage_context: Optional[StorageContext] = ..., show_progress: bool = ..., callback_manager: Optional[CallbackManager] = ..., transformations: Optional[List[TransformComponent]] = ..., **kwargs: Any) -> IndexType:
        """
        Create index from documents.

        Args:
            documents (Sequence[Document]]): List of documents to
                build the index from.

        """
        ...
    
    @property
    def index_struct(self) -> IS:
        """Get the index struct."""
        ...
    
    @property
    def index_id(self) -> str:
        """Get the index struct."""
        ...
    
    def set_index_id(self, index_id: str) -> None:
        """
        Set the index id.

        NOTE: if you decide to set the index_id on the index_struct manually,
        you will need to explicitly call `add_index_struct` on the `index_store`
        to update the index store.

        Args:
            index_id (str): Index id to set.

        """
        ...
    
    @property
    def docstore(self) -> BaseDocumentStore:
        """Get the docstore corresponding to the index."""
        ...
    
    @property
    def storage_context(self) -> StorageContext:
        ...
    
    @property
    def summary(self) -> str:
        ...
    
    @summary.setter
    def summary(self, new_summary: str) -> None:
        ...
    
    def build_index_from_nodes(self, nodes: Sequence[BaseNode], **build_kwargs: Any) -> IS:
        """Build the index from nodes."""
        ...
    
    def insert_nodes(self, nodes: Sequence[BaseNode], **insert_kwargs: Any) -> None:
        """Insert nodes."""
        ...
    
    async def ainsert_nodes(self, nodes: Sequence[BaseNode], **insert_kwargs: Any) -> None:
        """Asynchronously insert nodes."""
        ...
    
    def insert(self, document: Document, **insert_kwargs: Any) -> None:
        """Insert a document."""
        ...
    
    async def ainsert(self, document: Document, **insert_kwargs: Any) -> None:
        """Asynchronously insert a document."""
        ...
    
    def delete_nodes(self, node_ids: List[str], delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """
        Delete a list of nodes from the index.

        Args:
            doc_ids (List[str]): A list of doc_ids from the nodes to delete

        """
        ...
    
    async def adelete_nodes(self, node_ids: List[str], delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """
        Asynchronously delete a list of nodes from the index.

        Args:
            doc_ids (List[str]): A list of doc_ids from the nodes to delete

        """
        ...
    
    def delete(self, doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete a document from the index.
        All nodes in the index related to the index will be deleted.

        Args:
            doc_id (str): A doc_id of the ingested document

        """
        ...
    
    def delete_ref_doc(self, ref_doc_id: str, delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """Delete a document and it's nodes by using ref_doc_id."""
        ...
    
    async def adelete_ref_doc(self, ref_doc_id: str, delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """Delete a document and it's nodes by using ref_doc_id."""
        ...
    
    def update(self, document: Document, **update_kwargs: Any) -> None:
        """
        Update a document and it's corresponding nodes.

        This is equivalent to deleting the document and then inserting it again.

        Args:
            document (Union[BaseDocument, BaseIndex]): document to update
            insert_kwargs (Dict): kwargs to pass to insert
            delete_kwargs (Dict): kwargs to pass to delete

        """
        ...
    
    def update_ref_doc(self, document: Document, **update_kwargs: Any) -> None:
        """
        Update a document and it's corresponding nodes.

        This is equivalent to deleting the document and then inserting it again.

        Args:
            document (Union[BaseDocument, BaseIndex]): document to update
            insert_kwargs (Dict): kwargs to pass to insert
            delete_kwargs (Dict): kwargs to pass to delete

        """
        ...
    
    async def aupdate_ref_doc(self, document: Document, **update_kwargs: Any) -> None:
        """
        Asynchronously update a document and it's corresponding nodes.

        This is equivalent to deleting the document and then inserting it again.

        Args:
            document (Union[BaseDocument, BaseIndex]): document to update
            insert_kwargs (Dict): kwargs to pass to insert
            delete_kwargs (Dict): kwargs to pass to delete

        """
        ...
    
    def refresh(self, documents: Sequence[Document], **update_kwargs: Any) -> List[bool]:
        """
        Refresh an index with documents that have changed.

        This allows users to save LLM and Embedding model calls, while only
        updating documents that have any changes in text or metadata. It
        will also insert any documents that previously were not stored.
        """
        ...
    
    def refresh_ref_docs(self, documents: Sequence[Document], **update_kwargs: Any) -> List[bool]:
        """
        Refresh an index with documents that have changed.

        This allows users to save LLM and Embedding model calls, while only
        updating documents that have any changes in text or metadata. It
        will also insert any documents that previously were not stored.
        """
        ...
    
    async def arefresh_ref_docs(self, documents: Sequence[Document], **update_kwargs: Any) -> List[bool]:
        """
        Asynchronously refresh an index with documents that have changed.

        This allows users to save LLM and Embedding model calls, while only
        updating documents that have any changes in text or metadata. It
        will also insert any documents that previously were not stored.
        """
        ...
    
    @property
    @abstractmethod
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    
    @abstractmethod
    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        ...
    
    def as_query_engine(self, llm: Optional[LLMType] = ..., **kwargs: Any) -> BaseQueryEngine:
        """
        Convert the index to a query engine.

        Calls `index.as_retriever(**kwargs)` to get the retriever and then wraps it in a
        `RetrieverQueryEngine.from_args(retriever, **kwrags)` call.
        """
        ...
    
    def as_chat_engine(self, chat_mode: ChatMode = ..., llm: Optional[LLMType] = ..., **kwargs: Any) -> BaseChatEngine:
        """
        Convert the index to a chat engine.

        Calls `index.as_query_engine(llm=llm, **kwargs)` to get the query engine and then
        wraps it in a chat engine based on the chat mode.

        Chat modes:
            - `ChatMode.BEST` (default): Chat engine that uses an agent (react or openai) with a query engine tool
            - `ChatMode.CONTEXT`: Chat engine that uses a retriever to get context
            - `ChatMode.CONDENSE_QUESTION`: Chat engine that condenses questions
            - `ChatMode.CONDENSE_PLUS_CONTEXT`: Chat engine that condenses questions and uses a retriever to get context
            - `ChatMode.SIMPLE`: Simple chat engine that uses the LLM directly
            - `ChatMode.REACT`: Chat engine that uses a react agent with a query engine tool
            - `ChatMode.OPENAI`: Chat engine that uses an openai agent with a query engine tool
        """
        ...
    


BaseGPTIndex = BaseIndex
