"""
This type stub file was generated by pyright.
"""

import logging
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.embeddings.multi_modal_base import MultiModalEmbedding
from llama_index.core.schema import BaseNode, ImageNode
from llama_index.core.vector_stores.types import VectorStoreQueryResult
from typing import Dict, List, Optional, Sequence, Set, Tuple

"""Utilities for GPT indices."""
_logger = ...
def get_sorted_node_list(node_dict: Dict[int, BaseNode]) -> List[BaseNode]:
    """Get sorted node list. Used by tree-strutured indices."""
    ...

def extract_numbers_given_response(response: str, n: int = ...) -> Optional[List[int]]:
    """
    Extract number given the GPT-generated response.

    Used by tree-structured indices.

    """
    ...

def expand_tokens_with_subtokens(tokens: Set[str]) -> Set[str]:
    """Get subtokens from a list of tokens., filtering for stopwords."""
    ...

def log_vector_store_query_result(result: VectorStoreQueryResult, logger: Optional[logging.Logger] = ...) -> None:
    """Log vector store query result."""
    ...

def default_format_node_batch_fn(summary_nodes: List[BaseNode]) -> str:
    """
    Default format node batch function.

    Assign each summary node a number, and format the batch of nodes.

    """
    ...

def default_parse_choice_select_answer_fn(answer: str, num_choices: int, raise_error: bool = ...) -> Tuple[List[int], List[float]]:
    """Default parse choice select answer function."""
    ...

def embed_nodes(nodes: Sequence[BaseNode], embed_model: BaseEmbedding, show_progress: bool = ...) -> Dict[str, List[float]]:
    """
    Get embeddings of the given nodes, run embedding model if necessary.

    Args:
        nodes (Sequence[BaseNode]): The nodes to embed.
        embed_model (BaseEmbedding): The embedding model to use.
        show_progress (bool): Whether to show progress bar.

    Returns:
        Dict[str, List[float]]: A map from node id to embedding.

    """
    ...

def embed_image_nodes(nodes: Sequence[ImageNode], embed_model: MultiModalEmbedding, show_progress: bool = ...) -> Dict[str, List[float]]:
    """
    Get image embeddings of the given nodes, run image embedding model if necessary.

    Args:
        nodes (Sequence[ImageNode]): The nodes to embed.
        embed_model (MultiModalEmbedding): The embedding model to use.
        show_progress (bool): Whether to show progress bar.

    Returns:
        Dict[str, List[float]]: A map from node id to embedding.

    """
    ...

async def async_embed_nodes(nodes: Sequence[BaseNode], embed_model: BaseEmbedding, show_progress: bool = ...) -> Dict[str, List[float]]:
    """
    Async get embeddings of the given nodes, run embedding model if necessary.

    Args:
        nodes (Sequence[BaseNode]): The nodes to embed.
        embed_model (BaseEmbedding): The embedding model to use.
        show_progress (bool): Whether to show progress bar.

    Returns:
        Dict[str, List[float]]: A map from node id to embedding.

    """
    ...

async def async_embed_image_nodes(nodes: Sequence[ImageNode], embed_model: MultiModalEmbedding, show_progress: bool = ...) -> Dict[str, List[float]]:
    """
    Get image embeddings of the given nodes, run image embedding model if necessary.

    Args:
        nodes (Sequence[ImageNode]): The nodes to embed.
        embed_model (MultiModalEmbedding): The embedding model to use.
        show_progress (bool): Whether to show progress bar.

    Returns:
        Dict[str, List[float]]: A map from node id to embedding.

    """
    ...

