"""
This type stub file was generated by pyright.
"""

from fsspec import AbstractFileSystem
from typing import Any, Dict, List, Optional, Tuple
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Markdown parser.

Contains parser for md files.

"""
class MarkdownReader(BaseReader):
    """
    Markdown parser.

    Extract text from markdown files.
    Returns dictionary with keys as headers and values as the text between headers.

    """
    def __init__(self, *args: Any, remove_hyperlinks: bool = ..., remove_images: bool = ..., separator: str = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    
    def markdown_to_tups(self, markdown_text: str) -> List[Tuple[Optional[str], str]]:
        """Convert a markdown file to a list of tuples containing header and text."""
        ...
    
    def remove_images(self, content: str) -> str:
        """Remove images in markdown content but keep the description."""
        ...
    
    def remove_hyperlinks(self, content: str) -> str:
        """Remove hyperlinks in markdown content."""
        ...
    
    def parse_tups(self, filepath: str, errors: str = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Tuple[Optional[str], str]]:
        """Parse file into tuples."""
        ...
    
    def load_data(self, file: str, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file into string."""
        ...
    


