"""
This type stub file was generated by pyright.
"""

from llama_index.core.indices.vector_store.base import GPTVectorStoreIndex, VectorStoreIndex
from llama_index.core.indices.vector_store.retrievers import VectorIndexAutoRetriever, VectorIndexRetriever

"""Vector-store based data structures."""
__all__ = ["VectorStoreIndex", "VectorIndexRetriever", "VectorIndexAutoRetriever", "GPTVectorStoreIndex"]
