"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Generic, List, Optional, Sequence, Type, TypeVar
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.indices.base import BaseIndex
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.schema import BaseNode, QueryType

"""Base object types."""
OT = TypeVar("OT")
class ObjectRetriever(Generic[OT]):
    """Object retriever."""
    def __init__(self, retriever: BaseRetriever, object_node_mapping: BaseObjectNodeMapping[OT], node_postprocessors: Optional[List[BaseNodePostprocessor]] = ...) -> None:
        ...
    
    @property
    def retriever(self) -> BaseRetriever:
        """Retriever."""
        ...
    
    @property
    def object_node_mapping(self) -> BaseObjectNodeMapping[OT]:
        """Object node mapping."""
        ...
    
    @property
    def node_postprocessors(self) -> List[BaseNodePostprocessor]:
        """Node postprocessors."""
        ...
    
    def retrieve(self, str_or_query_bundle: QueryType) -> List[OT]:
        ...
    
    async def aretrieve(self, str_or_query_bundle: QueryType) -> List[OT]:
        ...
    


class ObjectIndex(Generic[OT]):
    """Object index."""
    def __init__(self, index: BaseIndex, object_node_mapping: BaseObjectNodeMapping) -> None:
        ...
    
    @property
    def index(self) -> BaseIndex:
        """Index."""
        ...
    
    @property
    def object_node_mapping(self) -> BaseObjectNodeMapping:
        """Object node mapping."""
        ...
    
    @classmethod
    def from_objects(cls, objects: Sequence[OT], object_mapping: Optional[BaseObjectNodeMapping] = ..., from_node_fn: Optional[Callable[[BaseNode], OT]] = ..., to_node_fn: Optional[Callable[[OT], BaseNode]] = ..., index_cls: Type[BaseIndex] = ..., **index_kwargs: Any) -> ObjectIndex:
        ...
    
    @classmethod
    def from_objects_and_index(cls, objects: Sequence[OT], index: BaseIndex, object_mapping: Optional[BaseObjectNodeMapping] = ..., from_node_fn: Optional[Callable[[BaseNode], OT]] = ..., to_node_fn: Optional[Callable[[OT], BaseNode]] = ...) -> ObjectIndex:
        ...
    
    def insert_object(self, obj: Any) -> None:
        ...
    
    def as_retriever(self, node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., **kwargs: Any) -> ObjectRetriever:
        ...
    
    def as_node_retriever(self, **kwargs: Any) -> BaseRetriever:
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., object_node_mapping: Optional[BaseObjectNodeMapping] = ...) -> ObjectIndex:
        ...
    


