"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, Dict, Generic, Optional, Sequence, TypeVar
from llama_index.core.schema import BaseNode, TextNode

"""Base object types."""
DEFAULT_PERSIST_FNAME = ...
OT = TypeVar("OT")
class BaseObjectNodeMapping(Generic[OT]):
    """Base object node mapping."""
    @classmethod
    @abstractmethod
    def from_objects(cls, objs: Sequence[OT], *args: Any, **kwargs: Any) -> BaseObjectNodeMapping:
        """
        Initialize node mapping from a list of objects.

        Only needs to be specified if the node mapping
        needs to be initialized with a list of objects.

        """
        ...
    
    def validate_object(self, obj: OT) -> None:
        """Validate object."""
        ...
    
    def add_object(self, obj: OT) -> None:
        """
        Add object.

        Only needs to be specified if the node mapping
        needs to be initialized with a list of objects.

        """
        ...
    
    @property
    @abstractmethod
    def obj_node_mapping(self) -> Dict[Any, Any]:
        """The mapping data structure between node and object."""
        ...
    
    @abstractmethod
    def to_node(self, obj: OT) -> BaseNode:
        """To node."""
        ...
    
    def to_nodes(self, objs: Sequence[OT]) -> Sequence[BaseNode]:
        ...
    
    def from_node(self, node: BaseNode) -> OT:
        """From node."""
        ...
    
    @abstractmethod
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """Persist objs."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> BaseObjectNodeMapping[OT]:
        """Load from serialization."""
        ...
    


class SimpleObjectNodeMapping(BaseObjectNodeMapping[Any]):
    """
    General node mapping that works for any obj.

    More specifically, any object with a meaningful string representation.

    """
    def __init__(self, objs: Optional[Sequence[Any]] = ...) -> None:
        ...
    
    @classmethod
    def from_objects(cls, objs: Sequence[Any], *args: Any, **kwargs: Any) -> SimpleObjectNodeMapping:
        ...
    
    @property
    def obj_node_mapping(self) -> Dict[int, Any]:
        ...
    
    @obj_node_mapping.setter
    def obj_node_mapping(self, mapping: Dict[int, Any]) -> None:
        ...
    
    def to_node(self, obj: Any) -> TextNode:
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """
        Persist object node mapping.

        NOTE: This may fail depending on whether the object types are
        pickle-able.
        """
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> SimpleObjectNodeMapping:
        ...
    


