"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Sequence
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.schema import BaseNode

"""Table node mapping."""
class FnNodeMapping(BaseObjectNodeMapping[Any]):
    """Fn node mapping."""
    def __init__(self, from_node_fn: Callable[[BaseNode], Any], to_node_fn: Callable[[Any], BaseNode]) -> None:
        ...
    
    @classmethod
    def from_objects(cls, objs: Sequence[Any], from_node_fn: Callable[[BaseNode], Any], to_node_fn: Callable[[Any], BaseNode], *args: Any, **kwargs: Any) -> BaseObjectNodeMapping:
        """Initialize node mapping."""
        ...
    
    def to_node(self, obj: Any) -> BaseNode:
        """To node."""
        ...
    
    @property
    def obj_node_mapping(self) -> Dict[int, Any]:
        """The mapping data structure between node and object."""
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """Persist objs."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> FnNodeMapping:
        ...
    


