"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Sequence
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.schema import TextNode
from llama_index.core.utilities.sql_wrapper import SQLDatabase

"""Table node mapping."""
class SQLTableSchema(BaseModel):
    """Lightweight representation of a SQL table."""
    table_name: str
    context_str: Optional[str] = ...


class SQLTableNodeMapping(BaseObjectNodeMapping[SQLTableSchema]):
    """SQL Table node mapping."""
    def __init__(self, sql_database: SQLDatabase) -> None:
        ...
    
    @classmethod
    def from_objects(cls, objs: Sequence[SQLTableSchema], *args: Any, sql_database: Optional[SQLDatabase] = ..., **kwargs: Any) -> BaseObjectNodeMapping:
        """Initialize node mapping."""
        ...
    
    def to_node(self, obj: SQLTableSchema) -> TextNode:
        """To node."""
        ...
    
    @property
    def obj_node_mapping(self) -> Dict[int, Any]:
        """The mapping data structure between node and object."""
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """Persist objs."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> SQLTableNodeMapping:
        ...
    


