"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Sequence
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.schema import TextNode
from llama_index.core.tools.query_engine import QueryEngineTool
from llama_index.core.tools.types import BaseTool

"""Tool mapping."""
def convert_tool_to_node(tool: BaseTool) -> TextNode:
    """Function convert Tool to node."""
    ...

class BaseToolNodeMapping(BaseObjectNodeMapping[BaseTool]):
    """Base Tool node mapping."""
    def validate_object(self, obj: BaseTool) -> None:
        ...
    
    @property
    def obj_node_mapping(self) -> Dict[int, Any]:
        """The mapping data structure between node and object."""
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """Persist objs."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> BaseToolNodeMapping:
        ...
    


class SimpleToolNodeMapping(BaseToolNodeMapping):
    """
    Simple Tool mapping.

    In this setup, we assume that the tool name is unique, and
    that the list of all tools are stored in memory.

    """
    def __init__(self, objs: Optional[Sequence[BaseTool]] = ...) -> None:
        ...
    
    @classmethod
    def from_objects(cls, objs: Sequence[BaseTool], *args: Any, **kwargs: Any) -> BaseObjectNodeMapping:
        ...
    
    def to_node(self, tool: BaseTool) -> TextNode:
        """To node."""
        ...
    


class BaseQueryToolNodeMapping(BaseObjectNodeMapping[QueryEngineTool]):
    """Base query tool node mapping."""
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> BaseQueryToolNodeMapping:
        ...
    
    @property
    def obj_node_mapping(self) -> Dict[int, Any]:
        """The mapping data structure between node and object."""
        ...
    
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None:
        """Persist objs."""
        ...
    


class SimpleQueryToolNodeMapping(BaseQueryToolNodeMapping):
    """Simple query tool mapping."""
    def __init__(self, objs: Optional[Sequence[QueryEngineTool]] = ...) -> None:
        ...
    
    def validate_object(self, obj: QueryEngineTool) -> None:
        ...
    
    @classmethod
    def from_objects(cls, objs: Sequence[QueryEngineTool], *args: Any, **kwargs: Any) -> BaseObjectNodeMapping:
        ...
    
    def to_node(self, obj: QueryEngineTool) -> TextNode:
        """To node."""
        ...
    


