"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, Sequence
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.schema import BaseNode

def get_object_mapping(objects: Sequence[Any], from_node_fn: Optional[Callable[[BaseNode], Any]] = ..., to_node_fn: Optional[Callable[[Any], BaseNode]] = ...) -> BaseObjectNodeMapping:
    """Get object mapping according to object."""
    ...

