"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, List, Optional
from qdrant_client import AsyncQdrantClient, QdrantClient
from llama_index.core.schema import BaseNode
from llama_index.core.vector_stores.types import BasePydanticVectorStore, MetadataFilters, VectorStoreQuery, VectorStoreQueryResult
from llama_index.vector_stores.qdrant.utils import HybridFusionCallable, SparseEncoderCallable
from qdrant_client.conversions.common_types import QuantizationConfig
from qdrant_client.http import models as rest

"""
Qdrant vector store index.

An index that is built on top of an existing Qdrant collection.

"""
logger = ...
import_err_msg = ...
DEFAULT_DENSE_VECTOR_NAME = ...
DEFAULT_SPARSE_VECTOR_NAME_OLD = ...
DEFAULT_SPARSE_VECTOR_NAME = ...
LEGACY_UNNAMED_VECTOR = ...
DOCUMENT_ID_KEY = ...
class QdrantVectorStore(BasePydanticVectorStore):
    """
    Qdrant Vector Store.

    In this vector store, embeddings and docs are stored within a
    Qdrant collection.

    During query time, the index uses Qdrant to query for the top
    k most similar nodes.

    Args:
        collection_name: (str): name of the Qdrant collection
        client (Optional[QdrantClient]): QdrantClient instance from `qdrant-client` package
        aclient (Optional[AsyncQdrantClient]): AsyncQdrantClient instance from `qdrant-client` package
        url (Optional[str]): url of the Qdrant instance
        api_key (Optional[str]): API key for authenticating with Qdrant
        batch_size (int): number of points to upload in a single request to Qdrant. Defaults to 64
        parallel (int): number of parallel processes to use during upload. Defaults to 1
        max_retries (int): maximum number of retries in case of a failure. Defaults to 3
        client_kwargs (Optional[dict]): additional kwargs for QdrantClient and AsyncQdrantClient
        enable_hybrid (bool): whether to enable hybrid search using dense and sparse vectors
        fastembed_sparse_model (Optional[str]): name of the FastEmbed sparse model to use, if any
        sparse_doc_fn (Optional[SparseEncoderCallable]): function to encode sparse vectors
        sparse_query_fn (Optional[SparseEncoderCallable]): function to encode sparse queries
        hybrid_fusion_fn (Optional[HybridFusionCallable]): function to fuse hybrid search results
        index_doc_id (bool): whether to create a payload index for the document ID. Defaults to True
        text_key (str): Name of the field holding the text information, Defaults to 'text'
        dense_vector_name (Optional[str]): Custom name for the dense vector field. Defaults to 'text-dense'
        sparse_vector_name (Optional[str]): Custom name for the sparse vector field. Defaults to 'text-sparse-new'
        shard_number (Optional[int]): Shard number for sharding the collection
        sharding_method (Optional[rest.ShardingMethod]): Sharding method for the collection
        replication_factor (Optional[int]): Replication factor for the collection
        write_consistency_factor (Optional[int]): Write consistency factor for the collection
        shard_key_selector_fn (Optional[Callable[..., rest.ShardKeySelector]]): Function to select shard keys
        shard_keys (Optional[list[rest.ShardKey]]): List of shard keys
        payload_indexes: Optional[list[dict[str, rest.PayloadSchemaType]]]: List of payload field indexes

    Notes:
        For backward compatibility, the vector store will automatically detect the vector format
        of existing collections and adapt accordingly:
        - For collections created with older versions using unnamed vectors (empty string ""),
          the vector store will use the legacy format for queries.
        - For collections with named vectors, it will use the existing vector names.
        - For new collections, it will use the vector names provided or the defaults.

    Examples:
        `pip install llama-index-vector-stores-qdrant`

        ```python
        import qdrant_client
        from llama_index.vector_stores.qdrant import QdrantVectorStore

        client = qdrant_client.QdrantClient()

        vector_store = QdrantVectorStore(
            collection_name="example_collection", client=client
        )
        ```

    """
    stores_text: bool = ...
    flat_metadata: bool = ...
    collection_name: str
    url: Optional[str]
    api_key: Optional[str]
    batch_size: int
    parallel: int
    max_retries: int
    client_kwargs: dict = ...
    enable_hybrid: bool
    index_doc_id: bool
    fastembed_sparse_model: Optional[str]
    text_key: Optional[str]
    dense_vector_name: str
    sparse_vector_name: str
    _client: QdrantClient = ...
    _aclient: AsyncQdrantClient = ...
    _collection_initialized: bool = ...
    _sparse_doc_fn: Optional[SparseEncoderCallable] = ...
    _sparse_query_fn: Optional[SparseEncoderCallable] = ...
    _hybrid_fusion_fn: Optional[HybridFusionCallable] = ...
    _dense_config: Optional[rest.VectorParams] = ...
    _sparse_config: Optional[rest.SparseVectorParams] = ...
    _quantization_config: Optional[QuantizationConfig] = ...
    _legacy_vector_format: Optional[bool] = ...
    _shard_key_selector_fn: Optional[Callable[..., rest.ShardKeySelector]] = ...
    _shard_keys: Optional[list[rest.ShardKey]] = ...
    _shard_number: Optional[int] = ...
    _sharding_method: Optional[rest.ShardingMethod] = ...
    _replication_factor: Optional[int] = ...
    _write_consistency_factor: Optional[int] = ...
    _payload_indexes: Optional[list[dict[str, rest.PayloadSchemaType]]] = ...
    def __init__(self, collection_name: str, client: Optional[QdrantClient] = ..., aclient: Optional[AsyncQdrantClient] = ..., url: Optional[str] = ..., api_key: Optional[str] = ..., batch_size: int = ..., parallel: int = ..., max_retries: int = ..., client_kwargs: Optional[dict] = ..., dense_config: Optional[rest.VectorParams] = ..., sparse_config: Optional[rest.SparseVectorParams] = ..., quantization_config: Optional[QuantizationConfig] = ..., enable_hybrid: bool = ..., fastembed_sparse_model: Optional[str] = ..., sparse_doc_fn: Optional[SparseEncoderCallable] = ..., sparse_query_fn: Optional[SparseEncoderCallable] = ..., hybrid_fusion_fn: Optional[HybridFusionCallable] = ..., index_doc_id: bool = ..., text_key: Optional[str] = ..., dense_vector_name: Optional[str] = ..., sparse_vector_name: Optional[str] = ..., shard_number: Optional[int] = ..., sharding_method: Optional[rest.ShardingMethod] = ..., shard_key_selector_fn: Optional[Callable[..., rest.ShardKeySelector]] = ..., shard_keys: Optional[list[rest.ShardKey]] = ..., replication_factor: Optional[int] = ..., write_consistency_factor: Optional[int] = ..., payload_indexes: Optional[list[dict[str, rest.PayloadSchemaType]]] = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def set_query_functions(self, sparse_doc_fn: Optional[SparseEncoderCallable] = ..., sparse_query_fn: Optional[SparseEncoderCallable] = ..., hybrid_fusion_fn: Optional[HybridFusionCallable] = ...): # -> None:
        ...
    
    def get_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., limit: Optional[int] = ..., shard_identifier: Optional[Any] = ...) -> List[BaseNode]:
        """
        Get nodes from the index.

        Args:
            node_ids (Optional[List[str]]): List of node IDs to retrieve.
            filters (Optional[MetadataFilters]): Metadata filters to apply.
            limit (Optional[int]): Maximum number of nodes to retrieve.
            shard_identifier (Optional[Any]): Shard identifier for the query.

        Returns:
            List[BaseNode]: List of nodes retrieved from the index.

        """
        ...
    
    async def aget_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., limit: Optional[int] = ..., shard_identifier: Optional[Any] = ...) -> List[BaseNode]:
        """
        Asynchronous method to get nodes from the index.

        Args:
            node_ids (Optional[List[str]]): List of node IDs to retrieve.
            filters (Optional[MetadataFilters]): Metadata filters to apply.
            limit (Optional[int]): Maximum number of nodes to retrieve.
            shard_identifier (Optional[Any]): Shard identifier for the query.

        Returns:
            List[BaseNode]: List of nodes retrieved from the index.

        """
        ...
    
    def add(self, nodes: List[BaseNode], shard_identifier: Optional[Any] = ..., **add_kwargs: Any) -> List[str]:
        """
        Add nodes to index.

        Args:
            nodes: List[BaseNode]: list of nodes with embeddings
            shard_identifier (Optional[Any]): Shard identifier for the nodes

        """
        ...
    
    async def async_add(self, nodes: List[BaseNode], shard_identifier: Optional[Any] = ..., **kwargs: Any) -> List[str]:
        """
        Asynchronous method to add nodes to Qdrant index.

        Args:
            nodes: List[BaseNode]: List of nodes with embeddings.
            shard_identifier: Optional[Any]: Shard identifier for the nodes.

        Returns:
            List of node IDs that were added to the index.

        Raises:
            ValueError: If trying to using async methods without aclient

        """
        ...
    
    def delete(self, ref_doc_id: str, shard_identifier: Optional[Any] = ..., **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id.

        Args:
            ref_doc_id (str): The doc_id of the document to delete.
            shard_identifier (Optional[Any]): Shard identifier for the nodes.

        """
        ...
    
    async def adelete(self, ref_doc_id: str, shard_identifier: Optional[Any] = ..., **delete_kwargs: Any) -> None:
        """
        Asynchronous method to delete nodes using with ref_doc_id.

        Args:
            ref_doc_id (str): The doc_id of the document to delete.
            shard_identifier (Optional[Any]): Shard identifier for the nodes.

        """
        ...
    
    def delete_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., shard_identifier: Optional[Any] = ..., **delete_kwargs: Any) -> None:
        """
        Delete nodes using with node_ids.

        Args:
            node_ids (Optional[List[str]): List of node IDs to delete.
            filters (Optional[MetadataFilters]): Metadata filters to apply.
            shard_identifier (Optional[Any]): Shard identifier for the nodes.

        """
        ...
    
    async def adelete_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., shard_identifier: Optional[Any] = ..., **delete_kwargs: Any) -> None:
        """
        Asynchronous method to delete nodes using with node_ids.

        Args:
            node_ids (Optional[List[str]): List of node IDs to delete.
            filters (Optional[MetadataFilters]): Metadata filters to apply.
            shard_identifier (Optional[Any]): Shard identifier for the nodes.

        """
        ...
    
    def clear(self) -> None:
        """
        Clear the index.
        """
        ...
    
    async def aclear(self) -> None:
        """
        Asynchronous method to clear the index.
        """
        ...
    
    @property
    def client(self) -> Any:
        """Return the Qdrant client."""
        ...
    
    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """
        Query index for top k most similar nodes.

        Args:
            query (VectorStoreQuery): query

        """
        ...
    
    async def aquery(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """
        Asynchronous method to query index for top k most similar nodes.

        Args:
            query (VectorStoreQuery): query

        """
        ...
    
    def parse_to_query_result(self, response: List[Any]) -> VectorStoreQueryResult:
        """
        Convert vector store response to VectorStoreQueryResult.

        Args:
            response: List[Any]: List of results returned from the vector store.

        """
        ...
    
    def use_old_sparse_encoder(self, collection_name: str) -> bool:
        """
        Check if the collection uses the old sparse encoder format.
        This is used during initialization to determine which sparse vector name to use.
        """
        ...
    
    async def ause_old_sparse_encoder(self, collection_name: str) -> bool:
        """
        Asynchronous method to check if the collection uses the old sparse encoder format.
        """
        ...
    
    def get_default_sparse_doc_encoder(self, collection_name: str, fastembed_sparse_model: Optional[str] = ...) -> SparseEncoderCallable:
        """
        Get the default sparse document encoder.
        For async-only clients, assumes new format initially.
        Will be auto-corrected on first async operation if collection uses old format.
        """
        ...
    
    def get_default_sparse_query_encoder(self, collection_name: str, fastembed_sparse_model: Optional[str] = ...) -> SparseEncoderCallable:
        """
        Get the default sparse query encoder.
        For async-only clients, assumes new format initially.
        Will be auto-corrected on first async operation if collection uses old format.
        """
        ...
    


