"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Optional, Sequence, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.data_structs.data_structs import IndexGraph
from llama_index.core.indices.base import BaseIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode, IndexNode
from llama_index.core.storage.docstore.types import RefDocInfo

"""Tree-based index."""
class TreeRetrieverMode(str, Enum):
    SELECT_LEAF = ...
    SELECT_LEAF_EMBEDDING = ...
    ALL_LEAF = ...
    ROOT = ...


REQUIRE_TREE_MODES = ...
class TreeIndex(BaseIndex[IndexGraph]):
    """
    Tree Index.

    The tree index is a tree-structured index, where each node is a summary of
    the children nodes. During index construction, the tree is constructed
    in a bottoms-up fashion until we end up with a set of root_nodes.

    There are a few different options during query time (see :ref:`Ref-Query`).
    The main option is to traverse down the tree from the root nodes.
    A secondary answer is to directly synthesize the answer from the root nodes.

    Args:
        summary_template (Optional[BasePromptTemplate]): A Summarization Prompt
            (see :ref:`Prompt-Templates`).
        insert_prompt (Optional[BasePromptTemplate]): An Tree Insertion Prompt
            (see :ref:`Prompt-Templates`).
        num_children (int): The number of children each node should have.
        build_tree (bool): Whether to build the tree during index construction.
        show_progress (bool): Whether to show progress bars. Defaults to False.

    """
    index_struct_cls = ...
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., objects: Optional[Sequence[IndexNode]] = ..., index_struct: Optional[IndexGraph] = ..., llm: Optional[LLM] = ..., summary_template: Optional[BasePromptTemplate] = ..., insert_prompt: Optional[BasePromptTemplate] = ..., num_children: int = ..., build_tree: bool = ..., use_async: bool = ..., show_progress: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    def as_retriever(self, retriever_mode: Union[str, TreeRetrieverMode] = ..., embed_model: Optional[BaseEmbedding] = ..., **kwargs: Any) -> BaseRetriever:
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


GPTTreeIndex = TreeIndex
