"""
This type stub file was generated by pyright.
"""

from typing import Optional, Sequence
from llama_index.core.data_structs.data_structs import IndexGraph
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.schema import BaseNode
from llama_index.core.storage.docstore import BaseDocumentStore

"""Tree Index inserter."""
class TreeIndexInserter:
    """LlamaIndex inserter."""
    def __init__(self, index_graph: IndexGraph, llm: Optional[LLM] = ..., num_children: int = ..., insert_prompt: BasePromptTemplate = ..., summary_prompt: BasePromptTemplate = ..., docstore: Optional[BaseDocumentStore] = ...) -> None:
        """Initialize with params."""
        ...
    
    def insert(self, nodes: Sequence[BaseNode]) -> None:
        """Insert into index_graph."""
        ...
    


