"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.tree.base import TreeIndex
from llama_index.core.indices.tree.select_leaf_retriever import TreeSelectLeafRetriever
from llama_index.core.prompts import BasePromptTemplate

"""Query Tree using embedding similarity between query and node text."""
logger = ...
class TreeSelectLeafEmbeddingRetriever(TreeSelectLeafRetriever):
    """
    Tree select leaf embedding retriever.

    This class traverses the index graph using the embedding similarity between the
    query and the node text.

    Args:
        query_template (Optional[BasePromptTemplate]): Tree Select Query Prompt
            (see :ref:`Prompt-Templates`).
        query_template_multiple (Optional[BasePromptTemplate]): Tree Select
            Query Prompt (Multiple)
            (see :ref:`Prompt-Templates`).
        text_qa_template (Optional[BasePromptTemplate]): Question-Answer Prompt
            (see :ref:`Prompt-Templates`).
        refine_template (Optional[BasePromptTemplate]): Refinement Prompt
            (see :ref:`Prompt-Templates`).
        child_branch_factor (int): Number of child nodes to consider at each level.
            If child_branch_factor is 1, then the query will only choose one child node
            to traverse for any given parent node.
            If child_branch_factor is 2, then the query will choose two child nodes.
        embed_model (Optional[BaseEmbedding]): Embedding model to use for
            embedding similarity.

    """
    def __init__(self, index: TreeIndex, embed_model: Optional[BaseEmbedding] = ..., query_template: Optional[BasePromptTemplate] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., refine_template: Optional[BasePromptTemplate] = ..., query_template_multiple: Optional[BasePromptTemplate] = ..., child_branch_factor: int = ..., verbose: bool = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., **kwargs: Any) -> None:
        ...
    


