"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.tree.base import TreeIndex
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode

"""Leaf query mechanism."""
logger = ...
def get_text_from_node(node: BaseNode, level: Optional[int] = ..., verbose: bool = ...) -> str:
    """Get text from node."""
    ...

class TreeSelectLeafRetriever(BaseRetriever):
    """
    Tree select leaf retriever.

    This class traverses the index graph and searches for a leaf node that can best
    answer the query.

    Args:
        query_template (Optional[BasePromptTemplate]): Tree Select Query Prompt
            (see :ref:`Prompt-Templates`).
        query_template_multiple (Optional[BasePromptTemplate]): Tree Select
            Query Prompt (Multiple)
            (see :ref:`Prompt-Templates`).
        child_branch_factor (int): Number of child nodes to consider at each level.
            If child_branch_factor is 1, then the query will only choose one child node
            to traverse for any given parent node.
            If child_branch_factor is 2, then the query will choose two child nodes.

    """
    def __init__(self, index: TreeIndex, query_template: Optional[BasePromptTemplate] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., refine_template: Optional[BasePromptTemplate] = ..., query_template_multiple: Optional[BasePromptTemplate] = ..., child_branch_factor: int = ..., verbose: bool = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., **kwargs: Any) -> None:
        ...
    


