"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.tree.base import TreeIndex

"""Retrieve query."""
logger = ...
class TreeRootRetriever(BaseRetriever):
    """
    Tree root retriever.

    This class directly retrieves the answer from the root nodes.

    Unlike GPTTreeIndexLeafQuery, this class assumes the graph already stores
    the answer (because it was constructed with a query_str), so it does not
    attempt to parse information down the graph in order to synthesize an answer.
    """
    def __init__(self, index: TreeIndex, callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        ...
    


