"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional, Union
from deprecated import deprecated
from huggingface_hub import AsyncInferenceClient, InferenceClient
from huggingface_hub.hf_api import ModelInfo
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks import CallbackManager
from llama_index.embeddings.huggingface.pooling import Pooling
from llama_index.core.embeddings.multi_modal_base import MultiModalEmbedding
from sentence_transformers import SentenceTransformer

DEFAULT_HUGGINGFACE_LENGTH = ...
logger = ...
class HuggingFaceEmbedding(MultiModalEmbedding):
    """
    HuggingFace class for text and image embeddings.

    Args:
        model_name (str, optional): If it is a filepath on disc, it loads the model from that path.
            If it is not a path, it first tries to download a pre-trained SentenceTransformer model.
            If that fails, tries to construct a model from the Hugging Face Hub with that name.
            Defaults to DEFAULT_HUGGINGFACE_EMBEDDING_MODEL.
        max_length (Optional[int], optional): Max sequence length to set in Model's config. If None,
            it will use the Model's default max_seq_length. Defaults to None.
        query_instruction (Optional[str], optional): Instruction to prepend to query text.
            Defaults to None.
        text_instruction (Optional[str], optional): Instruction to prepend to text.
            Defaults to None.
        normalize (bool, optional): Whether to normalize returned vectors.
            Defaults to True.
        embed_batch_size (int, optional): The batch size used for the computation.
            Defaults to DEFAULT_EMBED_BATCH_SIZE.
        cache_folder (Optional[str], optional): Path to store models. Defaults to None.
        trust_remote_code (bool, optional): Whether or not to allow for custom models defined on the
            Hub in their own modeling files. This option should only be set to True for repositories
            you trust and in which you have read the code, as it will execute code present on the Hub
            on your local machine. Defaults to False.
        device (Optional[str], optional): Device (like "cuda", "cpu", "mps", "npu", ...) that should
            be used for computation. If None, checks if a GPU can be used. Defaults to None.
        callback_manager (Optional[CallbackManager], optional): Callback Manager. Defaults to None.
        parallel_process (bool, optional): If True it will start a multi-process pool to process the
            encoding with several independent processes. Great for vast amount of texts.
            Defaults to False.
        target_devices (Optional[List[str]], optional): PyTorch target devices, e.g.
            ["cuda:0", "cuda:1", ...], ["npu:0", "npu:1", ...], or ["cpu", "cpu", "cpu", "cpu"].
            If target_devices is None and CUDA/NPU is available, then all available CUDA/NPU devices
            will be used. If target_devices is None and CUDA/NPU is not available, then 4 CPU devices
            will be used. This parameter will only be used if `parallel_process = True`.
            Defaults to None.
        num_workers (int, optional): The number of workers to use for async embedding calls.
            Defaults to None.
        show_progress_bar (bool, optional): Whether to show a progress bar.
            Defaults to False.
        **model_kwargs: Other model kwargs to use
        tokenizer_name (Optional[str], optional): "Deprecated"
        pooling (str, optional): "Deprecated"
        model (Optional[Any], optional): "Deprecated"
        tokenizer (Optional[Any], optional): "Deprecated"

    Examples:
        `pip install llama-index-embeddings-huggingface`

        ```python
        from llama_index.core import Settings
        from llama_index.embeddings.huggingface import HuggingFaceEmbedding

        # Set up the HuggingFaceEmbedding class with the required model to use with llamaindex core.
        embed_model  = HuggingFaceEmbedding(model_name = "BAAI/bge-small-en")
        Settings.embed_model = embed_model

        # Or if you want to Embed some text separately
        embeddings = embed_model.get_text_embedding("I want to Embed this text!")

        ```

    """
    max_length: int = ...
    normalize: bool = ...
    query_instruction: Optional[str] = ...
    text_instruction: Optional[str] = ...
    cache_folder: Optional[str] = ...
    show_progress_bar: bool = ...
    _model: SentenceTransformer = ...
    _device: str = ...
    _parallel_process: bool = ...
    _target_devices: Optional[List[str]] = ...
    def __init__(self, model_name: str = ..., tokenizer_name: Optional[str] = ..., pooling: str = ..., max_length: Optional[int] = ..., query_instruction: Optional[str] = ..., text_instruction: Optional[str] = ..., normalize: bool = ..., model: Optional[Any] = ..., tokenizer: Optional[Any] = ..., embed_batch_size: int = ..., cache_folder: Optional[str] = ..., trust_remote_code: bool = ..., device: Optional[str] = ..., callback_manager: Optional[CallbackManager] = ..., parallel_process: bool = ..., target_devices: Optional[List[str]] = ..., show_progress_bar: bool = ..., **model_kwargs) -> None:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


@deprecated("Deprecated in favor of `HuggingFaceInferenceAPIEmbedding` from `llama-index-embeddings-huggingface-api` which should be used instead.", action="always")
class HuggingFaceInferenceAPIEmbedding(BaseEmbedding):
    """
    Wrapper on the Hugging Face's Inference API for embeddings.

    Overview of the design:
    - Uses the feature extraction task: https://huggingface.co/tasks/feature-extraction
    """
    pooling: Optional[Pooling] = ...
    query_instruction: Optional[str] = ...
    text_instruction: Optional[str] = ...
    model_name: Optional[str] = ...
    token: Union[str, bool, None] = ...
    timeout: Optional[float] = ...
    headers: Dict[str, str] = ...
    cookies: Dict[str, str] = ...
    task: Optional[str] = ...
    _sync_client: InferenceClient = ...
    _async_client: AsyncInferenceClient = ...
    _get_model_info: Callable[..., ModelInfo] = ...
    def __init__(self, **kwargs: Any) -> None:
        """
        Initialize.

        Args:
            kwargs: See the class-level Fields.

        """
        ...
    
    def validate_supported(self, task: str) -> None:
        """
        Confirm the contained model_name is deployed on the Inference API service.

        Args:
            task: Hugging Face task to check within. A list of all tasks can be
                found here: https://huggingface.co/tasks

        """
        ...
    
    def get_model_info(self, **kwargs: Any) -> ModelInfo:
        """Get metadata on the current model from Hugging Face."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


HuggingFaceInferenceAPIEmbeddings = HuggingFaceInferenceAPIEmbedding
