"""
This type stub file was generated by pyright.
"""

import numpy as np
import torch
from enum import Enum
from typing import TYPE_CHECKING, Union, overload

if TYPE_CHECKING:
    ...
class Pooling(str, Enum):
    """Enum of possible pooling choices with pooling behaviors."""
    CLS = ...
    MEAN = ...
    LAST = ...
    def __call__(self, array: np.ndarray) -> np.ndarray:
        ...
    
    @classmethod
    @overload
    def cls_pooling(cls, array: np.ndarray) -> np.ndarray:
        ...
    
    @classmethod
    @overload
    def cls_pooling(cls, array: torch.Tensor) -> torch.Tensor:
        ...
    
    @classmethod
    def cls_pooling(cls, array: Union[np.ndarray, torch.Tensor]) -> Union[np.ndarray, torch.Tensor]:
        ...
    
    @classmethod
    def mean_pooling(cls, array: np.ndarray) -> np.ndarray:
        ...
    
    @classmethod
    @overload
    def last_pooling(cls, array: np.ndarray) -> np.ndarray:
        ...
    
    @classmethod
    @overload
    def last_pooling(cls, array: torch.Tensor) -> torch.Tensor:
        ...
    
    @classmethod
    def last_pooling(cls, array: Union[np.ndarray, torch.Tensor]) -> Union[np.ndarray, torch.Tensor]:
        ...
    


