"""
This type stub file was generated by pyright.
"""

from llama_index.readers.file.slides.base import PptxReader
from llama_index.readers.file.slides.image_extractor import ImageExtractor
from llama_index.readers.file.slides.content_extractor import SlideContentExtractor

__all__ = ["PptxReader", "ImageExtractor", "SlideContentExtractor"]
