"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional
from llama_index.core.base.llms.base import BaseLLM

"""
Enhanced content extraction for PowerPoint slides.

Extracts text, tables, charts, and speaker notes with proper structure preservation.
"""
logger = ...
MAX_ATTEMPTS = ...
MIN_BACKOFF = ...
MAX_BACKOFF = ...
SECTION_SEPARATOR = ...
def is_rate_limit_error(exception: Exception) -> bool:
    """Check if the exception is a rate limit error."""
    ...

class SlideContentExtractor:
    """
    Enhanced content extractor for PowerPoint slides.

    Extracts comprehensive content including tables, charts, notes, and structured text.
    """
    def __init__(self, llm: Optional[BaseLLM] = ..., extract_images: bool = ..., context_consolidation_with_llm: bool = ...) -> None:
        """
        Initialize content extractor.

        Args:
            llm: Optional LLM for content consolidation
            extract_images: Whether to extract and caption images
            context_consolidation_with_llm: Whether to use LLM for content consolidation

        """
        ...
    
    def extract_slide_safe(self, slide, slide_number: int, filename: Path) -> Dict[str, Any]:
        """Extract slide content with comprehensive error recovery."""
        ...
    


