"""
This type stub file was generated by pyright.
"""

from llama_index.core.llms import ChatMessage, LLM
from typing import Any, Dict, List, Type
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.base.llms.types import ChatMessage

"""Agent utils."""
def messages_to_xml_format(messages: List[ChatMessage]) -> List[ChatMessage]:
    ...

async def generate_structured_response(messages: List[ChatMessage], llm: LLM, output_cls: Type[BaseModel]) -> Dict[str, Any]:
    ...

