"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Sequence, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.data_structs.document_summary import IndexDocumentSummary
from llama_index.core.indices.base import BaseIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.response_synthesizers import BaseSynthesizer
from llama_index.core.schema import BaseNode, IndexNode
from llama_index.core.storage.docstore.types import RefDocInfo
from llama_index.core.storage.storage_context import StorageContext
from llama_index.core.vector_stores.types import BasePydanticVectorStore

"""
Document summary index.

A data structure where LlamaIndex stores the summary per document, and maps
the summary to the underlying Nodes.
This summary can be used for retrieval.

"""
logger = ...
DEFAULT_SUMMARY_QUERY = ...
class DocumentSummaryRetrieverMode(str, Enum):
    EMBEDDING = ...
    LLM = ...


_RetrieverMode = DocumentSummaryRetrieverMode
class DocumentSummaryIndex(BaseIndex[IndexDocumentSummary]):
    """
    Document Summary Index.

    Args:
        response_synthesizer (BaseSynthesizer): A response synthesizer for generating
            summaries.
        summary_query (str): The query to use to generate the summary for each document.
        show_progress (bool): Whether to show tqdm progress bars.
            Defaults to False.
        embed_summaries (bool): Whether to embed the summaries.
            This is required for running the default embedding-based retriever.
            Defaults to True.

    """
    index_struct_cls = ...
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., objects: Optional[Sequence[IndexNode]] = ..., index_struct: Optional[IndexDocumentSummary] = ..., llm: Optional[LLM] = ..., embed_model: Optional[BaseEmbedding] = ..., storage_context: Optional[StorageContext] = ..., response_synthesizer: Optional[BaseSynthesizer] = ..., summary_query: str = ..., show_progress: bool = ..., embed_summaries: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def vector_store(self) -> BasePydanticVectorStore:
        ...
    
    def as_retriever(self, retriever_mode: Union[str, _RetrieverMode] = ..., **kwargs: Any) -> BaseRetriever:
        """
        Get retriever.

        Args:
            retriever_mode (Union[str, DocumentSummaryRetrieverMode]): A retriever mode.
                Defaults to DocumentSummaryRetrieverMode.EMBEDDING.

        """
        ...
    
    def get_document_summary(self, doc_id: str) -> str:
        """
        Get document summary by doc id.

        Args:
            doc_id (str): A document id.

        """
        ...
    
    def delete_nodes(self, node_ids: List[str], delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """
        Delete a list of nodes from the index.

        Args:
            node_ids (List[str]): A list of node_ids from the nodes to delete

        """
        ...
    
    def delete_ref_doc(self, ref_doc_id: str, delete_from_docstore: bool = ..., **delete_kwargs: Any) -> None:
        """
        Delete a document from the index.
        All nodes in the index related to the document will be deleted.
        """
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


GPTDocumentSummaryIndex = DocumentSummaryIndex
