"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.document_summary.base import DocumentSummaryIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate

"""
Document summary retrievers.

This module contains retrievers for document summary indices.

"""
logger = ...
class DocumentSummaryIndexLLMRetriever(BaseRetriever):
    """
    Document Summary Index LLM Retriever.

    By default, select relevant summaries from index using LLM calls.

    Args:
        index (DocumentSummaryIndex): The index to retrieve from.
        choice_select_prompt (Optional[BasePromptTemplate]): The prompt to use for selecting relevant summaries.
        choice_batch_size (int): The number of summary nodes to send to LLM at a time.
        choice_top_k (int): The number of summary nodes to retrieve.
        format_node_batch_fn (Callable): Function to format a batch of nodes for LLM.
        parse_choice_select_answer_fn (Callable): Function to parse LLM response.
        llm (LLM): The llm to use.

    """
    def __init__(self, index: DocumentSummaryIndex, choice_select_prompt: Optional[BasePromptTemplate] = ..., choice_batch_size: int = ..., choice_top_k: int = ..., format_node_batch_fn: Optional[Callable] = ..., parse_choice_select_answer_fn: Optional[Callable] = ..., llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        ...
    


class DocumentSummaryIndexEmbeddingRetriever(BaseRetriever):
    """
    Document Summary Index Embedding Retriever.

    Args:
        index (DocumentSummaryIndex): The index to retrieve from.
        similarity_top_k (int): The number of summary nodes to retrieve.

    """
    def __init__(self, index: DocumentSummaryIndex, similarity_top_k: int = ..., embed_model: Optional[BaseEmbedding] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    


DocumentSummaryIndexRetriever = DocumentSummaryIndexLLMRetriever
