"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Optional, Sequence, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.data_structs.data_structs import KeywordTable
from llama_index.core.indices.base import BaseIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode, IndexNode
from llama_index.core.storage.docstore.types import RefDocInfo

"""
Keyword-table based index.

Similar to a "hash table" in concept. LlamaIndex first tries
to extract keywords from the source text, and stores the
keywords as keys per item. It similarly extracts keywords
from the query text. Then, it tries to match those keywords to
existing keywords in the table.

"""
DQKET = ...
class KeywordTableRetrieverMode(str, Enum):
    DEFAULT = ...
    SIMPLE = ...
    RAKE = ...


class BaseKeywordTableIndex(BaseIndex[KeywordTable]):
    """
    Base Keyword Table Index.

    This index extracts keywords from the text, and maps each
    keyword to the node(s) that it corresponds to. In this sense it mimics a
    "hash table". During index construction, the keyword table is constructed
    by extracting keywords from each node and creating an internal mapping.

    During query time, the keywords are extracted from the query text, and these
    keywords are used to index into the keyword table. The retrieved nodes
    are then used to answer the query.

    Args:
        keyword_extract_template (Optional[BasePromptTemplate]): A Keyword
            Extraction Prompt
            (see :ref:`Prompt-Templates`).
        use_async (bool): Whether to use asynchronous calls. Defaults to False.
        show_progress (bool): Whether to show tqdm progress bars. Defaults to False.

    """
    index_struct_cls = ...
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., objects: Optional[Sequence[IndexNode]] = ..., index_struct: Optional[KeywordTable] = ..., llm: Optional[LLM] = ..., keyword_extract_template: Optional[BasePromptTemplate] = ..., max_keywords_per_chunk: int = ..., use_async: bool = ..., show_progress: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    def as_retriever(self, retriever_mode: Union[str, KeywordTableRetrieverMode] = ..., **kwargs: Any) -> BaseRetriever:
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


class KeywordTableIndex(BaseKeywordTableIndex):
    """
    Keyword Table Index.

    This index uses a GPT model to extract keywords from the text.

    """
    ...


GPTKeywordTableIndex = KeywordTableIndex
