"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.indices.keyword_table.base import BaseKeywordTableIndex, KeywordTableRetrieverMode

"""
RAKE keyword-table based index.

Similar to KeywordTableIndex, but uses RAKE instead of GPT.

"""
class RAKEKeywordTableIndex(BaseKeywordTableIndex):
    """
    RAKE Keyword Table Index.

    This index uses a RAKE keyword extractor to extract keywords from the text.

    """
    def as_retriever(self, retriever_mode: Union[str, KeywordTableRetrieverMode] = ..., **kwargs: Any) -> BaseRetriever:
        ...
    


GPTRAKEKeywordTableIndex = RAKEKeywordTableIndex
