"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.keyword_table.base import BaseKeywordTableIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import BasePromptTemplate

"""Query for KeywordTableIndex."""
DQKET = ...
logger = ...
class BaseKeywordTableRetriever(BaseRetriever):
    """
    Base Keyword Table Retriever.

    Arguments are shared among subclasses.

    Args:
        keyword_extract_template (Optional[BasePromptTemplate]): A Keyword
            Extraction Prompt
            (see :ref:`Prompt-Templates`).
        query_keyword_extract_template (Optional[BasePromptTemplate]): A Query
            Keyword Extraction
            Prompt (see :ref:`Prompt-Templates`).
        refine_template (Optional[BasePromptTemplate]): A Refinement Prompt
            (see :ref:`Prompt-Templates`).
        text_qa_template (Optional[BasePromptTemplate]): A Question Answering Prompt
            (see :ref:`Prompt-Templates`).
        max_keywords_per_query (int): Maximum number of keywords to extract from query.
        num_chunks_per_query (int): Maximum number of text chunks to query.

    """
    def __init__(self, index: BaseKeywordTableIndex, keyword_extract_template: Optional[BasePromptTemplate] = ..., query_keyword_extract_template: Optional[BasePromptTemplate] = ..., max_keywords_per_query: int = ..., num_chunks_per_query: int = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


class KeywordTableGPTRetriever(BaseKeywordTableRetriever):
    """
    Keyword Table Index GPT Retriever.

    Extracts keywords using GPT. Set when using `retriever_mode="default"`.

    See BaseGPTKeywordTableQuery for arguments.

    """
    def __init__(self, index: BaseKeywordTableIndex, keyword_extract_template: Optional[BasePromptTemplate] = ..., query_keyword_extract_template: Optional[BasePromptTemplate] = ..., max_keywords_per_query: int = ..., num_chunks_per_query: int = ..., llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    


class KeywordTableSimpleRetriever(BaseKeywordTableRetriever):
    """
    Keyword Table Index Simple Retriever.

    Extracts keywords using simple regex-based keyword extractor.
    Set when `retriever_mode="simple"`.

    See BaseGPTKeywordTableQuery for arguments.

    """
    ...


class KeywordTableRAKERetriever(BaseKeywordTableRetriever):
    """
    Keyword Table Index RAKE Retriever.

    Extracts keywords using RAKE keyword extractor.
    Set when `retriever_mode="rake"`.

    See BaseGPTKeywordTableQuery for arguments.

    """
    ...


