"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.indices.keyword_table.base import BaseKeywordTableIndex, KeywordTableRetrieverMode

"""
Simple keyword-table based index.

Similar to KeywordTableIndex, but uses a simpler keyword extraction
technique that doesn't involve GPT - just uses regex.

"""
DQKET = ...
class SimpleKeywordTableIndex(BaseKeywordTableIndex):
    """
    Simple Keyword Table Index.

    This index uses a simple regex extractor to extract keywords from the text.

    """
    def as_retriever(self, retriever_mode: Union[str, KeywordTableRetrieverMode] = ..., **kwargs: Any) -> BaseRetriever:
        ...
    


GPTSimpleKeywordTableIndex = SimpleKeywordTableIndex
