"""
This type stub file was generated by pyright.
"""

from typing import Optional, Set

"""Utils for keyword table."""
def simple_extract_keywords(text_chunk: str, max_keywords: Optional[int] = ..., filter_stopwords: bool = ...) -> Set[str]:
    """Extract keywords with simple algorithm."""
    ...

def rake_extract_keywords(text_chunk: str, max_keywords: Optional[int] = ..., expand_with_subtokens: bool = ...) -> Set[str]:
    """Extract keywords with RAKE."""
    ...

def extract_keywords_given_response(response: str, lowercase: bool = ..., start_token: str = ...) -> Set[str]:
    """
    Extract keywords given the GPT-generated response.

    Used by keyword table indices.
    Parses <start_token>: <word1>, <word2>, ... into [word1, word2, ...]
    Raises exception if response doesn't start with <start_token>
    """
    ...

