"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from llama_index.core.base.base_auto_retriever import BaseAutoRetriever
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.vector_store.base import VectorStoreIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.schema import IndexNode, QueryBundle
from llama_index.core.vector_stores.types import MetadataFilters, VectorStoreInfo, VectorStoreQueryMode

_logger = ...
class VectorIndexAutoRetriever(BaseAutoRetriever):
    """
    Vector store auto retriever.

    A retriever for vector store index that uses an LLM to automatically set
    vector store query parameters.

    Args:
        index (VectorStoreIndex): vector store index
        vector_store_info (VectorStoreInfo): additional information about
            vector store content and supported metadata filters. The natural language
            description is used by an LLM to automatically set vector store query
            parameters.
        prompt_template_str: custom prompt template string for LLM.
            Uses default template string if None.
        similarity_top_k (int): number of top k results to return.
        empty_query_top_k (Optional[int]): number of top k results to return
            if the inferred query string is blank (uses metadata filters only).
            Can be set to None, which would use the similarity_top_k instead.
            By default, set to 10.
        max_top_k (int):
            the maximum top_k allowed. The top_k set by LLM or similarity_top_k will
            be clamped to this value.
        vector_store_query_mode (str): vector store query mode
            See reference for VectorStoreQueryMode for full list of supported modes.
        default_empty_query_vector (Optional[List[float]]): default empty query vector.
            Defaults to None. If not None, then this vector will be used as the query
            vector if the query is empty.
        callback_manager (Optional[CallbackManager]): callback manager
        verbose (bool): verbose mode

    """
    def __init__(self, index: VectorStoreIndex, vector_store_info: VectorStoreInfo, llm: Optional[LLM] = ..., prompt_template_str: Optional[str] = ..., max_top_k: int = ..., similarity_top_k: int = ..., empty_query_top_k: Optional[int] = ..., vector_store_query_mode: VectorStoreQueryMode = ..., default_empty_query_vector: Optional[List[float]] = ..., callback_manager: Optional[CallbackManager] = ..., verbose: bool = ..., extra_filters: Optional[MetadataFilters] = ..., object_map: Optional[dict] = ..., objects: Optional[List[IndexNode]] = ..., **kwargs: Any) -> None:
        ...
    
    def generate_retrieval_spec(self, query_bundle: QueryBundle, **kwargs: Any) -> BaseModel:
        ...
    
    async def agenerate_retrieval_spec(self, query_bundle: QueryBundle, **kwargs: Any) -> BaseModel:
        ...
    


