"""
This type stub file was generated by pyright.
"""

from typing import Any
from llama_index.core.types import BaseOutputParser

class VectorStoreQueryOutputParser(BaseOutputParser):
    def parse(self, output: str) -> Any:
        ...
    
    def format(self, prompt_template: str) -> str:
        ...
    


