"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Video audio parser.

Contains parsers for mp3, mp4 files.

"""
logger = ...
class VideoAudioReader(BaseReader):
    """
    Video audio parser.

    Extract text from transcript of video/audio files.

    """
    def __init__(self, *args: Any, model_version: str = ..., **kwargs: Any) -> None:
        """Init parser."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


