"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, AsyncGenerator, Generator, List, Optional, Sequence, Type
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.llms import LLM
from llama_index.core.prompts.mixin import PromptMixin
from llama_index.core.schema import NodeWithScore, QueryType
from llama_index.core.types import RESPONSE_TEXT_TYPE
from llama_index.core.instrumentation import DispatcherSpanMixin

"""
Response builder class.

This class provides general functions for taking in a set of text
and generating a response.

Will support different modes, from 1) stuffing chunks into prompt,
2) create and refine separately over each chunk, 3) tree summarization.

"""
dispatcher = ...
logger = ...
QueryTextType = QueryType
def empty_response_generator() -> Generator[str, None, None]:
    ...

async def empty_response_agenerator() -> AsyncGenerator[str, None]:
    ...

class BaseSynthesizer(PromptMixin, DispatcherSpanMixin):
    """Response builder class."""
    def __init__(self, llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., prompt_helper: Optional[PromptHelper] = ..., streaming: bool = ..., output_cls: Optional[Type[BaseModel]] = ...) -> None:
        """Init params."""
        ...
    
    @property
    def callback_manager(self) -> CallbackManager:
        ...
    
    @callback_manager.setter
    def callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...
    
    @abstractmethod
    def get_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Get response."""
        ...
    
    @abstractmethod
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Get response."""
        ...
    
    @dispatcher.span
    def synthesize(self, query: QueryTextType, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ..., **response_kwargs: Any) -> RESPONSE_TYPE:
        ...
    
    @dispatcher.span
    async def asynthesize(self, query: QueryTextType, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ..., **response_kwargs: Any) -> RESPONSE_TYPE:
        ...
    


