"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from llama_index.core.response_synthesizers.refine import Refine
from llama_index.core.types import RESPONSE_TEXT_TYPE

dispatcher = ...
class CompactAndRefine(Refine):
    """Refine responses across compact text chunks."""
    @dispatcher.span
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], prev_response: Optional[RESPONSE_TEXT_TYPE] = ..., **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    
    @dispatcher.span
    def get_response(self, query_str: str, text_chunks: Sequence[str], prev_response: Optional[RESPONSE_TEXT_TYPE] = ..., **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Get compact response."""
        ...
    


