"""
This type stub file was generated by pyright.
"""

from typing import Any, Sequence
from llama_index.core.response_synthesizers.base import BaseSynthesizer
from llama_index.core.types import RESPONSE_TEXT_TYPE

class ContextOnly(BaseSynthesizer):
    def get_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    


