"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, Type
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.llms import LLM
from llama_index.core.response_synthesizers.base import BaseSynthesizer
from llama_index.core.response_synthesizers.type import ResponseMode
from llama_index.core.types import BasePydanticProgram

def get_response_synthesizer(llm: Optional[LLM] = ..., prompt_helper: Optional[PromptHelper] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., refine_template: Optional[BasePromptTemplate] = ..., summary_template: Optional[BasePromptTemplate] = ..., simple_template: Optional[BasePromptTemplate] = ..., response_mode: ResponseMode = ..., callback_manager: Optional[CallbackManager] = ..., use_async: bool = ..., streaming: bool = ..., structured_answer_filtering: bool = ..., output_cls: Optional[Type[BaseModel]] = ..., program_factory: Optional[Callable[[BasePromptTemplate], BasePydanticProgram]] = ..., verbose: bool = ...) -> BaseSynthesizer:
    """Get a response synthesizer."""
    ...

