"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, Sequence, Type
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.llms import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.response_synthesizers.base import BaseSynthesizer
from llama_index.core.types import BasePydanticProgram, RESPONSE_TEXT_TYPE

dispatcher = ...
logger = ...
class StructuredRefineResponse(BaseModel):
    """
    Used to answer a given query based on the provided context.

    Also indicates if the query was satisfied with the provided answer.
    """
    answer: str = ...
    query_satisfied: bool = ...


class DefaultRefineProgram(BasePydanticProgram):
    """
    Runs the query on the LLM as normal and always returns the answer with
    query_satisfied=True. In effect, doesn't do any answer filtering.
    """
    def __init__(self, prompt: BasePromptTemplate, llm: LLM, output_cls: Optional[Type[BaseModel]] = ...) -> None:
        ...
    
    @property
    def output_cls(self) -> Type[BaseModel]:
        ...
    
    def __call__(self, *args: Any, **kwds: Any) -> StructuredRefineResponse:
        ...
    
    async def acall(self, *args: Any, **kwds: Any) -> StructuredRefineResponse:
        ...
    


class Refine(BaseSynthesizer):
    """Refine a response to a query across text chunks."""
    def __init__(self, llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., prompt_helper: Optional[PromptHelper] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., refine_template: Optional[BasePromptTemplate] = ..., output_cls: Optional[Type[BaseModel]] = ..., streaming: bool = ..., verbose: bool = ..., structured_answer_filtering: bool = ..., program_factory: Optional[Callable[[BasePromptTemplate], BasePydanticProgram]] = ...) -> None:
        ...
    
    @dispatcher.span
    def get_response(self, query_str: str, text_chunks: Sequence[str], prev_response: Optional[RESPONSE_TEXT_TYPE] = ..., **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Give response over chunks."""
        ...
    
    @dispatcher.span
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], prev_response: Optional[RESPONSE_TEXT_TYPE] = ..., **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    


