"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.llms import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.response_synthesizers.base import BaseSynthesizer
from llama_index.core.types import RESPONSE_TEXT_TYPE

class SimpleSummarize(BaseSynthesizer):
    def __init__(self, llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., prompt_helper: Optional[PromptHelper] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., streaming: bool = ...) -> None:
        ...
    
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    
    def get_response(self, query_str: str, text_chunks: Sequence[str], **kwargs: Any) -> RESPONSE_TEXT_TYPE:
        ...
    


