"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence, Type
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.prompt_helper import PromptHelper
from llama_index.core.llms import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.response_synthesizers.base import BaseSynthesizer
from llama_index.core.types import BaseModel, RESPONSE_TEXT_TYPE

class TreeSummarize(BaseSynthesizer):
    """
    Tree summarize response builder.

    This response builder recursively merges text chunks and summarizes them
    in a bottom-up fashion (i.e. building a tree from leaves to root).

    More concretely, at each recursively step:
    1. we repack the text chunks so that each chunk fills the context window of the LLM
    2. if there is only one chunk, we give the final response
    3. otherwise, we summarize each chunk and recursively summarize the summaries.
    """
    def __init__(self, llm: Optional[LLM] = ..., callback_manager: Optional[CallbackManager] = ..., prompt_helper: Optional[PromptHelper] = ..., summary_template: Optional[BasePromptTemplate] = ..., output_cls: Optional[Type[BaseModel]] = ..., streaming: bool = ..., use_async: bool = ..., verbose: bool = ...) -> None:
        ...
    
    async def aget_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Get tree summarize response."""
        ...
    
    def get_response(self, query_str: str, text_chunks: Sequence[str], **response_kwargs: Any) -> RESPONSE_TEXT_TYPE:
        """Get tree summarize response."""
        ...
    


