"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Dict, List, Optional
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Epub parser.

Contains parsers for epub files.
"""
logger = ...
class EpubReader(BaseReader):
    """Epub Parser."""
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


