"""
This type stub file was generated by pyright.
"""

from typing import List
from llama_index.core.base.embeddings.base import BaseEmbedding, Embedding
from llama_index.core.schema import ImageType

"""Base embeddings file."""
class MultiModalEmbedding(BaseEmbedding):
    """Base class for Multi Modal embeddings."""
    def get_image_embedding(self, img_file_path: ImageType) -> Embedding:
        """
        Embed the input image.
        """
        ...
    
    async def aget_image_embedding(self, img_file_path: ImageType) -> Embedding:
        """Get image embedding."""
        ...
    
    def get_image_embedding_batch(self, img_file_paths: List[ImageType], show_progress: bool = ...) -> List[Embedding]:
        """Get a list of image embeddings, with batching."""
        ...
    
    async def aget_image_embedding_batch(self, img_file_paths: List[ImageType], show_progress: bool = ...) -> List[Embedding]:
        """Asynchronously get a list of image embeddings, with batching."""
        ...
    


