"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional, Sequence
from llama_index.core.node_parser.interface import TextSplitter
from llama_index.core.llms import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseNode
from llama_index.core.utilities.sql_wrapper import SQLDatabase

"""Common classes for structured operations."""
logger = ...
class SQLDocumentContextBuilder:
    """
    Builder that builds context for a given set of SQL tables.

    Args:
        sql_database (Optional[SQLDatabase]): SQL database to use,
        text_splitter (Optional[TextSplitter]): Text Splitter to use.
        table_context_prompt (Optional[BasePromptTemplate]): A
            Table Context Prompt (see :ref:`Prompt-Templates`).
        refine_table_context_prompt (Optional[BasePromptTemplate]):
            A Refine Table Context Prompt (see :ref:`Prompt-Templates`).
        table_context_task (Optional[str]): The query to perform
            on the table context. A default query string is used
            if none is provided by the user.

    """
    def __init__(self, sql_database: SQLDatabase, llm: Optional[LLM] = ..., text_splitter: Optional[TextSplitter] = ..., table_context_prompt: Optional[BasePromptTemplate] = ..., refine_table_context_prompt: Optional[BasePromptTemplate] = ..., table_context_task: Optional[str] = ...) -> None:
        """Initialize params."""
        ...
    
    def build_all_context_from_documents(self, documents_dict: Dict[str, List[BaseNode]]) -> Dict[str, str]:
        """Build context for all tables in the database."""
        ...
    
    def build_table_context_from_documents(self, documents: Sequence[BaseNode], table_name: str) -> str:
        """Build context from documents for a single table."""
        ...
    


OUTPUT_PARSER_TYPE = Callable[[str], Optional[Dict[str, Any]]]
class BaseStructDatapointExtractor:
    """Extracts datapoints from a structured document."""
    def __init__(self, llm: LLM, schema_extract_prompt: BasePromptTemplate, output_parser: OUTPUT_PARSER_TYPE) -> None:
        """Initialize params."""
        ...
    
    def insert_datapoint_from_nodes(self, nodes: Sequence[BaseNode]) -> None:
        """Extract datapoint from a document and insert it."""
        ...
    


