"""
This type stub file was generated by pyright.
"""

from typing import Optional
from llama_index.core.indices.common.struct_store.base import BaseStructDatapointExtractor, OUTPUT_PARSER_TYPE
from llama_index.core.llms import LLM
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.utilities.sql_wrapper import SQLDatabase
from sqlalchemy import Table

"""SQL StructDatapointExtractor."""
class SQLStructDatapointExtractor(BaseStructDatapointExtractor):
    """Extracts datapoints from a structured document for a SQL db."""
    def __init__(self, llm: LLM, schema_extract_prompt: BasePromptTemplate, output_parser: OUTPUT_PARSER_TYPE, sql_database: SQLDatabase, table_name: Optional[str] = ..., table: Optional[Table] = ..., ref_doc_id_column: Optional[str] = ...) -> None:
        """Initialize params."""
        ...
    


