"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Union
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.schema import QueryType

"""Custom query engine."""
STR_OR_RESPONSE_TYPE = Union[RESPONSE_TYPE, str]
class CustomQueryEngine(BaseModel, BaseQueryEngine):
    """
    Custom query engine.

    Subclasses can define additional attributes as Pydantic fields.
    Subclasses must implement the `custom_query` method, which takes a query string
    and returns either a Response object or a string as output.

    They can optionally implement the `acustom_query` method for async support.

    """
    model_config = ...
    callback_manager: CallbackManager = ...
    def query(self, str_or_query_bundle: QueryType) -> RESPONSE_TYPE:
        ...
    
    async def aquery(self, str_or_query_bundle: QueryType) -> RESPONSE_TYPE:
        ...
    
    @abstractmethod
    def custom_query(self, query_str: str) -> STR_OR_RESPONSE_TYPE:
        """Run a custom query."""
        ...
    
    async def acustom_query(self, query_str: str) -> STR_OR_RESPONSE_TYPE:
        """Run a custom query asynchronously."""
        ...
    


