"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.indices.composability.graph import ComposableGraph

dispatcher = ...
class ComposableGraphQueryEngine(BaseQueryEngine):
    """
    Composable graph query engine.

    This query engine can operate over a ComposableGraph.
    It can take in custom query engines for its sub-indices.

    Args:
        graph (ComposableGraph): A ComposableGraph object.
        custom_query_engines (Optional[Dict[str, BaseQueryEngine]]): A dictionary of
            custom query engines.
        recursive (bool): Whether to recursively query the graph.
        **kwargs: additional arguments to be passed to the underlying index query
            engine.

    """
    def __init__(self, graph: ComposableGraph, custom_query_engines: Optional[Dict[str, BaseQueryEngine]] = ..., recursive: bool = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    


