"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.indices.query.query_transform.base import StepDecomposeQueryTransform
from llama_index.core.response_synthesizers import BaseSynthesizer

def default_stop_fn(stop_dict: Dict) -> bool:
    """Stop function for multi-step query combiner."""
    ...

class MultiStepQueryEngine(BaseQueryEngine):
    """
    Multi-step query engine.

    This query engine can operate over an existing base query engine,
    along with the multi-step query transform.

    Args:
        query_engine (BaseQueryEngine): A BaseQueryEngine object.
        query_transform (StepDecomposeQueryTransform): A StepDecomposeQueryTransform
            object.
        response_synthesizer (Optional[BaseSynthesizer]): A BaseSynthesizer
            object.
        num_steps (Optional[int]): Number of steps to run the multi-step query.
        early_stopping (bool): Whether to stop early if the stop function returns True.
        index_summary (str): A string summary of the index.
        stop_fn (Optional[Callable[[Dict], bool]]): A stop function that takes in a
            dictionary of information and returns a boolean.

    """
    def __init__(self, query_engine: BaseQueryEngine, query_transform: StepDecomposeQueryTransform, response_synthesizer: Optional[BaseSynthesizer] = ..., num_steps: Optional[int] = ..., early_stopping: bool = ..., index_summary: str = ..., stop_fn: Optional[Callable[[Dict], bool]] = ...) -> None:
        ...
    


