"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Sequence, TYPE_CHECKING
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.query.base import BaseQueryEngine
from llama_index.core.indices.query.schema import QueryBundle, QueryType
from llama_index.core.llms import LLM
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import NodeWithScore
from llama_index.core.indices.multi_modal import MultiModalVectorIndexRetriever

if TYPE_CHECKING:
    ...
class SimpleMultiModalQueryEngine(BaseQueryEngine):
    """
    Simple Multi Modal Retriever query engine.

    Assumes that retrieved text context fits within context window of LLM, along with images.

    Args:
        retriever (MultiModalVectorIndexRetriever): A retriever object.
        multi_modal_llm (Optional[LLM]): An LLM model.
        text_qa_template (Optional[BasePromptTemplate]): Text QA Prompt Template.
        image_qa_template (Optional[BasePromptTemplate]): Image QA Prompt Template.
        node_postprocessors (Optional[List[BaseNodePostprocessor]]): Node Postprocessors.
        callback_manager (Optional[CallbackManager]): A callback manager.

    """
    def __init__(self, retriever: MultiModalVectorIndexRetriever, multi_modal_llm: Optional[LLM] = ..., text_qa_template: Optional[BasePromptTemplate] = ..., image_qa_template: Optional[BasePromptTemplate] = ..., node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., callback_manager: Optional[CallbackManager] = ..., **kwargs: Any) -> None:
        ...
    
    def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    async def aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    def synthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    
    async def asynthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    
    def image_query(self, image_path: QueryType, prompt_str: str) -> RESPONSE_TYPE:
        """Answer a image query."""
        ...
    
    @property
    def retriever(self) -> MultiModalVectorIndexRetriever:
        """Get the retriever object."""
        ...
    


