"""
This type stub file was generated by pyright.
"""

from typing import Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.evaluation.base import BaseEvaluator
from llama_index.core.evaluation.guideline import GuidelineEvaluator
from llama_index.core.indices.query.query_transform.feedback_transform import FeedbackQueryTransformation

logger = ...
class RetryQueryEngine(BaseQueryEngine):
    """
    Does retry on query engine if it fails evaluation.

    Args:
        query_engine (BaseQueryEngine): A query engine object
        evaluator (BaseEvaluator): An evaluator object
        max_retries (int): Maximum number of retries
        callback_manager (Optional[CallbackManager]): A callback manager object

    """
    def __init__(self, query_engine: BaseQueryEngine, evaluator: BaseEvaluator, max_retries: int = ..., callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    


class RetryGuidelineQueryEngine(BaseQueryEngine):
    """
    Does retry with evaluator feedback
    if query engine fails evaluation.

    Args:
        query_engine (BaseQueryEngine): A query engine object
        guideline_evaluator (GuidelineEvaluator): A guideline evaluator object
        resynthesize_query (bool): Whether to resynthesize query
        max_retries (int): Maximum number of retries
        callback_manager (Optional[CallbackManager]): A callback manager object

    """
    def __init__(self, query_engine: BaseQueryEngine, guideline_evaluator: GuidelineEvaluator, resynthesize_query: bool = ..., max_retries: int = ..., callback_manager: Optional[CallbackManager] = ..., query_transformer: Optional[FeedbackQueryTransformation] = ...) -> None:
        ...
    


