"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, List, Optional, Sequence
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.base_selector import BaseSelector
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.llms.llm import LLM
from llama_index.core.objects.base import ObjectRetriever
from llama_index.core.response_synthesizers import TreeSummarize
from llama_index.core.schema import BaseNode, QueryBundle
from llama_index.core.tools.query_engine import QueryEngineTool
from llama_index.core.tools.types import ToolMetadata

logger = ...
def combine_responses(summarizer: TreeSummarize, responses: List[RESPONSE_TYPE], query_bundle: QueryBundle) -> RESPONSE_TYPE:
    """Combine multiple response from sub-engines."""
    ...

async def acombine_responses(summarizer: TreeSummarize, responses: List[RESPONSE_TYPE], query_bundle: QueryBundle) -> RESPONSE_TYPE:
    """Async combine multiple response from sub-engines."""
    ...

class RouterQueryEngine(BaseQueryEngine):
    """
    Router query engine.

    Selects one out of several candidate query engines to execute a query.

    Args:
        selector (BaseSelector): A selector that chooses one out of many options based
            on each candidate's metadata and query.
        query_engine_tools (Sequence[QueryEngineTool]): A sequence of candidate
            query engines. They must be wrapped as tools to expose metadata to
            the selector.
        summarizer (Optional[TreeSummarize]): Tree summarizer to summarize sub-results.

    """
    def __init__(self, selector: BaseSelector, query_engine_tools: Sequence[QueryEngineTool], llm: Optional[LLM] = ..., summarizer: Optional[TreeSummarize] = ..., verbose: bool = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, query_engine_tools: Sequence[QueryEngineTool], llm: Optional[LLM] = ..., selector: Optional[BaseSelector] = ..., summarizer: Optional[TreeSummarize] = ..., select_multi: bool = ..., **kwargs: Any) -> RouterQueryEngine:
        ...
    


def default_node_to_metadata_fn(node: BaseNode) -> ToolMetadata:
    """
    Default node to metadata function.

    We use the node's text as the Tool description.

    """
    ...

class RetrieverRouterQueryEngine(BaseQueryEngine):
    """
    Retriever-based router query engine.

    NOTE: this is deprecated, please use our new ToolRetrieverRouterQueryEngine

    Use a retriever to select a set of Nodes. Each node will be converted
    into a ToolMetadata object, and also used to retrieve a query engine, to form
    a QueryEngineTool.

    NOTE: this is a beta feature. We are figuring out the right interface
    between the retriever and query engine.

    Args:
        selector (BaseSelector): A selector that chooses one out of many options based
            on each candidate's metadata and query.
        query_engine_tools (Sequence[QueryEngineTool]): A sequence of candidate
            query engines. They must be wrapped as tools to expose metadata to
            the selector.
        callback_manager (Optional[CallbackManager]): A callback manager.

    """
    def __init__(self, retriever: BaseRetriever, node_to_query_engine_fn: Callable, callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    


class ToolRetrieverRouterQueryEngine(BaseQueryEngine):
    """
    Tool Retriever router query engine.

    Selects a set of candidate query engines to execute a query.

    Args:
        retriever (ObjectRetriever): A retriever that retrieves a set of
            query engine tools.
        summarizer (Optional[TreeSummarize]): Tree summarizer to summarize sub-results.

    """
    def __init__(self, retriever: ObjectRetriever[QueryEngineTool], llm: Optional[LLM] = ..., summarizer: Optional[TreeSummarize] = ...) -> None:
        ...
    


