"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, Union
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.query.query_transform.base import BaseQueryTransform
from llama_index.core.llms import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.schema import QueryBundle
from llama_index.core.selectors.llm_selectors import LLMSingleSelector
from llama_index.core.selectors.pydantic_selectors import PydanticSingleSelector
from llama_index.core.tools.query_engine import QueryEngineTool

"""SQL Join query engine."""
logger = ...
DEFAULT_SQL_JOIN_SYNTHESIS_PROMPT_TMPL = ...
DEFAULT_SQL_JOIN_SYNTHESIS_PROMPT = ...
DEFAULT_SQL_AUGMENT_TRANSFORM_PROMPT_TMPL = ...
DEFAULT_SQL_AUGMENT_TRANSFORM_PROMPT = ...
class SQLAugmentQueryTransform(BaseQueryTransform):
    """
    SQL Augment Query Transform.

    This query transform will transform the query into a more specific query
    after augmenting with SQL results.

    Args:
        llm (LLM): LLM to use for query transformation.
        sql_augment_transform_prompt (BasePromptTemplate): PromptTemplate to use
            for query transformation.
        check_stop_parser (Optional[Callable[[str], bool]]): Check stop function.

    """
    def __init__(self, llm: Optional[LLM] = ..., sql_augment_transform_prompt: Optional[BasePromptTemplate] = ..., check_stop_parser: Optional[Callable[[QueryBundle], bool]] = ...) -> None:
        """Initialize params."""
        ...
    
    def check_stop(self, query_bundle: QueryBundle) -> bool:
        """Check if query indicates stop."""
        ...
    


class SQLJoinQueryEngine(BaseQueryEngine):
    """
    SQL Join Query Engine.

    This query engine can "Join" a SQL database results
    with another query engine.
    It can decide it needs to query the SQL database or the other query engine.
    If it decides to query the SQL database, it will first query the SQL database,
    whether to augment information with retrieved results from the other query engine.

    Args:
        sql_query_tool (QueryEngineTool): Query engine tool for SQL database.
            other_query_tool (QueryEngineTool): Other query engine tool.
        selector (Optional[Union[LLMSingleSelector, PydanticSingleSelector]]):
            Selector to use.
        sql_join_synthesis_prompt (Optional[BasePromptTemplate]):
            PromptTemplate to use for SQL join synthesis.
        sql_augment_query_transform (Optional[SQLAugmentQueryTransform]): Query
            transform to use for SQL augmentation.
        use_sql_join_synthesis (bool): Whether to use SQL join synthesis.
        callback_manager (Optional[CallbackManager]): Callback manager to use.
        verbose (bool): Whether to print intermediate results.

    """
    def __init__(self, sql_query_tool: QueryEngineTool, other_query_tool: QueryEngineTool, selector: Optional[Union[LLMSingleSelector, PydanticSingleSelector]] = ..., llm: Optional[LLM] = ..., sql_join_synthesis_prompt: Optional[BasePromptTemplate] = ..., sql_augment_query_transform: Optional[SQLAugmentQueryTransform] = ..., use_sql_join_synthesis: bool = ..., callback_manager: Optional[CallbackManager] = ..., verbose: bool = ..., streaming: bool = ...) -> None:
        """Initialize params."""
        ...
    


