"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Sequence
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.query.query_transform.base import BaseQueryTransform
from llama_index.core.schema import NodeWithScore, QueryBundle

class TransformQueryEngine(BaseQueryEngine):
    """
    Transform query engine.

    Applies a query transform to a query bundle before passing
        it to a query engine.

    Args:
        query_engine (BaseQueryEngine): A query engine object.
        query_transform (BaseQueryTransform): A query transform object.
        transform_metadata (Optional[dict]): metadata to pass to the
            query transform.
        callback_manager (Optional[CallbackManager]): A callback manager.

    """
    def __init__(self, query_engine: BaseQueryEngine, query_transform: BaseQueryTransform, transform_metadata: Optional[dict] = ..., callback_manager: Optional[CallbackManager] = ...) -> None:
        ...
    
    def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        ...
    
    def synthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    
    async def asynthesize(self, query_bundle: QueryBundle, nodes: List[NodeWithScore], additional_source_nodes: Optional[Sequence[NodeWithScore]] = ...) -> RESPONSE_TYPE:
        ...
    


