"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional
from fsspec import AbstractFileSystem
from llama_index.core.readers.base import BaseReader
from llama_index.core.schema import Document

"""
Tabular parser.

Contains parsers for tabular data files.

"""
class CSVReader(BaseReader):
    """
    CSV parser.

    Args:
        concat_rows (bool): whether to concatenate all rows into one document.
            If set to False, a Document will be created for each row.
            True by default.

    """
    def __init__(self, *args: Any, concat_rows: bool = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ...) -> List[Document]:
        """
        Parse file.

        Returns:
            Union[str, List[str]]: a string or a List of strings.

        """
        ...
    


class PandasCSVReader(BaseReader):
    r"""
    Pandas-based CSV parser.

    Parses CSVs using the separator detection from Pandas `read_csv`function.
    If special parameters are required, use the `pandas_config` dict.

    Args:
        concat_rows (bool): whether to concatenate all rows into one document.
            If set to False, a Document will be created for each row.
            True by default.

        col_joiner (str): Separator to use for joining cols per row.
            Set to ", " by default.

        row_joiner (str): Separator to use for joining each row.
            Only used when `concat_rows=True`.
            Set to "\n" by default.

        pandas_config (dict): Options for the `pandas.read_csv` function call.
            Refer to https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
            for more information.
            Set to empty dict by default, this means pandas will try to figure
            out the separators, table head, etc. on its own.

    """
    def __init__(self, *args: Any, concat_rows: bool = ..., col_joiner: str = ..., row_joiner: str = ..., pandas_config: dict = ..., **kwargs: Any) -> None:
        """Init params."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parse file."""
        ...
    


class PandasExcelReader(BaseReader):
    """
    Custom Excel parser that includes header names in each row.

    Parses Excel files using Pandas' `read_excel` function, but formats
    each row to include the header name, for example: "name: joao, position: analyst".
    The first row (header) is not included in the generated documents.

    Args:
        concat_rows (bool): Determines whether to concatenate all rows into one document.
            If set to False, one Document is created for each row.
            Defaults to True.
        sheet_name (str | int | None): Defaults to None, meaning all sheets.
            Alternatively, pass a string or an integer to specify the sheet to be read.
        field_separator (str): Character or string to separate each field. Default: ", ".
        key_value_separator (str): Character or string to separate the key from the value. Default: ": ".
        pandas_config (dict): Options for the `pandas.read_excel` function call.
            Refer to https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
            for more details.
            Defaults to an empty dictionary.

    """
    def __init__(self, *args: Any, concat_rows: bool = ..., sheet_name=..., field_separator: str = ..., key_value_separator: str = ..., pandas_config: dict = ..., **kwargs: Any) -> None:
        """Initializes the parameters."""
        ...
    
    def load_data(self, file: Path, extra_info: Optional[Dict] = ..., fs: Optional[AbstractFileSystem] = ...) -> List[Document]:
        """Parses the file."""
        ...
    


