"""
This type stub file was generated by pyright.
"""

from llama_index.core.tools.types import BaseTool, ToolOutput
from typing import Sequence, TYPE_CHECKING
from llama_index.core.llms.llm import ToolSelection

if TYPE_CHECKING:
    ...
def call_tool(tool: BaseTool, arguments: dict) -> ToolOutput:
    """Call a tool with arguments."""
    ...

async def acall_tool(tool: BaseTool, arguments: dict) -> ToolOutput:
    """Call a tool with arguments asynchronously."""
    ...

def call_tool_with_selection(tool_call: ToolSelection, tools: Sequence[BaseTool], verbose: bool = ...) -> ToolOutput:
    ...

async def acall_tool_with_selection(tool_call: ToolSelection, tools: Sequence[BaseTool], verbose: bool = ...) -> ToolOutput:
    ...

