"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type
from deprecated import deprecated
from llama_index.core.tools.tool_spec.base import BaseToolSpec

"""Download tool from Llama Index. Deprecated."""
@deprecated("`download_tool()` is deprecated. " "Please install tool using pip install directly instead.")
def download_tool(tool_class: str, llama_hub_url: str = ..., refresh_cache: bool = ..., custom_path: Optional[str] = ...) -> Type[BaseToolSpec]:
    """
    Download a single tool from Llama Hub.

    Args:
        tool_class: The name of the tool class you want to download,
            such as `GmailToolSpec`.
        refresh_cache: If true, the local cache will be skipped and the
            loader will be fetched directly from the remote repo.
        custom_path: Custom dirpath to download loader into.

    Returns:
        A Loader.

    """
    ...

