"""
This type stub file was generated by pyright.
"""

from typing import Any, Awaitable, Callable, Dict, Optional, TYPE_CHECKING, Tuple, Type, Union
from llama_index.core.bridge.langchain import StructuredTool, Tool
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.tools.types import AsyncBaseTool, ToolMetadata, ToolOutput

if TYPE_CHECKING:
    ...
AsyncCallable = Callable[..., Awaitable[Any]]
def sync_to_async(fn: Callable[..., Any]) -> AsyncCallable:
    """Sync to async."""
    ...

def async_to_sync(func_async: AsyncCallable) -> Callable:
    """Async to sync."""
    ...

CallbackReturn = Optional[Union[ToolOutput, str]]
class FunctionTool(AsyncBaseTool):
    """
    Function Tool.

    A tool that takes in a function, optionally handles workflow context,
    and allows the use of callbacks. The callback can return a new ToolOutput
    to override the default one or a string that will be used as the final content.
    """
    def __init__(self, fn: Optional[Callable[..., Any]] = ..., metadata: Optional[ToolMetadata] = ..., async_fn: Optional[AsyncCallable] = ..., callback: Optional[Callable[..., Any]] = ..., async_callback: Optional[Callable[..., Any]] = ..., partial_params: Optional[Dict[str, Any]] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, fn: Optional[Callable[..., Any]] = ..., name: Optional[str] = ..., description: Optional[str] = ..., return_direct: bool = ..., fn_schema: Optional[Type[BaseModel]] = ..., async_fn: Optional[AsyncCallable] = ..., tool_metadata: Optional[ToolMetadata] = ..., callback: Optional[Callable[[Any], Any]] = ..., async_callback: Optional[AsyncCallable] = ..., partial_params: Optional[Dict[str, Any]] = ...) -> FunctionTool:
        ...
    
    @property
    def metadata(self) -> ToolMetadata:
        """Metadata."""
        ...
    
    @property
    def fn(self) -> Callable[..., Any]:
        """Function."""
        ...
    
    @property
    def async_fn(self) -> AsyncCallable:
        """Async function."""
        ...
    
    @property
    def real_fn(self) -> Union[Callable[..., Any], AsyncCallable]:
        """Real function."""
        ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    def call(self, *args: Any, **kwargs: Any) -> ToolOutput:
        """Sync Call."""
        ...
    
    async def acall(self, *args: Any, **kwargs: Any) -> ToolOutput:
        """Async Call."""
        ...
    
    def to_langchain_tool(self, **langchain_tool_kwargs: Any) -> Tool:
        """To langchain tool."""
        ...
    
    def to_langchain_structured_tool(self, **langchain_tool_kwargs: Any) -> StructuredTool:
        """To langchain structured tool."""
        ...
    
    @staticmethod
    def extract_param_docs(docstring: str, fn_params: Optional[set] = ...) -> Tuple[dict, set]:
        """
        Parses param descriptions from a docstring.

        Returns:
            - param_docs: Only for params in fn_params with non-conflicting descriptions.
            - unknown_params: Params found in docstring but not in fn_params (ignored in final output).

        """
        ...
    


