"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, TYPE_CHECKING
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.langchain_helpers.agents.tools import LlamaIndexTool
from llama_index.core.tools.types import AsyncBaseTool, ToolMetadata, ToolOutput

if TYPE_CHECKING:
    ...
DEFAULT_NAME = ...
DEFAULT_DESCRIPTION = ...
class QueryEngineTool(AsyncBaseTool):
    """
    Query engine tool.

    A tool making use of a query engine.

    Args:
        query_engine (BaseQueryEngine): A query engine.
        metadata (ToolMetadata): The associated metadata of the query engine.

    """
    def __init__(self, query_engine: BaseQueryEngine, metadata: ToolMetadata, resolve_input_errors: bool = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, query_engine: BaseQueryEngine, name: Optional[str] = ..., description: Optional[str] = ..., return_direct: bool = ..., resolve_input_errors: bool = ...) -> QueryEngineTool:
        ...
    
    @property
    def query_engine(self) -> BaseQueryEngine:
        ...
    
    @property
    def metadata(self) -> ToolMetadata:
        ...
    
    def call(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    async def acall(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    def as_langchain_tool(self) -> LlamaIndexTool:
        ...
    


