"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, TYPE_CHECKING
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.langchain_helpers.agents.tools import LlamaIndexTool
from llama_index.core.tools.types import AsyncBaseTool, ToolMetadata, ToolOutput
from llama_index.core.postprocessor.types import BaseNodePostprocessor

"""Retriever tool."""
if TYPE_CHECKING:
    ...
DEFAULT_NAME = ...
DEFAULT_DESCRIPTION = ...
class RetrieverTool(AsyncBaseTool):
    """
    Retriever tool.

    A tool making use of a retriever.

    Args:
        retriever (BaseRetriever): A retriever.
        metadata (ToolMetadata): The associated metadata of the query engine.
        node_postprocessors (Optional[List[BaseNodePostprocessor]]): A list of
            node postprocessors.

    """
    def __init__(self, retriever: BaseRetriever, metadata: ToolMetadata, node_postprocessors: Optional[List[BaseNodePostprocessor]] = ...) -> None:
        ...
    
    @classmethod
    def from_defaults(cls, retriever: BaseRetriever, node_postprocessors: Optional[List[BaseNodePostprocessor]] = ..., name: Optional[str] = ..., description: Optional[str] = ...) -> RetrieverTool:
        ...
    
    @property
    def retriever(self) -> BaseRetriever:
        ...
    
    @property
    def metadata(self) -> ToolMetadata:
        ...
    
    def call(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    async def acall(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    def as_langchain_tool(self) -> LlamaIndexTool:
        ...
    


