"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, TYPE_CHECKING, Type
from llama_index.core.base.llms.types import ContentBlock
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.bridge.langchain import StructuredTool, Tool
from deprecated import deprecated
from llama_index.core.bridge.pydantic import BaseModel

if TYPE_CHECKING:
    ...
class DefaultToolFnSchema(BaseModel):
    """Default tool function Schema."""
    input: str
    ...


@dataclass
class ToolMetadata:
    description: str
    name: Optional[str] = ...
    fn_schema: Optional[Type[BaseModel]] = ...
    return_direct: bool = ...
    def get_parameters_dict(self) -> dict:
        ...
    
    @property
    def fn_schema_str(self) -> str:
        """Get fn schema as string."""
        ...
    
    def get_name(self) -> str:
        """Get name."""
        ...
    
    @deprecated("Deprecated in favor of `to_openai_tool`, which should be used instead.")
    def to_openai_function(self) -> Dict[str, Any]:
        """
        Deprecated and replaced by `to_openai_tool`.
        The name and arguments of a function that should be called, as generated by the
        model.
        """
        ...
    
    def to_openai_tool(self, skip_length_check: bool = ...) -> Dict[str, Any]:
        """To OpenAI tool."""
        ...
    


class ToolOutput(BaseModel):
    """Tool output."""
    blocks: List[ContentBlock]
    tool_name: str
    raw_input: Dict[str, Any]
    raw_output: Any
    is_error: bool = ...
    def __init__(self, tool_name: str, content: Optional[str] = ..., blocks: Optional[List[ContentBlock]] = ..., raw_input: Optional[Dict[str, Any]] = ..., raw_output: Optional[Any] = ..., is_error: bool = ...) -> None:
        ...
    
    @property
    def content(self) -> str:
        """Get the content of the tool output."""
        ...
    
    @content.setter
    def content(self, content: str) -> None:
        """Set the content of the tool output."""
        ...
    
    def __str__(self) -> str:
        """String."""
        ...
    


class BaseTool(DispatcherSpanMixin):
    @property
    @abstractmethod
    def metadata(self) -> ToolMetadata:
        ...
    
    @abstractmethod
    def __call__(self, input: Any) -> ToolOutput:
        ...
    
    def to_langchain_tool(self, **langchain_tool_kwargs: Any) -> Tool:
        """To langchain tool."""
        ...
    
    def to_langchain_structured_tool(self, **langchain_tool_kwargs: Any) -> StructuredTool:
        """To langchain structured tool."""
        ...
    


class AsyncBaseTool(BaseTool):
    """
    Base-level tool class that is backwards compatible with the old tool spec but also
    supports async.
    """
    def __call__(self, *args: Any, **kwargs: Any) -> ToolOutput:
        ...
    
    @abstractmethod
    def call(self, input: Any) -> ToolOutput:
        """
        This is the method that should be implemented by the tool developer.
        """
        ...
    
    @abstractmethod
    async def acall(self, input: Any) -> ToolOutput:
        """
        This is the async version of the call method.
        Should also be implemented by the tool developer as an
        async-compatible implementation.
        """
        ...
    


class BaseToolAsyncAdapter(AsyncBaseTool):
    """
    Adapter class that allows a synchronous tool to be used as an async tool.
    """
    def __init__(self, tool: BaseTool) -> None:
        ...
    
    @property
    def metadata(self) -> ToolMetadata:
        ...
    
    def call(self, input: Any) -> ToolOutput:
        ...
    
    async def acall(self, input: Any) -> ToolOutput:
        ...
    


def adapt_to_async_tool(tool: BaseTool) -> AsyncBaseTool:
    """
    Converts a synchronous tool to an async tool.
    """
    ...

