"""
This type stub file was generated by pyright.
"""

from typing import Any, Awaitable, Callable, List, Optional, Tuple, Type, Union
from llama_index.core.bridge.pydantic import BaseModel

def create_schema_from_function(name: str, func: Union[Callable[..., Any], Callable[..., Awaitable[Any]]], additional_fields: Optional[List[Union[Tuple[str, Type, Any], Tuple[str, Type]]]] = ..., ignore_fields: Optional[List[str]] = ...) -> Type[BaseModel]:
    """
    Create schema from function.
    - Automatically adds json_schema_extra for basic Python types such as:
        - datetime.date -> format: "date"
        - datetime.datetime -> format: "date-time"
        - datetime.time -> format: "time"
    """
    ...

