"""
This type stub file was generated by pyright.
"""

from llama_index.core.base.llms.types import ChatMessage, MessageRole
from llama_index.core.prompts.base import BasePromptTemplate, ChatPromptTemplate, LangchainPromptTemplate, Prompt, PromptTemplate, PromptType, SelectorPromptTemplate
from llama_index.core.prompts.rich import RichPromptTemplate
from llama_index.core.prompts.display_utils import display_prompt_dict

"""Prompt class."""
__all__ = ["Prompt", "PromptTemplate", "SelectorPromptTemplate", "ChatPromptTemplate", "LangchainPromptTemplate", "BasePromptTemplate", "PromptType", "ChatMessage", "MessageRole", "display_prompt_dict", "RichPromptTemplate"]
