"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Optional, Sequence, TYPE_CHECKING, Tuple, Union
from typing_extensions import Annotated
from llama_index.core.bridge.pydantic import BaseModel, PlainSerializer, SerializeAsAny, WithJsonSchema
from llama_index.core.bridge.langchain import BasePromptTemplate as LangchainTemplate, ConditionalPromptSelector as LangchainSelector
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.base.llms.base import BaseLLM
from llama_index.core.types import BaseOutputParser

"""Prompts."""
if TYPE_CHECKING:
    ...
AnnotatedCallable = Annotated[Callable, WithJsonSchema({ "type": "string" }), WithJsonSchema({ "type": "string" }), PlainSerializer(lambda x: f"{x.__module__}.{x.__name__}", return_type=str),]
class BasePromptTemplate(BaseModel, ABC):
    model_config = ...
    metadata: Dict[str, Any]
    template_vars: List[str]
    kwargs: Dict[str, str]
    output_parser: Optional[BaseOutputParser]
    template_var_mappings: Optional[Dict[str, Any]] = ...
    function_mappings: Optional[Dict[str, AnnotatedCallable]] = ...
    @abstractmethod
    def partial_format(self, **kwargs: Any) -> BasePromptTemplate:
        ...
    
    @abstractmethod
    def format(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> str:
        ...
    
    @abstractmethod
    def format_messages(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> List[ChatMessage]:
        ...
    
    @abstractmethod
    def get_template(self, llm: Optional[BaseLLM] = ...) -> str:
        ...
    


class PromptTemplate(BasePromptTemplate):
    template: str
    def __init__(self, template: str, prompt_type: str = ..., output_parser: Optional[BaseOutputParser] = ..., metadata: Optional[Dict[str, Any]] = ..., template_var_mappings: Optional[Dict[str, Any]] = ..., function_mappings: Optional[Dict[str, Callable]] = ..., **kwargs: Any) -> None:
        ...
    
    def partial_format(self, **kwargs: Any) -> PromptTemplate:
        """Partially format the prompt."""
        ...
    
    def format(self, llm: Optional[BaseLLM] = ..., completion_to_prompt: Optional[Callable[[str], str]] = ..., **kwargs: Any) -> str:
        """Format the prompt into a string."""
        ...
    
    def format_messages(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> List[ChatMessage]:
        """Format the prompt into a list of chat messages."""
        ...
    
    def get_template(self, llm: Optional[BaseLLM] = ...) -> str:
        ...
    


class ChatPromptTemplate(BasePromptTemplate):
    message_templates: List[ChatMessage]
    def __init__(self, message_templates: Sequence[ChatMessage], prompt_type: str = ..., output_parser: Optional[BaseOutputParser] = ..., metadata: Optional[Dict[str, Any]] = ..., template_var_mappings: Optional[Dict[str, Any]] = ..., function_mappings: Optional[Dict[str, Callable]] = ..., **kwargs: Any) -> None:
        ...
    
    @classmethod
    def from_messages(cls, message_templates: Union[List[Tuple[str, str]], List[ChatMessage]], **kwargs: Any) -> ChatPromptTemplate:
        """From messages."""
        ...
    
    def partial_format(self, **kwargs: Any) -> ChatPromptTemplate:
        ...
    
    def format(self, llm: Optional[BaseLLM] = ..., messages_to_prompt: Optional[Callable[[Sequence[ChatMessage]], str]] = ..., **kwargs: Any) -> str:
        ...
    
    def format_messages(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> List[ChatMessage]:
        ...
    
    def get_template(self, llm: Optional[BaseLLM] = ...) -> str:
        ...
    


class SelectorPromptTemplate(BasePromptTemplate):
    default_template: SerializeAsAny[BasePromptTemplate]
    conditionals: Optional[Sequence[Tuple[Callable[[BaseLLM], bool], BasePromptTemplate]]] = ...
    def __init__(self, default_template: BasePromptTemplate, conditionals: Optional[Sequence[Tuple[Callable[[BaseLLM], bool], BasePromptTemplate]]] = ...) -> None:
        ...
    
    def select(self, llm: Optional[BaseLLM] = ...) -> BasePromptTemplate:
        ...
    
    def partial_format(self, **kwargs: Any) -> SelectorPromptTemplate:
        ...
    
    def format(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> str:
        """Format the prompt into a string."""
        ...
    
    def format_messages(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> List[ChatMessage]:
        """Format the prompt into a list of chat messages."""
        ...
    
    def get_template(self, llm: Optional[BaseLLM] = ...) -> str:
        ...
    


class LangchainPromptTemplate(BasePromptTemplate):
    selector: Any
    requires_langchain_llm: bool = ...
    def __init__(self, template: Optional[LangchainTemplate] = ..., selector: Optional[LangchainSelector] = ..., output_parser: Optional[BaseOutputParser] = ..., prompt_type: str = ..., metadata: Optional[Dict[str, Any]] = ..., template_var_mappings: Optional[Dict[str, Any]] = ..., function_mappings: Optional[Dict[str, Callable]] = ..., requires_langchain_llm: bool = ...) -> None:
        ...
    
    def partial_format(self, **kwargs: Any) -> BasePromptTemplate:
        """Partially format the prompt."""
        ...
    
    def format(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> str:
        """Format the prompt into a string."""
        ...
    
    def format_messages(self, llm: Optional[BaseLLM] = ..., **kwargs: Any) -> List[ChatMessage]:
        """Format the prompt into a list of chat messages."""
        ...
    
    def get_template(self, llm: Optional[BaseLLM] = ...) -> str:
        ...
    


Prompt = PromptTemplate
