"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Dict, Union
from llama_index.core.prompts.base import BasePromptTemplate

"""Prompt Mixin."""
HasPromptType = Union["PromptMixin", BasePromptTemplate]
PromptDictType = Dict[str, BasePromptTemplate]
PromptMixinType = Dict[str, "PromptMixin"]
class PromptMixin(ABC):
    """
    Prompt mixin.

    This mixin is used in other modules, like query engines, response synthesizers.
    This shows that the module supports getting, setting prompts,
    both within the immediate module as well as child modules.

    """
    def get_prompts(self) -> Dict[str, BasePromptTemplate]:
        """Get a prompt."""
        ...
    
    def update_prompts(self, prompts_dict: Dict[str, BasePromptTemplate]) -> None:
        """
        Update prompts.

        Other prompts will remain in place.

        """
        ...
    


