"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from llama_index.core.base.llms.base import BaseLLM
from llama_index.core.base.llms.types import ContentBlock

class SafeFormatter:
    """Safe string formatter that does not raise KeyError if key is missing."""
    def __init__(self, format_dict: Optional[Dict[str, str]] = ...) -> None:
        ...
    
    def format(self, format_string: str) -> str:
        ...
    
    def parse(self, format_string: str) -> List[str]:
        ...
    


def format_string(string_to_format: str, **kwargs: str) -> str:
    """Format a string with kwargs."""
    ...

def format_content_blocks(content_blocks: List[ContentBlock], **kwargs: str) -> List[ContentBlock]:
    """Format content blocks with kwargs."""
    ...

def get_template_vars(template_str: str) -> List[str]:
    """Get template variables from a template string."""
    ...

def is_chat_model(llm: BaseLLM) -> bool:
    ...

