"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from llama_index.core.bridge.pydantic import SerializeAsAny
from llama_index.core.llms.llm import LLM
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import BasePromptTemplate

"""LLM reranker."""
class LLMRerank(BaseNodePostprocessor):
    """LLM-based reranker."""
    top_n: int = ...
    choice_select_prompt: SerializeAsAny[BasePromptTemplate] = ...
    choice_batch_size: int = ...
    llm: LLM = ...
    _format_node_batch_fn: Callable = ...
    _parse_choice_select_answer_fn: Callable = ...
    def __init__(self, llm: Optional[LLM] = ..., choice_select_prompt: Optional[BasePromptTemplate] = ..., choice_batch_size: int = ..., format_node_batch_fn: Optional[Callable] = ..., parse_choice_select_answer_fn: Optional[Callable] = ..., top_n: int = ...) -> None:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


