"""
This type stub file was generated by pyright.
"""

from llama_index.core.postprocessor.types import BaseNodePostprocessor

class MetadataReplacementPostProcessor(BaseNodePostprocessor):
    target_metadata_key: str = ...
    def __init__(self, target_metadata_key: str) -> None:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


