"""
This type stub file was generated by pyright.
"""

from typing import Optional
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.bridge.pydantic import SerializeAsAny
from llama_index.core.postprocessor.types import BaseNodePostprocessor

"""Node recency post-processor."""
class FixedRecencyPostprocessor(BaseNodePostprocessor):
    """
    Fixed Recency post-processor.

    This post-processor does the following steps orders nodes by date.

    Assumes the date_key corresponds to a date field in the metadata.
    """
    top_k: int = ...
    date_key: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


DEFAULT_QUERY_EMBEDDING_TMPL = ...
class EmbeddingRecencyPostprocessor(BaseNodePostprocessor):
    """Embedding Recency post-processor."""
    embed_model: SerializeAsAny[BaseEmbedding] = ...
    date_key: str = ...
    similarity_cutoff: float = ...
    query_embedding_tmpl: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


class TimeWeightedPostprocessor(BaseNodePostprocessor):
    """
    Time-weighted post-processor.

    Reranks a set of nodes based on their recency.

    """
    time_decay: float = ...
    last_accessed_key: str = ...
    time_access_refresh: bool = ...
    now: Optional[float] = ...
    top_k: int = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


