"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from llama_index.core.bridge.pydantic import SerializeAsAny
from llama_index.core.llms import LLM
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.response_synthesizers import ResponseMode
from llama_index.core.schema import NodeWithScore
from llama_index.core.storage.docstore import BaseDocumentStore

"""Node postprocessor."""
logger = ...
class KeywordNodePostprocessor(BaseNodePostprocessor):
    """Keyword-based Node processor."""
    required_keywords: List[str] = ...
    exclude_keywords: List[str] = ...
    lang: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


class SimilarityPostprocessor(BaseNodePostprocessor):
    """Similarity-based Node processor."""
    similarity_cutoff: float = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


def get_forward_nodes(node_with_score: NodeWithScore, num_nodes: int, docstore: BaseDocumentStore) -> Dict[str, NodeWithScore]:
    """Get forward nodes."""
    ...

def get_backward_nodes(node_with_score: NodeWithScore, num_nodes: int, docstore: BaseDocumentStore) -> Dict[str, NodeWithScore]:
    """Get backward nodes."""
    ...

class PrevNextNodePostprocessor(BaseNodePostprocessor):
    """
    Previous/Next Node post-processor.

    Allows users to fetch additional nodes from the document store,
    based on the relationships of the nodes.

    NOTE: this is a beta feature.

    Args:
        docstore (BaseDocumentStore): The document store.
        num_nodes (int): The number of nodes to return (default: 1)
        mode (str): The mode of the post-processor.
            Can be "previous", "next", or "both.

    """
    docstore: BaseDocumentStore
    num_nodes: int = ...
    mode: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


DEFAULT_INFER_PREV_NEXT_TMPL = ...
DEFAULT_REFINE_INFER_PREV_NEXT_TMPL = ...
class AutoPrevNextNodePostprocessor(BaseNodePostprocessor):
    """
    Previous/Next Node post-processor.

    Allows users to fetch additional nodes from the document store,
    based on the prev/next relationships of the nodes.

    NOTE: difference with PrevNextPostprocessor is that
    this infers forward/backwards direction.

    NOTE: this is a beta feature.

    Args:
        docstore (BaseDocumentStore): The document store.
        num_nodes (int): The number of nodes to return (default: 1)
        infer_prev_next_tmpl (str): The template to use for inference.
            Required fields are {context_str} and {query_str}.

    """
    model_config = ...
    docstore: BaseDocumentStore
    llm: Optional[SerializeAsAny[LLM]] = ...
    num_nodes: int = ...
    infer_prev_next_tmpl: str = ...
    refine_prev_next_tmpl: str = ...
    verbose: bool = ...
    response_mode: ResponseMode = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    


class LongContextReorder(BaseNodePostprocessor):
    """
    Models struggle to access significant details found
    in the center of extended contexts. A study
    (https://arxiv.org/abs/2307.03172) observed that the best
    performance typically arises when crucial data is positioned
    at the start or conclusion of the input context. Additionally,
    as the input context lengthens, performance drops notably, even
    in models designed for long contexts.".
    """
    @classmethod
    def class_name(cls) -> str:
        ...
    


