"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.postprocessor.types import BaseNodePostprocessor

"""Optimization related classes and functions."""
logger = ...
class SentenceEmbeddingOptimizer(BaseNodePostprocessor):
    """Optimization of a text chunk given the query by shortening the input text."""
    percentile_cutoff: Optional[float] = ...
    threshold_cutoff: Optional[float] = ...
    _embed_model: BaseEmbedding = ...
    _tokenizer_fn: Callable[[str], List[str]] = ...
    context_before: Optional[int] = ...
    context_after: Optional[int] = ...
    def __init__(self, embed_model: Optional[BaseEmbedding] = ..., percentile_cutoff: Optional[float] = ..., threshold_cutoff: Optional[float] = ..., tokenizer_fn: Optional[Callable[[str], List[str]]] = ..., context_before: Optional[int] = ..., context_after: Optional[int] = ...) -> None:
        """
        Optimizer class that is passed into BaseGPTIndexQuery.

        Should be set like this:

        .. code-block:: python
        from llama_index.core.optimization.optimizer import Optimizer
        optimizer = SentenceEmbeddingOptimizer(
                        percentile_cutoff=0.5
                        this means that the top 50% of sentences will be used.
                        Alternatively, you can set the cutoff using a threshold
                        on the similarity score. In this case only sentences with a
                        similarity score higher than the threshold will be used.
                        threshold_cutoff=0.7
                        these cutoffs can also be used together.
                    )

        query_engine = index.as_query_engine(
            optimizer=optimizer
        )
        response = query_engine.query("<query_str>")
        """
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


