"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, Tuple
from llama_index.core.llms.llm import LLM
from llama_index.core.postprocessor.types import BaseNodePostprocessor

"""PII postprocessor."""
DEFAULT_PII_TMPL = ...
class PIINodePostprocessor(BaseNodePostprocessor):
    """
    PII Node processor.

    NOTE: this is a beta feature, the API might change.

    Args:
        llm (LLM): The local LLM to use for prediction.

    """
    llm: LLM
    pii_str_tmpl: str = ...
    pii_node_info_key: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def mask_pii(self, text: str) -> Tuple[str, Dict]:
        """Mask PII in text."""
        ...
    


class NERPIINodePostprocessor(BaseNodePostprocessor):
    """
    NER PII Node processor.

    Uses a HF transformers model.

    """
    pii_node_info_key: str = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def mask_pii(self, ner: Callable, text: str) -> Tuple[str, Dict]:
        """Mask PII in text."""
        ...
    


