"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import List, Optional
from llama_index.core.callbacks import CallbackManager
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.schema import BaseComponent, NodeWithScore, QueryBundle

class BaseNodePostprocessor(BaseComponent, DispatcherSpanMixin, ABC):
    model_config = ...
    callback_manager: CallbackManager = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def postprocess_nodes(self, nodes: List[NodeWithScore], query_bundle: Optional[QueryBundle] = ..., query_str: Optional[str] = ...) -> List[NodeWithScore]:
        """Postprocess nodes."""
        ...
    
    async def apostprocess_nodes(self, nodes: List[NodeWithScore], query_bundle: Optional[QueryBundle] = ..., query_str: Optional[str] = ...) -> List[NodeWithScore]:
        """Postprocess nodes (async)."""
        ...
    


