"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Optional

"""Base output parser class."""
@dataclass
class StructuredOutput:
    """Structured output class."""
    raw_output: str
    parsed_output: Optional[Any] = ...


class OutputParserException(Exception):
    ...


