"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, TYPE_CHECKING
from llama_index.core.output_parsers import BaseOutputParser
from llama_index.core.bridge.langchain import BaseOutputParser as LCOutputParser

"""Base output parser class."""
if TYPE_CHECKING:
    ...
class LangchainOutputParser(BaseOutputParser):
    """Langchain output parser."""
    def __init__(self, output_parser: LCOutputParser, format_key: Optional[str] = ...) -> None:
        """Init params."""
        ...
    
    def parse(self, output: str) -> Any:
        """Parse, validate, and correct errors programmatically."""
        ...
    
    def format(self, query: str) -> str:
        """Format a query with structured output formatting instructions."""
        ...
    


