"""
This type stub file was generated by pyright.
"""

from typing import Any, Generic, List, Optional, Type
from llama_index.core.output_parsers import BaseOutputParser
from llama_index.core.types import Model

"""Pydantic output parser."""
PYDANTIC_FORMAT_TMPL = ...
class PydanticOutputParser(BaseOutputParser, Generic[Model]):
    """
    Pydantic Output Parser.

    Args:
        output_cls (BaseModel): Pydantic output class.

    """
    def __init__(self, output_cls: Type[Model], excluded_schema_keys_from_format: Optional[List] = ..., pydantic_format_tmpl: str = ...) -> None:
        """Init params."""
        ...
    
    @property
    def output_cls(self) -> Type[Model]:
        ...
    
    @property
    def format_string(self) -> str:
        """Format string."""
        ...
    
    def get_format_string(self, escape_json: bool = ...) -> str:
        """Format string."""
        ...
    
    def parse(self, text: str) -> Any:
        """Parse, validate, and correct errors programmatically."""
        ...
    
    def format(self, query: str) -> str:
        """Format a query with structured output formatting instructions."""
        ...
    


