"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any
from dataclasses_json import DataClassJsonMixin
from llama_index.core.types import BaseOutputParser

FORMAT_STR = ...
@dataclass
class Answer(DataClassJsonMixin):
    choice: int
    reason: str
    ...


class SelectionOutputParser(BaseOutputParser):
    REQUIRED_KEYS = ...
    def parse(self, output: str) -> Any:
        ...
    
    def format(self, prompt_template: str) -> str:
        ...
    


