"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Callable, List, Sequence
from typing_extensions import Annotated
from llama_index.core.bridge.pydantic import BeforeValidator, Field, PlainSerializer, WithJsonSchema
from llama_index.core.callbacks import CallbackManager
from llama_index.core.schema import BaseNode, Document, TransformComponent

"""Node parser interface."""
IdFuncCallable = Annotated[Callable, Field(validate_default=True), BeforeValidator(_validate_id_func), WithJsonSchema({ "type": "string" }, mode="serialization"), WithJsonSchema({ "type": "string" }, mode="validation"), PlainSerializer(_serialize_id_func),]
class NodeParser(TransformComponent, ABC):
    """Base interface for node parser."""
    model_config = ...
    include_metadata: bool = ...
    include_prev_next_rel: bool = ...
    callback_manager: CallbackManager = ...
    id_func: IdFuncCallable = ...
    def get_nodes_from_documents(self, documents: Sequence[Document], show_progress: bool = ..., **kwargs: Any) -> List[BaseNode]:
        """
        Parse documents into nodes.

        Args:
            documents (Sequence[Document]): documents to parse
            show_progress (bool): whether to show progress bar

        """
        ...
    
    async def aget_nodes_from_documents(self, documents: Sequence[Document], show_progress: bool = ..., **kwargs: Any) -> List[BaseNode]:
        ...
    
    def __call__(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[BaseNode]:
        ...
    
    async def acall(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[BaseNode]:
        ...
    


class TextSplitter(NodeParser):
    @abstractmethod
    def split_text(self, text: str) -> List[str]:
        ...
    
    def split_texts(self, texts: List[str]) -> List[str]:
        ...
    


class MetadataAwareTextSplitter(TextSplitter):
    @abstractmethod
    def split_text_metadata_aware(self, text: str, metadata_str: str) -> List[str]:
        ...
    
    def split_texts_metadata_aware(self, texts: List[str], metadata_strs: List[str]) -> List[str]:
        ...
    


