"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.vector_store.base import VectorStoreIndex
from llama_index.core.vector_stores.types import MetadataFilters, VectorStoreQueryMode

"""Base vector store index query."""
dispatcher = ...
class VectorIndexRetriever(BaseRetriever):
    """
    Vector index retriever.

    Args:
        index (VectorStoreIndex): vector store index.
        similarity_top_k (int): number of top k results to return.
        vector_store_query_mode (str): vector store query mode
            See reference for VectorStoreQueryMode for full list of supported modes.
        filters (Optional[MetadataFilters]): metadata filters, defaults to None
        alpha (float): weight for sparse/dense retrieval, only used for
            hybrid query mode.
        doc_ids (Optional[List[str]]): list of documents to constrain search.
        vector_store_kwargs (dict): Additional vector store specific kwargs to pass
            through to the vector store at query time.

    """
    def __init__(self, index: VectorStoreIndex, similarity_top_k: int = ..., vector_store_query_mode: VectorStoreQueryMode = ..., filters: Optional[MetadataFilters] = ..., alpha: Optional[float] = ..., node_ids: Optional[List[str]] = ..., doc_ids: Optional[List[str]] = ..., sparse_top_k: Optional[int] = ..., hybrid_top_k: Optional[int] = ..., callback_manager: Optional[CallbackManager] = ..., object_map: Optional[dict] = ..., embed_model: Optional[BaseEmbedding] = ..., verbose: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @property
    def similarity_top_k(self) -> int:
        """Return similarity top k."""
        ...
    
    @similarity_top_k.setter
    def similarity_top_k(self, similarity_top_k: int) -> None:
        """Set similarity top k."""
        ...
    


