"""
This type stub file was generated by pyright.
"""

import fsspec
from typing import Any, Dict, List, Optional, Sequence, Tuple
from llama_index.core.graph_stores.types import LabelledNode, LabelledPropertyGraph, PropertyGraphStore, Relation, Triplet
from llama_index.core.vector_stores.types import VectorStoreQuery

class SimplePropertyGraphStore(PropertyGraphStore):
    """
    Simple Labelled Property Graph Store.

    This class implements a simple in-memory labelled property graph store.

    Args:
        graph (Optional[LabelledPropertyGraph]): Labelled property graph to initialize the store.

    """
    supports_structured_queries: bool = ...
    supports_vector_queries: bool = ...
    def __init__(self, graph: Optional[LabelledPropertyGraph] = ...) -> None:
        ...
    
    def get(self, properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[LabelledNode]:
        """Get nodes."""
        ...
    
    def get_triplets(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[Triplet]:
        """Get triplets."""
        ...
    
    def get_rel_map(self, graph_nodes: List[LabelledNode], depth: int = ..., limit: int = ..., ignore_rels: Optional[List[str]] = ...) -> List[Triplet]:
        """Get depth-aware rel map."""
        ...
    
    def upsert_nodes(self, nodes: Sequence[LabelledNode]) -> None:
        """Add nodes."""
        ...
    
    def upsert_relations(self, relations: List[Relation]) -> None:
        """Add relations."""
        ...
    
    def delete(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> None:
        """Delete matching data."""
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the graph store to a file."""
        ...
    
    @classmethod
    def from_persist_path(cls, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimplePropertyGraphStore:
        """Load from persist path."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimplePropertyGraphStore:
        """Load from persist dir."""
        ...
    
    @classmethod
    def from_dict(cls, data: dict) -> SimplePropertyGraphStore:
        """Load from dict."""
        ...
    
    def to_dict(self) -> dict:
        """Convert to dict."""
        ...
    
    def get_schema(self, refresh: bool = ...) -> str:
        """Get the schema of the graph store."""
        ...
    
    def structured_query(self, query: str, param_map: Optional[Dict[str, Any]] = ...) -> Any:
        """Query the graph store with statement and parameters."""
        ...
    
    def vector_query(self, query: VectorStoreQuery, **kwargs: Any) -> Tuple[List[LabelledNode], List[float]]:
        """Query the graph store with a vector store query."""
        ...
    
    @property
    def client(self) -> Any:
        """Get client."""
        ...
    
    def save_networkx_graph(self, name: str = ...) -> None:
        """Display the graph store, useful for debugging."""
        ...
    
    def show_jupyter_graph(self) -> None:
        """
        Visualizes the graph structure of the graph store.

        NOTE: This function requires yfiles_jupyter_graphs to be installed.
        NOTE: This method exclusively works in jupyter environments.

        """
        ...
    


