"""
This type stub file was generated by pyright.
"""

import fsspec
from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from dataclasses_json import DataClassJsonMixin
from llama_index.core.graph_stores.types import GraphStore

"""Simple graph store index."""
logger = ...
@dataclass
class SimpleGraphStoreData(DataClassJsonMixin):
    """
    Simple Graph Store Data container.

    Args:
        graph_dict (Optional[dict]): dict mapping subject to

    """
    graph_dict: Dict[str, List[List[str]]] = ...
    def get_rel_map(self, subjs: Optional[List[str]] = ..., depth: int = ..., limit: int = ...) -> Dict[str, List[List[str]]]:
        """Get subjects' rel map in max depth."""
        ...
    


class SimpleGraphStore(GraphStore):
    """
    Simple Graph Store.

    In this graph store, triplets are stored within a simple, in-memory dictionary.

    Args:
        simple_graph_store_data_dict (Optional[dict]): data dict
            containing the triplets. See SimpleGraphStoreData
            for more details.

    """
    def __init__(self, data: Optional[SimpleGraphStoreData] = ..., fs: Optional[fsspec.AbstractFileSystem] = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    @classmethod
    def from_persist_dir(cls, persist_dir: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleGraphStore:
        """Load from persist dir."""
        ...
    
    @property
    def client(self) -> None:
        """
        Get client.
        Not applicable for this store.
        """
        ...
    
    def get(self, subj: str) -> List[List[str]]:
        """Get triplets."""
        ...
    
    def get_rel_map(self, subjs: Optional[List[str]] = ..., depth: int = ..., limit: int = ...) -> Dict[str, List[List[str]]]:
        """Get depth-aware rel map."""
        ...
    
    def upsert_triplet(self, subj: str, rel: str, obj: str) -> None:
        """Add triplet."""
        ...
    
    def delete(self, subj: str, rel: str, obj: str) -> None:
        """Delete triplet."""
        ...
    
    def persist(self, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the SimpleGraphStore to a directory."""
        ...
    
    def get_schema(self, refresh: bool = ...) -> str:
        """Get the schema of the Simple Graph store."""
        ...
    
    def query(self, query: str, param_map: Optional[Dict[str, Any]] = ...) -> Any:
        """Query the Simple Graph store."""
        ...
    
    @classmethod
    def from_persist_path(cls, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleGraphStore:
        """Create a SimpleGraphStore from a persist directory."""
        ...
    
    @classmethod
    def from_dict(cls, save_dict: dict) -> SimpleGraphStore:
        ...
    
    def to_dict(self) -> dict:
        ...
    


