"""
This type stub file was generated by pyright.
"""

import fsspec
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Protocol, Sequence, Set, Tuple, runtime_checkable
from llama_index.core.bridge.pydantic import BaseModel, SerializeAsAny
from llama_index.core.prompts import PromptTemplate
from llama_index.core.schema import BaseNode
from llama_index.core.vector_stores.types import VectorStoreQuery

DEFAULT_PERSIST_DIR = ...
DEFAULT_PERSIST_FNAME = ...
DEFAULT_PG_PERSIST_FNAME = ...
TRIPLET_SOURCE_KEY = ...
VECTOR_SOURCE_KEY = ...
KG_NODES_KEY = ...
KG_RELATIONS_KEY = ...
KG_SOURCE_REL = ...
class LabelledNode(BaseModel):
    """An entity in a graph."""
    label: str = ...
    embedding: Optional[List[float]] = ...
    properties: Dict[str, Any] = ...
    @abstractmethod
    def __str__(self) -> str:
        """Return the string representation of the node."""
        ...
    
    @property
    @abstractmethod
    def id(self) -> str:
        """Get the node id."""
        ...
    


class EntityNode(LabelledNode):
    """An entity in a graph."""
    name: str = ...
    label: str = ...
    properties: Dict[str, Any] = ...
    def __str__(self) -> str:
        """Return the string representation of the node."""
        ...
    
    @property
    def id(self) -> str:
        """Get the node id."""
        ...
    


class ChunkNode(LabelledNode):
    """A text chunk in a graph."""
    text: str = ...
    id_: Optional[str] = ...
    label: str = ...
    properties: Dict[str, Any] = ...
    def __str__(self) -> str:
        """Return the string representation of the node."""
        ...
    
    @property
    def id(self) -> str:
        """Get the node id."""
        ...
    


class Relation(BaseModel):
    """A relation connecting two entities in a graph."""
    label: str
    source_id: str
    target_id: str
    properties: Dict[str, Any] = ...
    def __str__(self) -> str:
        """Return the string representation of the relation."""
        ...
    
    @property
    def id(self) -> str:
        """Get the relation id."""
        ...
    


Triplet = Tuple[LabelledNode, Relation, LabelledNode]
class LabelledPropertyGraph(BaseModel):
    """In memory labelled property graph containing entities and relations."""
    nodes: SerializeAsAny[Dict[str, LabelledNode]] = ...
    relations: SerializeAsAny[Dict[str, Relation]] = ...
    triplets: Set[Tuple[str, str, str]] = ...
    def get_all_nodes(self) -> List[LabelledNode]:
        """Get all entities."""
        ...
    
    def get_all_relations(self) -> List[Relation]:
        """Get all relations."""
        ...
    
    def get_triplets(self) -> List[Triplet]:
        """Get all triplets."""
        ...
    
    def add_triplet(self, triplet: Triplet) -> None:
        """Add a triplet."""
        ...
    
    def add_node(self, node: LabelledNode) -> None:
        """Add a node."""
        ...
    
    def add_relation(self, relation: Relation) -> None:
        """Add a relation."""
        ...
    
    def delete_triplet(self, triplet: Triplet) -> None:
        """Delete a triplet."""
        ...
    
    def delete_node(self, node: LabelledNode) -> None:
        """Delete a node."""
        ...
    
    def delete_relation(self, relation: Relation) -> None:
        """Delete a relation."""
        ...
    


@runtime_checkable
class GraphStore(Protocol):
    """
    Abstract graph store protocol.

    This protocol defines the interface for a graph store, which is responsible
    for storing and retrieving knowledge graph data.

    Attributes:
        client: Any: The client used to connect to the graph store.
        get: Callable[[str], List[List[str]]]: Get triplets for a given subject.
        get_rel_map: Callable[[Optional[List[str]], int], Dict[str, List[List[str]]]]:
            Get subjects' rel map in max depth.
        upsert_triplet: Callable[[str, str, str], None]: Upsert a triplet.
        delete: Callable[[str, str, str], None]: Delete a triplet.
        persist: Callable[[str, Optional[fsspec.AbstractFileSystem]], None]:
            Persist the graph store to a file.
        get_schema: Callable[[bool], str]: Get the schema of the graph store.

    """
    schema: str = ...
    @property
    def client(self) -> Any:
        """Get client."""
        ...
    
    def get(self, subj: str) -> List[List[str]]:
        """Get triplets."""
        ...
    
    def get_rel_map(self, subjs: Optional[List[str]] = ..., depth: int = ..., limit: int = ...) -> Dict[str, List[List[str]]]:
        """Get depth-aware rel map."""
        ...
    
    def upsert_triplet(self, subj: str, rel: str, obj: str) -> None:
        """Add triplet."""
        ...
    
    def delete(self, subj: str, rel: str, obj: str) -> None:
        """Delete triplet."""
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the graph store to a file."""
        ...
    
    def get_schema(self, refresh: bool = ...) -> str:
        """Get the schema of the graph store."""
        ...
    
    def query(self, query: str, param_map: Optional[Dict[str, Any]] = ...) -> Any:
        """Query the graph store with statement and parameters."""
        ...
    


class PropertyGraphStore(ABC):
    """
    Abstract labelled graph store protocol.

    This protocol defines the interface for a graph store, which is responsible
    for storing and retrieving knowledge graph data.

    Attributes:
        client: Any: The client used to connect to the graph store.
        get: Callable[[str], List[List[str]]]: Get triplets for a given subject.
        get_rel_map: Callable[[Optional[List[str]], int], Dict[str, List[List[str]]]]:
            Get subjects' rel map in max depth.
        upsert_triplet: Callable[[str, str, str], None]: Upsert a triplet.
        delete: Callable[[str, str, str], None]: Delete a triplet.
        persist: Callable[[str, Optional[fsspec.AbstractFileSystem]], None]:
            Persist the graph store to a file.

    """
    supports_structured_queries: bool = ...
    supports_vector_queries: bool = ...
    text_to_cypher_template: PromptTemplate = ...
    @property
    def client(self) -> Any:
        """Get client."""
        ...
    
    @abstractmethod
    def get(self, properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[LabelledNode]:
        """Get nodes with matching values."""
        ...
    
    @abstractmethod
    def get_triplets(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[Triplet]:
        """Get triplets with matching values."""
        ...
    
    @abstractmethod
    def get_rel_map(self, graph_nodes: List[LabelledNode], depth: int = ..., limit: int = ..., ignore_rels: Optional[List[str]] = ...) -> List[Triplet]:
        """Get depth-aware rel map."""
        ...
    
    def get_llama_nodes(self, node_ids: List[str]) -> List[BaseNode]:
        """Get llama-index nodes."""
        ...
    
    @abstractmethod
    def upsert_nodes(self, nodes: Sequence[LabelledNode]) -> None:
        """Upsert nodes."""
        ...
    
    @abstractmethod
    def upsert_relations(self, relations: List[Relation]) -> None:
        """Upsert relations."""
        ...
    
    def upsert_llama_nodes(self, llama_nodes: List[BaseNode]) -> None:
        """Add llama-index nodes."""
        ...
    
    @abstractmethod
    def delete(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> None:
        """Delete matching data."""
        ...
    
    def delete_llama_nodes(self, node_ids: Optional[List[str]] = ..., ref_doc_ids: Optional[List[str]] = ...) -> None:
        """
        Delete llama-index nodes.

        Intended to delete any nodes in the graph store associated
        with the given llama-index node_ids or ref_doc_ids.
        """
        ...
    
    @abstractmethod
    def structured_query(self, query: str, param_map: Optional[Dict[str, Any]] = ...) -> Any:
        """Query the graph store with statement and parameters."""
        ...
    
    @abstractmethod
    def vector_query(self, query: VectorStoreQuery, **kwargs: Any) -> Tuple[List[LabelledNode], List[float]]:
        """Query the graph store with a vector store query."""
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the graph store to a file."""
        ...
    
    def get_schema(self, refresh: bool = ...) -> Any:
        """Get the schema of the graph store."""
        ...
    
    def get_schema_str(self, refresh: bool = ...) -> str:
        """Get the schema of the graph store as a string."""
        ...
    
    async def aget(self, properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[LabelledNode]:
        """Asynchronously get nodes with matching values."""
        ...
    
    async def aget_triplets(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> List[Triplet]:
        """Asynchronously get triplets with matching values."""
        ...
    
    async def aget_rel_map(self, graph_nodes: List[LabelledNode], depth: int = ..., limit: int = ..., ignore_rels: Optional[List[str]] = ...) -> List[Triplet]:
        """Asynchronously get depth-aware rel map."""
        ...
    
    async def aget_llama_nodes(self, node_ids: List[str]) -> List[BaseNode]:
        """Asynchronously get nodes."""
        ...
    
    async def aupsert_nodes(self, nodes: List[LabelledNode]) -> None:
        """Asynchronously add nodes."""
        ...
    
    async def aupsert_relations(self, relations: List[Relation]) -> None:
        """Asynchronously add relations."""
        ...
    
    async def adelete(self, entity_names: Optional[List[str]] = ..., relation_names: Optional[List[str]] = ..., properties: Optional[dict] = ..., ids: Optional[List[str]] = ...) -> None:
        """Asynchronously delete matching data."""
        ...
    
    async def adelete_llama_nodes(self, node_ids: Optional[List[str]] = ..., ref_doc_ids: Optional[List[str]] = ...) -> None:
        """Asynchronously delete llama-index nodes."""
        ...
    
    async def astructured_query(self, query: str, param_map: Optional[Dict[str, Any]] = ...) -> Any:
        """Asynchronously query the graph store with statement and parameters."""
        ...
    
    async def avector_query(self, query: VectorStoreQuery, **kwargs: Any) -> Tuple[List[LabelledNode], List[float]]:
        """Asynchronously query the graph store with a vector store query."""
        ...
    
    async def aget_schema(self, refresh: bool = ...) -> str:
        """Asynchronously get the schema of the graph store."""
        ...
    
    async def aget_schema_str(self, refresh: bool = ...) -> str:
        """Asynchronously get the schema of the graph store as a string."""
        ...
    


