"""
This type stub file was generated by pyright.
"""

from typing import Any, Sequence
from llama_index.core.base.llms.types import ChatMessage, ChatResponse, ChatResponseAsyncGen, ChatResponseGen, CompletionResponse, CompletionResponseAsyncGen
from llama_index.core.llms.callbacks import llm_chat_callback, llm_completion_callback
from llama_index.core.llms.llm import LLM

class CustomLLM(LLM):
    """
    Simple abstract base class for custom LLMs.

    Subclasses must implement the `__init__`, `_complete`,
        `_stream_complete`, and `metadata` methods.
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    @llm_chat_callback()
    def chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        ...
    
    @llm_chat_callback()
    def stream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseGen:
        ...
    
    @llm_chat_callback()
    async def achat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        ...
    
    @llm_chat_callback()
    async def astream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseAsyncGen:
        ...
    
    @llm_completion_callback()
    async def acomplete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponse:
        ...
    
    @llm_completion_callback()
    async def astream_complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponseAsyncGen:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


