"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncGenerator, Dict, Generator, List, Optional, Protocol, Sequence, TYPE_CHECKING, Type, Union, runtime_checkable
from typing_extensions import Annotated
from llama_index.core.base.llms.types import ChatMessage, ChatResponseAsyncGen, ChatResponseGen, CompletionResponseAsyncGen, CompletionResponseGen
from llama_index.core.bridge.pydantic import BaseModel, WithJsonSchema, field_validator, model_validator
from llama_index.core.base.llms.base import BaseLLM
from llama_index.core.prompts import BasePromptTemplate, PromptTemplate
from llama_index.core.types import BaseOutputParser, Model, PydanticProgramMode, TokenAsyncGen, TokenGen
from llama_index.core.chat_engine.types import AgentChatResponse
from llama_index.core.program.utils import FlexibleModel
from llama_index.core.tools.types import BaseTool
from llama_index.core.llms.structured_llm import StructuredLLM

dispatcher = ...
if TYPE_CHECKING:
    ...
class ToolSelection(BaseModel):
    """Tool selection."""
    tool_id: str = ...
    tool_name: str = ...
    tool_kwargs: Dict[str, Any] = ...
    @field_validator("tool_kwargs", mode="wrap")
    @classmethod
    def ignore_non_dict_arguments(cls, v: Any, handler: Any) -> Dict[str, Any]:
        ...
    


@runtime_checkable
class MessagesToPromptType(Protocol):
    def __call__(self, messages: Sequence[ChatMessage]) -> str:
        ...
    


@runtime_checkable
class CompletionToPromptType(Protocol):
    def __call__(self, prompt: str) -> str:
        ...
    


def stream_completion_response_to_tokens(completion_response_gen: CompletionResponseGen) -> TokenGen:
    """Convert a stream completion response to a stream of tokens."""
    ...

def stream_chat_response_to_tokens(chat_response_gen: ChatResponseGen) -> TokenGen:
    """Convert a stream completion response to a stream of tokens."""
    ...

async def astream_completion_response_to_tokens(completion_response_gen: CompletionResponseAsyncGen) -> TokenAsyncGen:
    """Convert a stream completion response to a stream of tokens."""
    ...

async def astream_chat_response_to_tokens(chat_response_gen: ChatResponseAsyncGen) -> TokenAsyncGen:
    """Convert a stream completion response to a stream of tokens."""
    ...

def default_completion_to_prompt(prompt: str) -> str:
    ...

MessagesToPromptCallable = Annotated[Optional[MessagesToPromptType], WithJsonSchema({ "type": "string" }),]
CompletionToPromptCallable = Annotated[Optional[CompletionToPromptType], WithJsonSchema({ "type": "string" }),]
class LLM(BaseLLM):
    """
    The LLM class is the main class for interacting with language models.

    Attributes:
        system_prompt (Optional[str]):
            System prompt for LLM calls.
        messages_to_prompt (Callable):
            Function to convert a list of messages to an LLM prompt.
        completion_to_prompt (Callable):
            Function to convert a completion to an LLM prompt.
        output_parser (Optional[BaseOutputParser]):
            Output parser to parse, validate, and correct errors programmatically.
        pydantic_program_mode (PydanticProgramMode):
            Pydantic program mode to use for structured prediction.

    """
    system_prompt: Optional[str] = ...
    messages_to_prompt: MessagesToPromptCallable = ...
    completion_to_prompt: CompletionToPromptCallable = ...
    output_parser: Optional[BaseOutputParser] = ...
    pydantic_program_mode: PydanticProgramMode = ...
    query_wrapper_prompt: Optional[BasePromptTemplate] = ...
    @field_validator("messages_to_prompt")
    @classmethod
    def set_messages_to_prompt(cls, messages_to_prompt: Optional[MessagesToPromptType]) -> MessagesToPromptType:
        ...
    
    @field_validator("completion_to_prompt")
    @classmethod
    def set_completion_to_prompt(cls, completion_to_prompt: Optional[CompletionToPromptType]) -> CompletionToPromptType:
        ...
    
    @model_validator(mode="after")
    def check_prompts(self) -> LLM:
        ...
    
    @dispatcher.span
    def structured_predict(self, output_cls: Type[Model], prompt: PromptTemplate, llm_kwargs: Optional[Dict[str, Any]] = ..., **prompt_args: Any) -> Model:
        r"""
        Structured predict.

        Args:
            output_cls (BaseModel):
                Output class to use for structured prediction.
            prompt (PromptTemplate):
                Prompt template to use for structured prediction.
            llm_kwargs (Optional[Dict[str, Any]]):
                Arguments that are passed down to the LLM invoked by the program.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            BaseModel: The structured prediction output.

        Examples:
            ```python
            from pydantic import BaseModel

            class Test(BaseModel):
                \"\"\"My test class.\"\"\"
                name: str

            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please predict a Test with a random name related to {topic}.")
            output = llm.structured_predict(Test, prompt, topic="cats")
            print(output.name)
            ```

        """
        ...
    
    @dispatcher.span
    async def astructured_predict(self, output_cls: Type[Model], prompt: PromptTemplate, llm_kwargs: Optional[Dict[str, Any]] = ..., **prompt_args: Any) -> Model:
        r"""
        Async Structured predict.

        Args:
            output_cls (BaseModel):
                Output class to use for structured prediction.
            prompt (PromptTemplate):
                Prompt template to use for structured prediction.
            llm_kwargs (Optional[Dict[str, Any]]):
                Arguments that are passed down to the LLM invoked by the program.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            BaseModel: The structured prediction output.

        Examples:
            ```python
            from pydantic import BaseModel

            class Test(BaseModel):
                \"\"\"My test class.\"\"\"
                name: str

            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please predict a Test with a random name related to {topic}.")
            output = await llm.astructured_predict(Test, prompt, topic="cats")
            print(output.name)
            ```

        """
        ...
    
    @dispatcher.span
    def stream_structured_predict(self, output_cls: Type[Model], prompt: PromptTemplate, llm_kwargs: Optional[Dict[str, Any]] = ..., **prompt_args: Any) -> Generator[Union[Model, FlexibleModel], None, None]:
        r"""
        Stream Structured predict.

        Args:
            output_cls (BaseModel):
                Output class to use for structured prediction.
            prompt (PromptTemplate):
                Prompt template to use for structured prediction.
            llm_kwargs (Optional[Dict[str, Any]]):
                Arguments that are passed down to the LLM invoked by the program.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            Generator: A generator returning partial copies of the model or list of models.

        Examples:
            ```python
            from pydantic import BaseModel

            class Test(BaseModel):
                \"\"\"My test class.\"\"\"
                name: str

            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please predict a Test with a random name related to {topic}.")
            stream_output = llm.stream_structured_predict(Test, prompt, topic="cats")
            for partial_output in stream_output:
                # stream partial outputs until completion
                print(partial_output.name)
            ```

        """
        ...
    
    @dispatcher.span
    async def astream_structured_predict(self, output_cls: Type[Model], prompt: PromptTemplate, llm_kwargs: Optional[Dict[str, Any]] = ..., **prompt_args: Any) -> AsyncGenerator[Union[Model, FlexibleModel], None]:
        r"""
        Async Stream Structured predict.

        Args:
            output_cls (BaseModel):
                Output class to use for structured prediction.
            prompt (PromptTemplate):
                Prompt template to use for structured prediction.
            llm_kwargs (Optional[Dict[str, Any]]):
                Arguments that are passed down to the LLM invoked by the program.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            Generator: A generator returning partial copies of the model or list of models.

        Examples:
            ```python
            from pydantic import BaseModel

            class Test(BaseModel):
                \"\"\"My test class.\"\"\"
                name: str

            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please predict a Test with a random name related to {topic}.")
            stream_output = await llm.astream_structured_predict(Test, prompt, topic="cats")
            async for partial_output in stream_output:
                # stream partial outputs until completion
                print(partial_output.name)
            ```

        """
        ...
    
    @dispatcher.span
    def predict(self, prompt: BasePromptTemplate, **prompt_args: Any) -> str:
        """
        Predict for a given prompt.

        Args:
            prompt (BasePromptTemplate):
                The prompt to use for prediction.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            str: The prediction output.

        Examples:
            ```python
            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please write a random name related to {topic}.")
            output = llm.predict(prompt, topic="cats")
            print(output)
            ```

        """
        ...
    
    @dispatcher.span
    def stream(self, prompt: BasePromptTemplate, **prompt_args: Any) -> TokenGen:
        """
        Stream predict for a given prompt.

        Args:
            prompt (BasePromptTemplate):
                The prompt to use for prediction.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Yields:
            str: Each streamed token.

        Examples:
            ```python
            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please write a random name related to {topic}.")
            gen = llm.stream(prompt, topic="cats")
            for token in gen:
                print(token, end="", flush=True)
            ```

        """
        ...
    
    @dispatcher.span
    async def apredict(self, prompt: BasePromptTemplate, **prompt_args: Any) -> str:
        """
        Async Predict for a given prompt.

        Args:
            prompt (BasePromptTemplate):
                The prompt to use for prediction.
            prompt_args (Any):
                Additional arguments to format the prompt with.

        Returns:
            str: The prediction output.

        Examples:
            ```python
            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please write a random name related to {topic}.")
            output = await llm.apredict(prompt, topic="cats")
            print(output)
            ```

        """
        ...
    
    @dispatcher.span
    async def astream(self, prompt: BasePromptTemplate, **prompt_args: Any) -> TokenAsyncGen:
        """
        Async stream predict for a given prompt.

        Args:
        prompt (BasePromptTemplate):
            The prompt to use for prediction.
        prompt_args (Any):
            Additional arguments to format the prompt with.

        Yields:
            str: An async generator that yields strings of tokens.

        Examples:
            ```python
            from llama_index.core.prompts import PromptTemplate

            prompt = PromptTemplate("Please write a random name related to {topic}.")
            gen = await llm.astream(prompt, topic="cats")
            async for token in gen:
                print(token, end="", flush=True)
            ```

        """
        ...
    
    @dispatcher.span
    def predict_and_call(self, tools: List[BaseTool], user_msg: Optional[Union[str, ChatMessage]] = ..., chat_history: Optional[List[ChatMessage]] = ..., verbose: bool = ..., **kwargs: Any) -> AgentChatResponse:
        """
        Predict and call the tool.

        By default uses a ReAct agent to do tool calling (through text prompting),
        but function calling LLMs will implement this differently.

        """
        ...
    
    @dispatcher.span
    async def apredict_and_call(self, tools: List[BaseTool], user_msg: Optional[Union[str, ChatMessage]] = ..., chat_history: Optional[List[ChatMessage]] = ..., verbose: bool = ..., **kwargs: Any) -> AgentChatResponse:
        """Predict and call the tool."""
        ...
    
    def as_structured_llm(self, output_cls: Type[BaseModel], **kwargs: Any) -> StructuredLLM:
        """Return a structured LLM around a given object."""
        ...
    


