"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from llama_index.core.base.llms.types import ChatMessage, ChatResponseGen, CompletionResponse, CompletionResponseGen, LLMMetadata
from llama_index.core.callbacks import CallbackManager
from llama_index.core.llms.callbacks import llm_chat_callback, llm_completion_callback
from llama_index.core.llms.custom import CustomLLM
from llama_index.core.llms.llm import CompletionToPromptType, MessagesToPromptType
from llama_index.core.types import PydanticProgramMode

class MockLLM(CustomLLM):
    max_tokens: Optional[int]
    def __init__(self, max_tokens: Optional[int] = ..., callback_manager: Optional[CallbackManager] = ..., system_prompt: Optional[str] = ..., messages_to_prompt: Optional[MessagesToPromptType] = ..., completion_to_prompt: Optional[CompletionToPromptType] = ..., pydantic_program_mode: PydanticProgramMode = ...) -> None:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @property
    def metadata(self) -> LLMMetadata:
        ...
    
    @llm_completion_callback()
    def complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponse:
        ...
    
    @llm_completion_callback()
    def stream_complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponseGen:
        ...
    


class MockLLMWithNonyieldingChatStream(MockLLM):
    @llm_chat_callback()
    def stream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseGen:
        ...
    


