"""
This type stub file was generated by pyright.
"""

from typing import Any, Sequence, Type
from llama_index.core.base.llms.types import ChatMessage, ChatResponse, ChatResponseAsyncGen, ChatResponseGen, CompletionResponse, CompletionResponseGen, LLMMetadata
from llama_index.core.llms.llm import LLM
from llama_index.core.bridge.pydantic import BaseModel, SerializeAsAny
from llama_index.core.llms.callbacks import llm_chat_callback, llm_completion_callback

class StructuredLLM(LLM):
    """
    A structured LLM takes in an inner LLM along with a designated output class,
    and all methods will return outputs in that structure.

    """
    llm: SerializeAsAny[LLM]
    output_cls: Type[BaseModel] = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    @property
    def metadata(self) -> LLMMetadata:
        ...
    
    @llm_chat_callback()
    def chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        """Chat endpoint for LLM."""
        ...
    
    @llm_chat_callback()
    def stream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseGen:
        ...
    
    @llm_completion_callback()
    def complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponse:
        ...
    
    @llm_completion_callback()
    def stream_complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponseGen:
        """Stream completion endpoint for LLM."""
        ...
    
    @llm_chat_callback()
    async def achat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        ...
    
    @llm_chat_callback()
    async def astream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseAsyncGen:
        """Async stream chat endpoint for LLM."""
        ...
    
    @llm_completion_callback()
    async def acomplete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponse:
        ...
    
    @llm_completion_callback()
    async def astream_complete(self, prompt: str, formatted: bool = ..., **kwargs: Any) -> CompletionResponseGen:
        """Async stream completion endpoint for LLM."""
        ...
    


