"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Any, List, Optional, Sequence, Union
from llama_index.core.base.llms.types import ChatMessage, ChatResponse, ChatResponseAsyncGen, ChatResponseGen, CompletionResponse, CompletionResponseAsyncGen, CompletionResponseGen, ImageBlock
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks import CallbackManager
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.schema import BaseComponent, ImageNode

class MultiModalLLMMetadata(BaseModel):
    model_config = ...
    context_window: Optional[int] = ...
    num_output: Optional[int] = ...
    num_input_files: Optional[int] = ...
    is_function_calling_model: Optional[bool] = ...
    model_name: str = ...
    is_chat_model: bool = ...


class MultiModalLLM(BaseComponent, DispatcherSpanMixin):
    """Multi-Modal LLM interface."""
    model_config = ...
    callback_manager: CallbackManager = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    @property
    @abstractmethod
    def metadata(self) -> MultiModalLLMMetadata:
        """Multi-Modal LLM metadata."""
        ...
    
    @abstractmethod
    def complete(self, prompt: str, image_documents: List[Union[ImageNode, ImageBlock]], **kwargs: Any) -> CompletionResponse:
        """Completion endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    def stream_complete(self, prompt: str, image_documents: List[Union[ImageNode, ImageBlock]], **kwargs: Any) -> CompletionResponseGen:
        """Streaming completion endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    def chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        """Chat endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    def stream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseGen:
        """Stream chat endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    async def acomplete(self, prompt: str, image_documents: List[Union[ImageNode, ImageBlock]], **kwargs: Any) -> CompletionResponse:
        """Async completion endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    async def astream_complete(self, prompt: str, image_documents: List[Union[ImageNode, ImageBlock]], **kwargs: Any) -> CompletionResponseAsyncGen:
        """Async streaming completion endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    async def achat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        """Async chat endpoint for Multi-Modal LLM."""
        ...
    
    @abstractmethod
    async def astream_chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponseAsyncGen:
        """Async streaming chat endpoint for Multi-Modal LLM."""
        ...
    
    def __init_subclass__(cls, **kwargs: Any) -> None:
        """
        The callback decorators installs events, so they must be applied before
        the span decorators, otherwise the spans wouldn't contain the events.
        """
        ...
    


