"""
This type stub file was generated by pyright.
"""

from llama_index.core.storage.chat_store.base import BaseChatStore
from llama_index.core.storage.chat_store.simple_chat_store import SimpleChatStore

__all__ = ["BaseChatStore", "SimpleChatStore"]
