"""
This type stub file was generated by pyright.
"""

from llama_index.core.storage.chat_store.base import BaseChatStore

RECOGNIZED_CHAT_STORES = ...
def load_chat_store(data: dict) -> BaseChatStore:
    """Load a chat store from a dict."""
    ...

