"""
This type stub file was generated by pyright.
"""

import fsspec
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated
from llama_index.core.bridge.pydantic import WrapSerializer
from llama_index.core.llms import ChatMessage
from llama_index.core.storage.chat_store.base import BaseChatStore

def chat_message_serialization(chat_message: Any, handler: Any, info: Any) -> Dict[str, Any]:
    ...

AnnotatedChatMessage = Annotated[ChatMessage, WrapSerializer(chat_message_serialization)]
class SimpleChatStore(BaseChatStore):
    """Simple chat store. Async methods provide same functionality as sync methods in this class."""
    store: Dict[str, List[AnnotatedChatMessage]] = ...
    @classmethod
    def class_name(cls) -> str:
        """Get class name."""
        ...
    
    def set_messages(self, key: str, messages: List[ChatMessage]) -> None:
        """Set messages for a key."""
        ...
    
    def get_messages(self, key: str) -> List[ChatMessage]:
        """Get messages for a key."""
        ...
    
    def add_message(self, key: str, message: ChatMessage, idx: Optional[int] = ...) -> None:
        """Add a message for a key."""
        ...
    
    def delete_messages(self, key: str) -> Optional[List[ChatMessage]]:
        """Delete messages for a key."""
        ...
    
    def delete_message(self, key: str, idx: int) -> Optional[ChatMessage]:
        """Delete specific message for a key."""
        ...
    
    def delete_last_message(self, key: str) -> Optional[ChatMessage]:
        """Delete last message for a key."""
        ...
    
    def get_keys(self) -> List[str]:
        """Get all keys."""
        ...
    
    def persist(self, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the docstore to a file."""
        ...
    
    @classmethod
    def from_persist_path(cls, persist_path: str = ..., fs: Optional[fsspec.AbstractFileSystem] = ...) -> SimpleChatStore:
        """Create a SimpleChatStore from a persist path."""
        ...
    


