"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.bridge.pydantic import field_validator
from llama_index.core.memory.memory import BaseMemoryBlock
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.vector_stores.types import BasePydanticVectorStore

DEFAULT_RETRIEVED_TEXT_TEMPLATE = ...
def get_default_embed_model() -> BaseEmbedding:
    ...

class VectorMemoryBlock(BaseMemoryBlock[str]):
    """
    A memory block that retrieves relevant information from a vector store.

    This block stores conversation history in a vector store and retrieves
    relevant information based on the most recent messages.
    """
    name: str = ...
    vector_store: BasePydanticVectorStore = ...
    embed_model: BaseEmbedding = ...
    similarity_top_k: int = ...
    retrieval_context_window: int = ...
    format_template: BasePromptTemplate = ...
    node_postprocessors: List[BaseNodePostprocessor] = ...
    query_kwargs: Dict[str, Any] = ...
    @field_validator("vector_store", mode="before")
    def validate_vector_store(cls, v: Any) -> BasePydanticVectorStore:
        ...
    
    @field_validator("format_template", mode="before")
    @classmethod
    def validate_format_template(cls, v: Any) -> BasePromptTemplate:
        ...
    


