"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncGenerator, Dict, Generator, List, Optional, Type, Union
from llama_index.core.llms.function_calling import FunctionCallingLLM
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.types import BasePydanticProgram, Model
from llama_index.core.tools.function_tool import FunctionTool
from llama_index.core.program.utils import FlexibleModel

"""Pydantic program through function calling."""
_logger = ...
def get_function_tool(output_cls: Type[Model]) -> FunctionTool:
    """Get function tool."""
    ...

class FunctionCallingProgram(BasePydanticProgram[Model]):
    """
    Function Calling Program.

    Uses function calling LLMs to obtain a structured output.
    """
    def __init__(self, output_cls: Type[Model], llm: FunctionCallingLLM, prompt: BasePromptTemplate, tool_choice: Optional[Union[str, Dict[str, Any]]] = ..., allow_parallel_tool_calls: bool = ..., tool_required: bool = ..., verbose: bool = ...) -> None:
        """Init params."""
        ...
    
    @classmethod
    def from_defaults(cls, output_cls: Type[Model], prompt_template_str: Optional[str] = ..., prompt: Optional[BasePromptTemplate] = ..., llm: Optional[LLM] = ..., verbose: bool = ..., allow_parallel_tool_calls: bool = ..., tool_choice: Optional[Union[str, Dict[str, Any]]] = ..., tool_required: bool = ..., **kwargs: Any) -> FunctionCallingProgram:
        ...
    
    @property
    def output_cls(self) -> Type[Model]:
        ...
    
    @property
    def prompt(self) -> BasePromptTemplate:
        ...
    
    @prompt.setter
    def prompt(self, prompt: BasePromptTemplate) -> None:
        ...
    
    def __call__(self, *args: Any, llm_kwargs: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Union[Model, List[Model]]:
        ...
    
    async def acall(self, *args: Any, llm_kwargs: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Union[Model, List[Model]]:
        ...
    
    def stream_call(self, *args: Any, llm_kwargs: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Generator[Union[Model, List[Model], FlexibleModel, List[FlexibleModel]], None, None]:
        """
        Stream object.

        Returns a generator returning partials of the same object
        or a list of objects until it returns.
        """
        ...
    
    async def astream_call(self, *args: Any, llm_kwargs: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> AsyncGenerator[Union[Model, List[Model], FlexibleModel, List[FlexibleModel]], None]:
        """
        Stream objects.

        Returns a generator returning partials of the same object
        or a list of objects until it returns.
        """
        ...
    


