"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type, Union
from llama_index.core.base.llms.types import ChatResponse
from llama_index.core.program.utils import FlexibleModel
from llama_index.core.types import Model

"""
Simplified streaming utilities for processing structured outputs from message content.

This module provides utilities for processing streaming responses that contain
structured data directly in the message content (not in function calls).
"""
def process_streaming_content_incremental(chat_response: ChatResponse, output_cls: Type[Model], cur_object: Optional[Union[Model, FlexibleModel]] = ...) -> Union[Model, FlexibleModel]:
    """
    Process streaming response content with true incremental list handling.

    This version can extract partial progress from incomplete JSON and build
    lists incrementally (e.g., 1 joke → 2 jokes → 3 jokes) rather than
    jumping from empty to complete lists.

    Args:
        chat_response (ChatResponse): The chat response to process
        output_cls (Type[BaseModel]): The target output class
        cur_object (Optional[BaseModel]): Current best object (for comparison)
        flexible_mode (bool): Whether to use flexible schema during parsing

    Returns:
        Union[BaseModel, FlexibleModel]: Processed object with incremental updates

    """
    ...

