"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Sequence, Type, Union
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.llms.llm import LLM
from llama_index.core.llms.function_calling import FunctionCallingLLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.types import BasePydanticProgram, Model, PydanticProgramMode
from llama_index.core.base.llms.types import ChatResponse

"""Program utils."""
_logger = ...
class FlexibleModel(BaseModel):
    model_config = ...


def create_flexible_model(model: Type[BaseModel]) -> Type[FlexibleModel]:
    """Create a flexible version of the model that allows any fields."""
    ...

def create_list_model(base_cls: Type[BaseModel]) -> Type[BaseModel]:
    """Create a list version of an existing Pydantic object."""
    ...

def get_program_for_llm(output_cls: Type[Model], prompt: BasePromptTemplate, llm: LLM, pydantic_program_mode: PydanticProgramMode = ..., **kwargs: Any) -> BasePydanticProgram[Model]:
    """Get a program based on the compatible LLM."""
    ...

def process_streaming_objects(chat_response: ChatResponse, output_cls: Type[Model], cur_objects: Optional[Sequence[Model]] = ..., allow_parallel_tool_calls: bool = ..., flexible_mode: bool = ..., llm: Optional[FunctionCallingLLM] = ...) -> Union[Model, List[Model], FlexibleModel, List[FlexibleModel]]:
    """
    Process streaming response into structured objects.

    Args:
        chat_response (ChatResponse): The chat response to process
        output_cls (Type[BaseModel]): The target output class
        cur_objects (Optional[List[BaseModel]]): Current accumulated objects
        allow_parallel_tool_calls (bool): Whether to allow multiple tool calls
        flexible_mode (bool): Whether to use flexible schema during parsing

    Returns:
        Union[BaseModel, List[BaseModel]]: Processed object(s)

    """
    ...

def num_valid_fields(obj: Union[BaseModel, Sequence[BaseModel], Dict[str, BaseModel]]) -> int:
    """
    Recursively count the number of fields in a Pydantic object (including nested objects) that aren't None.

    Args:
        obj (Any): A Pydantic model instance or any other object.

    Returns:
        int: The number of fields that have non-None values.

    """
    ...

